// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advisory.sql

package store

import (
	"context"
)

const quickPlayBucketXactLock = `-- name: QuickPlayBucketXactLock :exec
SELECT pg_advisory_xact_lock($1::integer, $2::integer)
`

type QuickPlayBucketXactLockParams struct {
	LockClass int32 `json:"lock_class"`
	GameKey   int32 `json:"game_key"`
}

// Serializes quick-play find-or-create across app instances (released at transaction end).
func (q *Queries) QuickPlayBucketXactLock(ctx context.Context, arg QuickPlayBucketXactLockParams) error {
	_, err := q.db.Exec(ctx, quickPlayBucketXactLock, arg.LockClass, arg.GameKey)
	return err
}
