// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const completeGame = `-- name: CompleteGame :one
UPDATE game SET completed = TRUE, winner = $1 WHERE game_id = $2 RETURNING game_id, display_name, game, game_state, completed, winner, created_at
`

type CompleteGameParams struct {
	Winner *uuid.UUID `json:"winner"`
	GameID uuid.UUID  `json:"game_id"`
}

func (q *Queries) CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, completeGame, arg.Winner, arg.GameID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.Winner,
		&i.CreatedAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
   INSERT INTO game (game_id, display_name, game, game_state)
   VALUES ($1, $2, $3, $4)
RETURNING game_id, display_name, game, game_state, completed, winner, created_at
`

type CreateGameParams struct {
	GameID      uuid.UUID `json:"game_id"`
	DisplayName string    `json:"display_name"`
	Game        GameType  `json:"game"`
	GameState   []byte    `json:"game_state"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.GameID,
		arg.DisplayName,
		arg.Game,
		arg.GameState,
	)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.Winner,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByPlayer = `-- name: GetGameByPlayer :one
SELECT g.game_id, g.display_name, g.game, g.game_state, g.completed, g.winner, g.created_at
  FROM game g
           INNER JOIN game_player gp
           ON gp.game_id = g.game_id
 WHERE gp.player_id = $1
   AND NOT g.completed
`

func (q *Queries) GetGameByPlayer(ctx context.Context, playerID uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByPlayer, playerID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.Winner,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByPlayerForUpdate = `-- name: GetGameByPlayerForUpdate :one
SELECT g.game_id, g.display_name, g.game, g.game_state, g.completed, g.winner, g.created_at
  FROM game g
           INNER JOIN game_player gp
           ON gp.game_id = g.game_id
 WHERE gp.player_id = $1
   AND NOT g.completed
FOR UPDATE
`

func (q *Queries) GetGameByPlayerForUpdate(ctx context.Context, playerID uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByPlayerForUpdate, playerID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.Winner,
		&i.CreatedAt,
	)
	return i, err
}

const getGameIDByPlayer = `-- name: GetGameIDByPlayer :one
SELECT g.game_id FROM game g
INNER JOIN game_player gp
    ON gp.game_id = g.game_id
WHERE gp.player_id = $1
  AND NOT g.completed
`

func (q *Queries) GetGameIDByPlayer(ctx context.Context, playerID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getGameIDByPlayer, playerID)
	var game_id uuid.UUID
	err := row.Scan(&game_id)
	return game_id, err
}

const updateGameState = `-- name: UpdateGameState :one
   UPDATE game
      SET game_state = $1
    WHERE game_id = $2
RETURNING game_id, display_name, game, game_state, completed, winner, created_at
`

type UpdateGameStateParams struct {
	GameState []byte    `json:"game_state"`
	GameID    uuid.UUID `json:"game_id"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState, arg.GameState, arg.GameID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.Winner,
		&i.CreatedAt,
	)
	return i, err
}
