// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
   INSERT INTO game (display_name, game, game_state)
   VALUES ($1, $2, $3)
RETURNING game_id, display_name, game, game_state, completed, created_at
`

type CreateGameParams struct {
	DisplayName string   `json:"display_name"`
	Game        GameType `json:"game"`
	GameState   []byte   `json:"game_state"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.DisplayName, arg.Game, arg.GameState)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByPlayer = `-- name: GetGameByPlayer :one
SELECT g.game_id, g.display_name, g.game, g.game_state, g.completed, g.created_at
  FROM game g
           INNER JOIN game_player gp
           ON gp.game_id = g.game_id
 WHERE gp.player_id = $1
   AND NOT g.completed
`

func (q *Queries) GetGameByPlayer(ctx context.Context, playerID uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByPlayer, playerID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameState = `-- name: UpdateGameState :one
   UPDATE game
      SET game_state = $1
    WHERE game_id = $2
RETURNING game_id, display_name, game, game_state, completed, created_at
`

type UpdateGameStateParams struct {
	GameState []byte    `json:"game_state"`
	GameID    uuid.UUID `json:"game_id"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState, arg.GameState, arg.GameID)
	var i Game
	err := row.Scan(
		&i.GameID,
		&i.DisplayName,
		&i.Game,
		&i.GameState,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}
