// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_timeout.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteGameTimeout = `-- name: DeleteGameTimeout :one
DELETE FROM game_timeout WHERE game_id = $1 AND player_id = $2 and demand_id IS NOT DISTINCT FROM $3 RETURNING game_id, player_id, demand_id, token_id, created_at
`

type DeleteGameTimeoutParams struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
	DemandID *string   `json:"demand_id"`
}

func (q *Queries) DeleteGameTimeout(ctx context.Context, arg DeleteGameTimeoutParams) (GameTimeout, error) {
	row := q.db.QueryRow(ctx, deleteGameTimeout, arg.GameID, arg.PlayerID, arg.DemandID)
	var i GameTimeout
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.DemandID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}

const getGameTimeoutForUpdate = `-- name: GetGameTimeoutForUpdate :one
SELECT game_id, player_id, demand_id, token_id, created_at FROM game_timeout WHERE game_id = $1 AND player_id = $2 AND demand_id IS NOT DISTINCT FROM $3 FOR UPDATE
`

type GetGameTimeoutForUpdateParams struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
	DemandID *string   `json:"demand_id"`
}

func (q *Queries) GetGameTimeoutForUpdate(ctx context.Context, arg GetGameTimeoutForUpdateParams) (GameTimeout, error) {
	row := q.db.QueryRow(ctx, getGameTimeoutForUpdate, arg.GameID, arg.PlayerID, arg.DemandID)
	var i GameTimeout
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.DemandID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGameDemandTimeout = `-- name: UpsertGameDemandTimeout :one
INSERT INTO game_timeout (game_id, player_id, demand_id, token_id) VALUES ($1, $2, $3, $4)
    ON CONFLICT (game_id, player_id, demand_id) WHERE demand_id IS NOT NULL DO UPDATE SET
    token_id = EXCLUDED.token_id
    RETURNING game_id, player_id, demand_id, token_id, created_at
`

type UpsertGameDemandTimeoutParams struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
	DemandID *string   `json:"demand_id"`
	TokenID  uuid.UUID `json:"token_id"`
}

func (q *Queries) UpsertGameDemandTimeout(ctx context.Context, arg UpsertGameDemandTimeoutParams) (GameTimeout, error) {
	row := q.db.QueryRow(ctx, upsertGameDemandTimeout,
		arg.GameID,
		arg.PlayerID,
		arg.DemandID,
		arg.TokenID,
	)
	var i GameTimeout
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.DemandID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGameMoveTimeout = `-- name: UpsertGameMoveTimeout :one
INSERT INTO game_timeout (game_id, player_id, token_id) VALUES ($1, $2, $3)
    ON CONFLICT (game_id, player_id) WHERE demand_id IS NULL DO UPDATE SET
    token_id = EXCLUDED.token_id
    RETURNING game_id, player_id, demand_id, token_id, created_at
`

type UpsertGameMoveTimeoutParams struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
	TokenID  uuid.UUID `json:"token_id"`
}

func (q *Queries) UpsertGameMoveTimeout(ctx context.Context, arg UpsertGameMoveTimeoutParams) (GameTimeout, error) {
	row := q.db.QueryRow(ctx, upsertGameMoveTimeout, arg.GameID, arg.PlayerID, arg.TokenID)
	var i GameTimeout
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.DemandID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
