// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_player.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createGamePlayer = `-- name: CreateGamePlayer :one
   INSERT INTO game_player (game_id, player_id)
   VALUES ($1, $2)
RETURNING game_id, player_id
`

type CreateGamePlayerParams struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) CreateGamePlayer(ctx context.Context, arg CreateGamePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, createGamePlayer, arg.GameID, arg.PlayerID)
	var i GamePlayer
	err := row.Scan(&i.GameID, &i.PlayerID)
	return i, err
}

const createGamePlayersFromRoom = `-- name: CreateGamePlayersFromRoom :exec
INSERT INTO game_player(game_id, player_id)
SELECT $1, player_id
  FROM room_player
 WHERE room_id = $2
`

type CreateGamePlayersFromRoomParams struct {
	GameID uuid.UUID `json:"game_id"`
	RoomID uuid.UUID `json:"room_id"`
}

func (q *Queries) CreateGamePlayersFromRoom(ctx context.Context, arg CreateGamePlayersFromRoomParams) error {
	_, err := q.db.Exec(ctx, createGamePlayersFromRoom, arg.GameID, arg.RoomID)
	return err
}
