// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_history.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createGameHistory = `-- name: CreateGameHistory :one
INSERT INTO game_history (game_id, seq_num, action_kind, action_version, action) VALUES ($1, $2, $3, $4, $5) RETURNING game_id, seq_num, action_kind, action_version, action, created_at
`

type CreateGameHistoryParams struct {
	GameID        uuid.UUID `json:"game_id"`
	SeqNum        int16     `json:"seq_num"`
	ActionKind    string    `json:"action_kind"`
	ActionVersion int32     `json:"action_version"`
	Action        []byte    `json:"action"`
}

func (q *Queries) CreateGameHistory(ctx context.Context, arg CreateGameHistoryParams) (GameHistory, error) {
	row := q.db.QueryRow(ctx, createGameHistory,
		arg.GameID,
		arg.SeqNum,
		arg.ActionKind,
		arg.ActionVersion,
		arg.Action,
	)
	var i GameHistory
	err := row.Scan(
		&i.GameID,
		&i.SeqNum,
		&i.ActionKind,
		&i.ActionVersion,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const listGameHistory = `-- name: ListGameHistory :many
SELECT game_id, seq_num, action_kind, action_version, action, created_at FROM game_history WHERE game_id = $1 ORDER BY seq_num LIMIT $2 OFFSET $3
`

type ListGameHistoryParams struct {
	GameID uuid.UUID `json:"game_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListGameHistory(ctx context.Context, arg ListGameHistoryParams) ([]GameHistory, error) {
	rows, err := q.db.Query(ctx, listGameHistory, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameHistory{}
	for rows.Next() {
		var i GameHistory
		if err := rows.Scan(
			&i.GameID,
			&i.SeqNum,
			&i.ActionKind,
			&i.ActionVersion,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
