// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type GameType string

const (
	GameTypeMonopolyDeal GameType = "monopoly_deal"
)

func (e *GameType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameType(s)
	case string:
		*e = GameType(s)
	default:
		return fmt.Errorf("unsupported scan type for GameType: %T", src)
	}
	return nil
}

type NullGameType struct {
	GameType GameType `json:"game_type"`
	Valid    bool     `json:"valid"` // Valid is true if GameType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameType) Scan(value interface{}) error {
	if value == nil {
		ns.GameType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameType), nil
}

func (e GameType) Valid() bool {
	switch e {
	case GameTypeMonopolyDeal:
		return true
	}
	return false
}

func AllGameTypeValues() []GameType {
	return []GameType{
		GameTypeMonopolyDeal,
	}
}

type Game struct {
	GameID      uuid.UUID `json:"game_id"`
	DisplayName string    `json:"display_name"`
	Game        GameType  `json:"game"`
	Settings    []byte    `json:"settings"`
	GameState   []byte    `json:"game_state"`
	Completed   bool      `json:"completed"`
	CreatedAt   time.Time `json:"created_at"`
}

type GamePlayer struct {
	GameID   uuid.UUID `json:"game_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

type Player struct {
	PlayerID       uuid.UUID `json:"player_id"`
	DisplayName    string    `json:"display_name"`
	Email          string    `json:"email"`
	ImageUrl       string    `json:"image_url"`
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
}

type Room struct {
	RoomID      uuid.UUID `json:"room_id"`
	DisplayName string    `json:"display_name"`
	Capacity    int32     `json:"capacity"`
	Occupied    int32     `json:"occupied"`
	Game        GameType  `json:"game"`
	Settings    []byte    `json:"settings"`
	CreatedAt   time.Time `json:"created_at"`
}

type RoomPlayer struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
	IsReady  bool      `json:"is_ready"`
	IsHost   bool      `json:"is_host"`
	JoinedAt time.Time `json:"joined_at"`
}
