// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
)

type Player struct {
	PlayerID       uuid.UUID `json:"player_id"`
	DisplayName    string    `json:"display_name"`
	Email          string    `json:"email"`
	ImageUrl       string    `json:"image_url"`
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
}
