// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
   INSERT INTO player(display_name, email, image_url)
   VALUES ($1, $2, $3)
RETURNING player_id, display_name, email, image_url, refresh_token_id
`

type CreatePlayerParams struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
	ImageUrl    string `json:"image_url"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.DisplayName, arg.Email, arg.ImageUrl)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.DisplayName,
		&i.Email,
		&i.ImageUrl,
		&i.RefreshTokenID,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT player_id, display_name, email, image_url, refresh_token_id
  FROM player
 WHERE (player_id = $1 OR $1 IS NULL)
   AND (email = $2 OR $2 IS NULL)
   AND NOT ($1 IS NULL AND $2 IS NULL)
`

type GetPlayerParams struct {
	PlayerID *uuid.UUID `json:"player_id"`
	Email    *string    `json:"email"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.PlayerID, arg.Email)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.DisplayName,
		&i.Email,
		&i.ImageUrl,
		&i.RefreshTokenID,
	)
	return i, err
}

const getPlayers = `-- name: GetPlayers :many
SELECT player_id, display_name, email, image_url, refresh_token_id
  FROM player
 WHERE (played_id = ANY ($1::uuid[]))
`

func (q *Queries) GetPlayers(ctx context.Context, playerIds []uuid.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayers, playerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.PlayerID,
			&i.DisplayName,
			&i.Email,
			&i.ImageUrl,
			&i.RefreshTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByRoom = `-- name: GetPlayersByRoom :many
SELECT p.player_id, p.display_name, p.email, p.image_url, p.refresh_token_id, rp.is_ready, rp.is_host
  FROM player p
           INNER JOIN room_player rp
           ON rp.player_id = p.player_id
 WHERE rp.room_id = $1
 ORDER BY rp.joined_at
`

type GetPlayersByRoomRow struct {
	PlayerID       uuid.UUID `json:"player_id"`
	DisplayName    string    `json:"display_name"`
	Email          string    `json:"email"`
	ImageUrl       string    `json:"image_url"`
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
	IsReady        bool      `json:"is_ready"`
	IsHost         bool      `json:"is_host"`
}

func (q *Queries) GetPlayersByRoom(ctx context.Context, roomID uuid.UUID) ([]GetPlayersByRoomRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByRoomRow{}
	for rows.Next() {
		var i GetPlayersByRoomRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.DisplayName,
			&i.Email,
			&i.ImageUrl,
			&i.RefreshTokenID,
			&i.IsReady,
			&i.IsHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
   UPDATE player
      SET display_name = $1
    WHERE player_id = $2
RETURNING player_id, display_name, email, image_url, refresh_token_id
`

type UpdatePlayerParams struct {
	DisplayName string    `json:"display_name"`
	PlayerID    uuid.UUID `json:"player_id"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer, arg.DisplayName, arg.PlayerID)
	var i Player
	err := row.Scan(
		&i.PlayerID,
		&i.DisplayName,
		&i.Email,
		&i.ImageUrl,
		&i.RefreshTokenID,
	)
	return i, err
}
