// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
}

var _ Querier = (*Queries)(nil)
