// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimGameTimeouts(ctx context.Context, limit int32) ([]GameTimeout, error)
	ClaimGameTimeoutsByGame(ctx context.Context, arg ClaimGameTimeoutsByGameParams) ([]GameTimeout, error)
	CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGameHistory(ctx context.Context, arg CreateGameHistoryParams) (GameHistory, error)
	CreateGamePlayer(ctx context.Context, arg CreateGamePlayerParams) (GamePlayer, error)
	CreateGamePlayersFromRoom(ctx context.Context, arg CreateGamePlayersFromRoomParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (RoomPlayer, error)
	DecrementRoomOccupied(ctx context.Context, roomID uuid.UUID) (Room, error)
	DeleteGameTimeout(ctx context.Context, arg DeleteGameTimeoutParams) (GameTimeout, error)
	DeleteRoom(ctx context.Context, roomID uuid.UUID) error
	DeleteRoomPlayer(ctx context.Context, arg DeleteRoomPlayerParams) error
	DeleteRoomPlayersByRoom(ctx context.Context, roomID uuid.UUID) error
	GetGameByPlayer(ctx context.Context, playerID uuid.UUID) (Game, error)
	GetGameByPlayerForUpdate(ctx context.Context, playerID uuid.UUID) (Game, error)
	GetGameIDByPlayer(ctx context.Context, playerID uuid.UUID) (uuid.UUID, error)
	GetGameTimeoutForUpdate(ctx context.Context, arg GetGameTimeoutForUpdateParams) (GameTimeout, error)
	GetOldestRoomPlayer(ctx context.Context, arg GetOldestRoomPlayerParams) (RoomPlayer, error)
	GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error)
	GetPlayers(ctx context.Context, playerIds []uuid.UUID) ([]Player, error)
	GetPlayersByGame(ctx context.Context, gameID uuid.UUID) ([]Player, error)
	GetPlayersByRoom(ctx context.Context, roomID uuid.UUID) ([]GetPlayersByRoomRow, error)
	GetQuickPlayRoomForUpdate(ctx context.Context, game GameType) (Room, error)
	GetRoom(ctx context.Context, roomID uuid.UUID) (Room, error)
	GetRoomByPlayer(ctx context.Context, playerID uuid.UUID) (Room, error)
	GetRoomForUpdate(ctx context.Context, roomID uuid.UUID) (Room, error)
	GetRoomPlayer(ctx context.Context, playerID uuid.UUID) (RoomPlayer, error)
	GetRoomPlayerForUpdate(ctx context.Context, playerID uuid.UUID) (RoomPlayer, error)
	IncrementRoomOccupied(ctx context.Context, roomID uuid.UUID) (Room, error)
	ListGameHistory(ctx context.Context, arg ListGameHistoryParams) ([]GameHistory, error)
	ListGameTimeouts(ctx context.Context, gameID uuid.UUID) ([]GameTimeout, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error)
	// Serializes quick-play find-or-create across app instances (released at transaction end).
	QuickPlayBucketXactLock(ctx context.Context, arg QuickPlayBucketXactLockParams) error
	ToggleRoomPlayerIsReady(ctx context.Context, arg ToggleRoomPlayerIsReadyParams) (RoomPlayer, error)
	UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdateRoomCapacity(ctx context.Context, arg UpdateRoomCapacityParams) (Room, error)
	UpdateRoomOccupied(ctx context.Context, arg UpdateRoomOccupiedParams) (Room, error)
	UpdateRoomPlayerHost(ctx context.Context, arg UpdateRoomPlayerHostParams) (RoomPlayer, error)
	UpdateRoomSettings(ctx context.Context, arg UpdateRoomSettingsParams) (Room, error)
	UpsertGameDemandTimeout(ctx context.Context, arg UpsertGameDemandTimeoutParams) (GameTimeout, error)
	UpsertGameMoveTimeout(ctx context.Context, arg UpsertGameMoveTimeoutParams) (GameTimeout, error)
}

var _ Querier = (*Queries)(nil)
