// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO room(display_name, capacity)
    VALUES ($1, $2)
RETURNING
    room_id, display_name, capacity, room_status, game_state
`

type CreateRoomParams struct {
	DisplayName string `json:"display_name"`
	Capacity    int32  `json:"capacity"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.DisplayName, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.RoomStatus,
		&i.GameState,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT
    room_id, display_name, capacity, room_status, game_state
FROM
    room
WHERE (room_id = $1
    OR room_id ILIKE '%' || $1 || '%'
    OR display_name = $1
    OR display_name ILIKE '%' || $1 || '%'
    OR $1 IS NULL)
AND room_status <> 'completed'
`

func (q *Queries) ListRooms(ctx context.Context, searchTerm *uuid.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, searchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.DisplayName,
			&i.Capacity,
			&i.RoomStatus,
			&i.GameState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
