// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_player.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoomPlayer = `-- name: CreateRoomPlayer :one
INSERT INTO room_player(room_id, player_id, is_host)
    VALUES ($1, $2, $3)
RETURNING
    room_id, player_id, joined_at, is_host
`

type CreateRoomPlayerParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
	IsHost   bool      `json:"is_host"`
}

func (q *Queries) CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, createRoomPlayer, arg.RoomID, arg.PlayerID, arg.IsHost)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.JoinedAt,
		&i.IsHost,
	)
	return i, err
}

const deleteRoomPlayer = `-- name: DeleteRoomPlayer :exec
DELETE FROM room_player
WHERE room_id = $1
    AND player_id = $2
`

type DeleteRoomPlayerParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) DeleteRoomPlayer(ctx context.Context, arg DeleteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteRoomPlayer, arg.RoomID, arg.PlayerID)
	return err
}

const getRoomPlayerByPlayer = `-- name: GetRoomPlayerByPlayer :one
SELECT
    room_id, player_id, joined_at, is_host
FROM
    room_player
WHERE
    player_id = $1
`

func (q *Queries) GetRoomPlayerByPlayer(ctx context.Context, playerID uuid.UUID) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, getRoomPlayerByPlayer, playerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.JoinedAt,
		&i.IsHost,
	)
	return i, err
}

const getRoomPlayers = `-- name: GetRoomPlayers :many
SELECT
    rp.room_id,
    rp.joined_at,
    rp.is_host,
    p.player_id,
    p.display_name,
    p.email,
    p.image_url
FROM
    room_player rp
    INNER JOIN player p ON p.player_id = rp.player_id
WHERE
    rp.room_id = $1
`

type GetRoomPlayersRow struct {
	RoomID      uuid.UUID `json:"room_id"`
	JoinedAt    time.Time `json:"joined_at"`
	IsHost      bool      `json:"is_host"`
	PlayerID    uuid.UUID `json:"player_id"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	ImageUrl    string    `json:"image_url"`
}

func (q *Queries) GetRoomPlayers(ctx context.Context, roomID uuid.UUID) ([]GetRoomPlayersRow, error) {
	rows, err := q.db.Query(ctx, getRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomPlayersRow{}
	for rows.Next() {
		var i GetRoomPlayersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.JoinedAt,
			&i.IsHost,
			&i.PlayerID,
			&i.DisplayName,
			&i.Email,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomHost = `-- name: SetRoomHost :one
WITH oldest AS (
    SELECT
        room_id,
        player_id
    FROM (
        SELECT
            room_id,
            player_id,
            ROW_NUMBER() OVER (PARTITION BY room_id ORDER BY joined_at ASC) AS rn
    FROM
        room_player) t
    WHERE
        rn = 1)
UPDATE
    room_player rp
SET
    is_host =(rp.player_id = o.player_id)
FROM
    oldest o
WHERE
    rp.room_id = o.room_id
RETURNING
    rp.room_id, rp.player_id, rp.joined_at, rp.is_host
`

func (q *Queries) SetRoomHost(ctx context.Context) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, setRoomHost)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.JoinedAt,
		&i.IsHost,
	)
	return i, err
}
