// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
   INSERT INTO room (display_name, capacity, game, settings)
   VALUES ($1, $2, $3, $4)
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

type CreateRoomParams struct {
	DisplayName string `json:"display_name"`
	Capacity    int32  `json:"capacity"`
	Game        Game   `json:"game"`
	Settings    []byte `json:"settings"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.DisplayName,
		arg.Capacity,
		arg.Game,
		arg.Settings,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const decrementRoomOccupied = `-- name: DecrementRoomOccupied :one
   UPDATE room
      SET occupied = occupied - 1
    WHERE room_id = $1
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

func (q *Queries) DecrementRoomOccupied(ctx context.Context, roomID uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, decrementRoomOccupied, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE
  FROM room
 WHERE room_id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, roomID)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT room_id, display_name, capacity, occupied, game, settings, created_at
  FROM room
 WHERE room_id = $1
`

func (q *Queries) GetRoom(ctx context.Context, roomID uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByPlayer = `-- name: GetRoomByPlayer :one
SELECT r.room_id, r.display_name, r.capacity, r.occupied, r.game, r.settings, r.created_at
  FROM room r
           INNER JOIN room_player rp
           ON rp.room_id = r.room_id
 WHERE rp.player_id = $1
`

func (q *Queries) GetRoomByPlayer(ctx context.Context, playerID uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByPlayer, playerID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const incrementRoomOccupied = `-- name: IncrementRoomOccupied :one
   UPDATE room
      SET occupied = occupied + 1
    WHERE room_id = $1
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

func (q *Queries) IncrementRoomOccupied(ctx context.Context, roomID uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, incrementRoomOccupied, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT rp.room_id, rp.player_id, rp.is_ready, rp.is_host, rp.joined_at, r.display_name AS room_display_name, r.capacity AS room_capacity, r.occupied AS room_occupied,
       r.game AS room_game, r.settings AS room_settings, r.created_at AS room_created_at,
       p.display_name AS host_display_name, p.image_url AS host_image_url, COUNT(*) OVER () AS total_count
  FROM room_player rp
           INNER JOIN room r
           ON r.room_id = rp.room_id
           INNER JOIN player p
           ON p.player_id = rp.player_id
 WHERE (r.room_id::text = $3::text OR r.room_id::text ILIKE '%' || $3 || '%' OR
        p.player_id::text = $3 OR p.player_id::text ILIKE '%' || $3 || '%' OR
        r.display_name = $3 OR r.display_name ILIKE '%' || $3 || '%' OR
        p.display_name = $3 OR p.display_name ILIKE '%' || $3 || '%' OR
        $3 IS NULL)
   AND (r.game = $4 OR $4 IS NULL)
   AND rp.is_host
 ORDER BY r.display_name
 LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
	Search *string  `json:"search"`
	Game   NullGame `json:"game"`
}

type ListRoomsRow struct {
	RoomID          uuid.UUID `json:"room_id"`
	PlayerID        uuid.UUID `json:"player_id"`
	IsReady         bool      `json:"is_ready"`
	IsHost          bool      `json:"is_host"`
	JoinedAt        time.Time `json:"joined_at"`
	RoomDisplayName string    `json:"room_display_name"`
	RoomCapacity    int32     `json:"room_capacity"`
	RoomOccupied    int32     `json:"room_occupied"`
	RoomGame        Game      `json:"room_game"`
	RoomSettings    []byte    `json:"room_settings"`
	RoomCreatedAt   time.Time `json:"room_created_at"`
	HostDisplayName string    `json:"host_display_name"`
	HostImageUrl    string    `json:"host_image_url"`
	TotalCount      int64     `json:"total_count"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Game,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsRow{}
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.PlayerID,
			&i.IsReady,
			&i.IsHost,
			&i.JoinedAt,
			&i.RoomDisplayName,
			&i.RoomCapacity,
			&i.RoomOccupied,
			&i.RoomGame,
			&i.RoomSettings,
			&i.RoomCreatedAt,
			&i.HostDisplayName,
			&i.HostImageUrl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomCapacity = `-- name: UpdateRoomCapacity :one
   UPDATE room
      SET capacity = $1
    WHERE room_id = $2
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

type UpdateRoomCapacityParams struct {
	Capacity int32     `json:"capacity"`
	RoomID   uuid.UUID `json:"room_id"`
}

func (q *Queries) UpdateRoomCapacity(ctx context.Context, arg UpdateRoomCapacityParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomCapacity, arg.Capacity, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomOccupied = `-- name: UpdateRoomOccupied :one
   UPDATE room
      SET occupied = $1
    WHERE room_id = $2
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

type UpdateRoomOccupiedParams struct {
	Occupied int32     `json:"occupied"`
	RoomID   uuid.UUID `json:"room_id"`
}

func (q *Queries) UpdateRoomOccupied(ctx context.Context, arg UpdateRoomOccupiedParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomOccupied, arg.Occupied, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomSettings = `-- name: UpdateRoomSettings :one
   UPDATE room
      SET capacity = $1,
          game = $2,
          settings = $3
    WHERE room_id = $4
RETURNING room_id, display_name, capacity, occupied, game, settings, created_at
`

type UpdateRoomSettingsParams struct {
	Capacity int32     `json:"capacity"`
	Game     Game      `json:"game"`
	Settings []byte    `json:"settings"`
	RoomID   uuid.UUID `json:"room_id"`
}

func (q *Queries) UpdateRoomSettings(ctx context.Context, arg UpdateRoomSettingsParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomSettings,
		arg.Capacity,
		arg.Game,
		arg.Settings,
		arg.RoomID,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.DisplayName,
		&i.Capacity,
		&i.Occupied,
		&i.Game,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
