// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_player.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRoomPlayer = `-- name: CreateRoomPlayer :one
   INSERT INTO room_player (room_id, player_id, is_host)
   VALUES ($1, $2, $3)
RETURNING room_id, player_id, is_ready, is_host, joined_at
`

type CreateRoomPlayerParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
	IsHost   bool      `json:"is_host"`
}

func (q *Queries) CreateRoomPlayer(ctx context.Context, arg CreateRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, createRoomPlayer, arg.RoomID, arg.PlayerID, arg.IsHost)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.IsReady,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const deleteRoomPlayer = `-- name: DeleteRoomPlayer :exec
DELETE
  FROM room_player
 WHERE room_id = $1
   AND player_id = $2
`

type DeleteRoomPlayerParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) DeleteRoomPlayer(ctx context.Context, arg DeleteRoomPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteRoomPlayer, arg.RoomID, arg.PlayerID)
	return err
}

const deleteRoomPlayersByRoom = `-- name: DeleteRoomPlayersByRoom :exec
DELETE
  FROM room_player
 WHERE room_id = $1
`

func (q *Queries) DeleteRoomPlayersByRoom(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoomPlayersByRoom, roomID)
	return err
}

const getOldestRoomPlayer = `-- name: GetOldestRoomPlayer :one
SELECT room_id, player_id, is_ready, is_host, joined_at
  FROM room_player
 WHERE room_id = $1
   AND player_id <> $2
 ORDER BY joined_at
 LIMIT 1
`

type GetOldestRoomPlayerParams struct {
	RoomID          uuid.UUID `json:"room_id"`
	LeavingPlayerID uuid.UUID `json:"leaving_player_id"`
}

func (q *Queries) GetOldestRoomPlayer(ctx context.Context, arg GetOldestRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, getOldestRoomPlayer, arg.RoomID, arg.LeavingPlayerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.IsReady,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const getRoomPlayer = `-- name: GetRoomPlayer :one
SELECT room_id, player_id, is_ready, is_host, joined_at
  FROM room_player
 WHERE player_id = $1
`

func (q *Queries) GetRoomPlayer(ctx context.Context, playerID uuid.UUID) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, getRoomPlayer, playerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.IsReady,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const toggleRoomPlayerIsReady = `-- name: ToggleRoomPlayerIsReady :one
   UPDATE room_player
      SET is_ready = NOT is_ready
    WHERE room_id = $1
      AND player_id = $2
RETURNING room_id, player_id, is_ready, is_host, joined_at
`

type ToggleRoomPlayerIsReadyParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) ToggleRoomPlayerIsReady(ctx context.Context, arg ToggleRoomPlayerIsReadyParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, toggleRoomPlayerIsReady, arg.RoomID, arg.PlayerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.IsReady,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}

const updateRoomPlayerHost = `-- name: UpdateRoomPlayerHost :one
   UPDATE room_player
      SET is_host = $1
    WHERE room_id = $2
      AND player_id = $3
RETURNING room_id, player_id, is_ready, is_host, joined_at
`

type UpdateRoomPlayerHostParams struct {
	IsHost   bool      `json:"is_host"`
	RoomID   uuid.UUID `json:"room_id"`
	PlayerID uuid.UUID `json:"player_id"`
}

func (q *Queries) UpdateRoomPlayerHost(ctx context.Context, arg UpdateRoomPlayerHostParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, updateRoomPlayerHost, arg.IsHost, arg.RoomID, arg.PlayerID)
	var i RoomPlayer
	err := row.Scan(
		&i.RoomID,
		&i.PlayerID,
		&i.IsReady,
		&i.IsHost,
		&i.JoinedAt,
	)
	return i, err
}
