// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: monopoly_deal.proto

package monopoly_deal_schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetKey int32

const (
	AssetKey_ASSET_KEY_UNSPECIFIED           AssetKey = 0
	AssetKey_ASSET_KEY_BALTIC_AVE            AssetKey = 1
	AssetKey_ASSET_KEY_MEDITERRANEAN_AVE     AssetKey = 2
	AssetKey_ASSET_KEY_CONNECTICUT_AVE       AssetKey = 3
	AssetKey_ASSET_KEY_ORIENTAL_AVE          AssetKey = 4
	AssetKey_ASSET_KEY_VERMONT_AVE           AssetKey = 5
	AssetKey_ASSET_KEY_ST_CHARLES_PLACE      AssetKey = 6
	AssetKey_ASSET_KEY_VIRGINIA_AVE          AssetKey = 7
	AssetKey_ASSET_KEY_STATES_AVE            AssetKey = 8
	AssetKey_ASSET_KEY_NEW_YORK_AVE          AssetKey = 9
	AssetKey_ASSET_KEY_ST_JAMES_PLACE        AssetKey = 10
	AssetKey_ASSET_KEY_TENNESSEE_AVE         AssetKey = 11
	AssetKey_ASSET_KEY_KENTUCKY_AVE          AssetKey = 12
	AssetKey_ASSET_KEY_INDIANA_AVE           AssetKey = 13
	AssetKey_ASSET_KEY_ILLINOIS_AVE          AssetKey = 14
	AssetKey_ASSET_KEY_VENTNOR_AVE           AssetKey = 15
	AssetKey_ASSET_KEY_MARVIN_GARDENS        AssetKey = 16
	AssetKey_ASSET_KEY_ATLANTIC_AVE          AssetKey = 17
	AssetKey_ASSET_KEY_NORTH_CAROLINA_AVE    AssetKey = 18
	AssetKey_ASSET_KEY_PACIFIC_AVE           AssetKey = 19
	AssetKey_ASSET_KEY_PENNSYLVANIA_AVE      AssetKey = 20
	AssetKey_ASSET_KEY_BOARDWALK             AssetKey = 21
	AssetKey_ASSET_KEY_PARK_PLACE            AssetKey = 22
	AssetKey_ASSET_KEY_WATER_WORKS           AssetKey = 23
	AssetKey_ASSET_KEY_ELECTRIC_COMPANY      AssetKey = 24
	AssetKey_ASSET_KEY_SHORT_LINE            AssetKey = 25
	AssetKey_ASSET_KEY_B_AND_O_RAILROAD      AssetKey = 26
	AssetKey_ASSET_KEY_READING_RAILROAD      AssetKey = 27
	AssetKey_ASSET_KEY_PENNSYLVANIA_RAILROAD AssetKey = 28
	AssetKey_ASSET_KEY_WILD_BROWN_SKY        AssetKey = 29
	AssetKey_ASSET_KEY_WILD_SKY_RAILROAD     AssetKey = 30
	AssetKey_ASSET_KEY_WILD_PINK_ORANGE      AssetKey = 31
	AssetKey_ASSET_KEY_WILD_RED_YELLOW       AssetKey = 32
	AssetKey_ASSET_KEY_WILD_GREEN_BLUE       AssetKey = 33
	AssetKey_ASSET_KEY_WILD_GREEN_RAILROAD   AssetKey = 34
	AssetKey_ASSET_KEY_WILD_UTILITY_RAILROAD AssetKey = 35
	AssetKey_ASSET_KEY_WILD_WILD             AssetKey = 36
	AssetKey_ASSET_KEY_MONEY_10              AssetKey = 37
	AssetKey_ASSET_KEY_MONEY_5               AssetKey = 38
	AssetKey_ASSET_KEY_MONEY_4               AssetKey = 39
	AssetKey_ASSET_KEY_MONEY_3               AssetKey = 40
	AssetKey_ASSET_KEY_MONEY_2               AssetKey = 41
	AssetKey_ASSET_KEY_MONEY_1               AssetKey = 42
	AssetKey_ASSET_KEY_DEAL_BREAKER          AssetKey = 43
	AssetKey_ASSET_KEY_JUST_SAY_NO           AssetKey = 44
	AssetKey_ASSET_KEY_HOTEL                 AssetKey = 45
	AssetKey_ASSET_KEY_DEBT_COLLECTOR        AssetKey = 46
	AssetKey_ASSET_KEY_FORCED_DEAL           AssetKey = 47
	AssetKey_ASSET_KEY_SLY_DEAL              AssetKey = 48
	AssetKey_ASSET_KEY_HOUSE                 AssetKey = 49
	AssetKey_ASSET_KEY_ITS_MY_BIRTHDAY       AssetKey = 50
	AssetKey_ASSET_KEY_DOUBLE_THE_RENT       AssetKey = 51
	AssetKey_ASSET_KEY_PASS_GO               AssetKey = 52
	AssetKey_ASSET_KEY_RENT_WILD             AssetKey = 53
	AssetKey_ASSET_KEY_RENT_BROWN_SKY        AssetKey = 54
	AssetKey_ASSET_KEY_RENT_PINK_ORANGE      AssetKey = 55
	AssetKey_ASSET_KEY_RENT_RED_YELLOW       AssetKey = 56
	AssetKey_ASSET_KEY_RENT_GREEN_BLUE       AssetKey = 57
	AssetKey_ASSET_KEY_RENT_UTILITY_RAILROAD AssetKey = 58
)

// Enum value maps for AssetKey.
var (
	AssetKey_name = map[int32]string{
		0:  "ASSET_KEY_UNSPECIFIED",
		1:  "ASSET_KEY_BALTIC_AVE",
		2:  "ASSET_KEY_MEDITERRANEAN_AVE",
		3:  "ASSET_KEY_CONNECTICUT_AVE",
		4:  "ASSET_KEY_ORIENTAL_AVE",
		5:  "ASSET_KEY_VERMONT_AVE",
		6:  "ASSET_KEY_ST_CHARLES_PLACE",
		7:  "ASSET_KEY_VIRGINIA_AVE",
		8:  "ASSET_KEY_STATES_AVE",
		9:  "ASSET_KEY_NEW_YORK_AVE",
		10: "ASSET_KEY_ST_JAMES_PLACE",
		11: "ASSET_KEY_TENNESSEE_AVE",
		12: "ASSET_KEY_KENTUCKY_AVE",
		13: "ASSET_KEY_INDIANA_AVE",
		14: "ASSET_KEY_ILLINOIS_AVE",
		15: "ASSET_KEY_VENTNOR_AVE",
		16: "ASSET_KEY_MARVIN_GARDENS",
		17: "ASSET_KEY_ATLANTIC_AVE",
		18: "ASSET_KEY_NORTH_CAROLINA_AVE",
		19: "ASSET_KEY_PACIFIC_AVE",
		20: "ASSET_KEY_PENNSYLVANIA_AVE",
		21: "ASSET_KEY_BOARDWALK",
		22: "ASSET_KEY_PARK_PLACE",
		23: "ASSET_KEY_WATER_WORKS",
		24: "ASSET_KEY_ELECTRIC_COMPANY",
		25: "ASSET_KEY_SHORT_LINE",
		26: "ASSET_KEY_B_AND_O_RAILROAD",
		27: "ASSET_KEY_READING_RAILROAD",
		28: "ASSET_KEY_PENNSYLVANIA_RAILROAD",
		29: "ASSET_KEY_WILD_BROWN_SKY",
		30: "ASSET_KEY_WILD_SKY_RAILROAD",
		31: "ASSET_KEY_WILD_PINK_ORANGE",
		32: "ASSET_KEY_WILD_RED_YELLOW",
		33: "ASSET_KEY_WILD_GREEN_BLUE",
		34: "ASSET_KEY_WILD_GREEN_RAILROAD",
		35: "ASSET_KEY_WILD_UTILITY_RAILROAD",
		36: "ASSET_KEY_WILD_WILD",
		37: "ASSET_KEY_MONEY_10",
		38: "ASSET_KEY_MONEY_5",
		39: "ASSET_KEY_MONEY_4",
		40: "ASSET_KEY_MONEY_3",
		41: "ASSET_KEY_MONEY_2",
		42: "ASSET_KEY_MONEY_1",
		43: "ASSET_KEY_DEAL_BREAKER",
		44: "ASSET_KEY_JUST_SAY_NO",
		45: "ASSET_KEY_HOTEL",
		46: "ASSET_KEY_DEBT_COLLECTOR",
		47: "ASSET_KEY_FORCED_DEAL",
		48: "ASSET_KEY_SLY_DEAL",
		49: "ASSET_KEY_HOUSE",
		50: "ASSET_KEY_ITS_MY_BIRTHDAY",
		51: "ASSET_KEY_DOUBLE_THE_RENT",
		52: "ASSET_KEY_PASS_GO",
		53: "ASSET_KEY_RENT_WILD",
		54: "ASSET_KEY_RENT_BROWN_SKY",
		55: "ASSET_KEY_RENT_PINK_ORANGE",
		56: "ASSET_KEY_RENT_RED_YELLOW",
		57: "ASSET_KEY_RENT_GREEN_BLUE",
		58: "ASSET_KEY_RENT_UTILITY_RAILROAD",
	}
	AssetKey_value = map[string]int32{
		"ASSET_KEY_UNSPECIFIED":           0,
		"ASSET_KEY_BALTIC_AVE":            1,
		"ASSET_KEY_MEDITERRANEAN_AVE":     2,
		"ASSET_KEY_CONNECTICUT_AVE":       3,
		"ASSET_KEY_ORIENTAL_AVE":          4,
		"ASSET_KEY_VERMONT_AVE":           5,
		"ASSET_KEY_ST_CHARLES_PLACE":      6,
		"ASSET_KEY_VIRGINIA_AVE":          7,
		"ASSET_KEY_STATES_AVE":            8,
		"ASSET_KEY_NEW_YORK_AVE":          9,
		"ASSET_KEY_ST_JAMES_PLACE":        10,
		"ASSET_KEY_TENNESSEE_AVE":         11,
		"ASSET_KEY_KENTUCKY_AVE":          12,
		"ASSET_KEY_INDIANA_AVE":           13,
		"ASSET_KEY_ILLINOIS_AVE":          14,
		"ASSET_KEY_VENTNOR_AVE":           15,
		"ASSET_KEY_MARVIN_GARDENS":        16,
		"ASSET_KEY_ATLANTIC_AVE":          17,
		"ASSET_KEY_NORTH_CAROLINA_AVE":    18,
		"ASSET_KEY_PACIFIC_AVE":           19,
		"ASSET_KEY_PENNSYLVANIA_AVE":      20,
		"ASSET_KEY_BOARDWALK":             21,
		"ASSET_KEY_PARK_PLACE":            22,
		"ASSET_KEY_WATER_WORKS":           23,
		"ASSET_KEY_ELECTRIC_COMPANY":      24,
		"ASSET_KEY_SHORT_LINE":            25,
		"ASSET_KEY_B_AND_O_RAILROAD":      26,
		"ASSET_KEY_READING_RAILROAD":      27,
		"ASSET_KEY_PENNSYLVANIA_RAILROAD": 28,
		"ASSET_KEY_WILD_BROWN_SKY":        29,
		"ASSET_KEY_WILD_SKY_RAILROAD":     30,
		"ASSET_KEY_WILD_PINK_ORANGE":      31,
		"ASSET_KEY_WILD_RED_YELLOW":       32,
		"ASSET_KEY_WILD_GREEN_BLUE":       33,
		"ASSET_KEY_WILD_GREEN_RAILROAD":   34,
		"ASSET_KEY_WILD_UTILITY_RAILROAD": 35,
		"ASSET_KEY_WILD_WILD":             36,
		"ASSET_KEY_MONEY_10":              37,
		"ASSET_KEY_MONEY_5":               38,
		"ASSET_KEY_MONEY_4":               39,
		"ASSET_KEY_MONEY_3":               40,
		"ASSET_KEY_MONEY_2":               41,
		"ASSET_KEY_MONEY_1":               42,
		"ASSET_KEY_DEAL_BREAKER":          43,
		"ASSET_KEY_JUST_SAY_NO":           44,
		"ASSET_KEY_HOTEL":                 45,
		"ASSET_KEY_DEBT_COLLECTOR":        46,
		"ASSET_KEY_FORCED_DEAL":           47,
		"ASSET_KEY_SLY_DEAL":              48,
		"ASSET_KEY_HOUSE":                 49,
		"ASSET_KEY_ITS_MY_BIRTHDAY":       50,
		"ASSET_KEY_DOUBLE_THE_RENT":       51,
		"ASSET_KEY_PASS_GO":               52,
		"ASSET_KEY_RENT_WILD":             53,
		"ASSET_KEY_RENT_BROWN_SKY":        54,
		"ASSET_KEY_RENT_PINK_ORANGE":      55,
		"ASSET_KEY_RENT_RED_YELLOW":       56,
		"ASSET_KEY_RENT_GREEN_BLUE":       57,
		"ASSET_KEY_RENT_UTILITY_RAILROAD": 58,
	}
)

func (x AssetKey) Enum() *AssetKey {
	p := new(AssetKey)
	*p = x
	return p
}

func (x AssetKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKey) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[0].Descriptor()
}

func (AssetKey) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[0]
}

func (x AssetKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKey.Descriptor instead.
func (AssetKey) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED   Category = 0
	Category_CATEGORY_PURE_PROPERTY Category = 1
	Category_CATEGORY_WILD_PROPERTY Category = 2
	Category_CATEGORY_MONEY         Category = 3
	Category_CATEGORY_ACTION        Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_PURE_PROPERTY",
		2: "CATEGORY_WILD_PROPERTY",
		3: "CATEGORY_MONEY",
		4: "CATEGORY_ACTION",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":   0,
		"CATEGORY_PURE_PROPERTY": 1,
		"CATEGORY_WILD_PROPERTY": 2,
		"CATEGORY_MONEY":         3,
		"CATEGORY_ACTION":        4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_BROWN       Color = 1
	Color_COLOR_SKY         Color = 2
	Color_COLOR_PINK        Color = 3
	Color_COLOR_ORANGE      Color = 4
	Color_COLOR_RED         Color = 5
	Color_COLOR_YELLOW      Color = 6
	Color_COLOR_GREEN       Color = 7
	Color_COLOR_BLUE        Color = 8
	Color_COLOR_UTILITY     Color = 9
	Color_COLOR_RAILROAD    Color = 10
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0:  "COLOR_UNSPECIFIED",
		1:  "COLOR_BROWN",
		2:  "COLOR_SKY",
		3:  "COLOR_PINK",
		4:  "COLOR_ORANGE",
		5:  "COLOR_RED",
		6:  "COLOR_YELLOW",
		7:  "COLOR_GREEN",
		8:  "COLOR_BLUE",
		9:  "COLOR_UTILITY",
		10: "COLOR_RAILROAD",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_BROWN":       1,
		"COLOR_SKY":         2,
		"COLOR_PINK":        3,
		"COLOR_ORANGE":      4,
		"COLOR_RED":         5,
		"COLOR_YELLOW":      6,
		"COLOR_GREEN":       7,
		"COLOR_BLUE":        8,
		"COLOR_UTILITY":     9,
		"COLOR_RAILROAD":    10,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[2].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[2]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

type DemandKind int32

const (
	DemandKind_DEMAND_KIND_UNSPECIFIED  DemandKind = 0
	DemandKind_DEMAND_KIND_PAYMENT      DemandKind = 1
	DemandKind_DEMAND_KIND_PROPERTY     DemandKind = 2
	DemandKind_DEMAND_KIND_PROPERTY_SET DemandKind = 3
)

// Enum value maps for DemandKind.
var (
	DemandKind_name = map[int32]string{
		0: "DEMAND_KIND_UNSPECIFIED",
		1: "DEMAND_KIND_PAYMENT",
		2: "DEMAND_KIND_PROPERTY",
		3: "DEMAND_KIND_PROPERTY_SET",
	}
	DemandKind_value = map[string]int32{
		"DEMAND_KIND_UNSPECIFIED":  0,
		"DEMAND_KIND_PAYMENT":      1,
		"DEMAND_KIND_PROPERTY":     2,
		"DEMAND_KIND_PROPERTY_SET": 3,
	}
)

func (x DemandKind) Enum() *DemandKind {
	p := new(DemandKind)
	*p = x
	return p
}

func (x DemandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DemandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[3].Descriptor()
}

func (DemandKind) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[3]
}

func (x DemandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DemandKind.Descriptor instead.
func (DemandKind) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_monopoly_deal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_monopoly_deal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

func (x *Chat) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ChatReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReceived) Reset() {
	*x = ChatReceived{}
	mi := &file_monopoly_deal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReceived) ProtoMessage() {}

func (x *ChatReceived) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReceived.ProtoReflect.Descriptor instead.
func (*ChatReceived) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

func (x *ChatReceived) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatReceived) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AssetKey      AssetKey               `protobuf:"varint,2,opt,name=asset_key,json=assetKey,proto3,enum=fun_kames.schema.monopoly_deal.AssetKey" json:"asset_key,omitempty"`
	Category      Category               `protobuf:"varint,3,opt,name=category,proto3,enum=fun_kames.schema.monopoly_deal.Category" json:"category,omitempty"`
	ActiveColor   Color                  `protobuf:"varint,4,opt,name=active_color,json=activeColor,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"active_color,omitempty"`
	Colors        []Color                `protobuf:"varint,5,rep,packed,name=colors,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"colors,omitempty"`
	Value         int32                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_monopoly_deal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetAssetKey() AssetKey {
	if x != nil {
		return x.AssetKey
	}
	return AssetKey_ASSET_KEY_UNSPECIFIED
}

func (x *Card) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Card) GetActiveColor() Color {
	if x != nil {
		return x.ActiveColor
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Card) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Card) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Money         int32                  `protobuf:"varint,4,opt,name=money,proto3" json:"money,omitempty"`
	CompletedSets int32                  `protobuf:"varint,5,opt,name=completed_sets,json=completedSets,proto3" json:"completed_sets,omitempty"`
	HandCards     int32                  `protobuf:"varint,6,opt,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_monopoly_deal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Player) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Player) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Player) GetCompletedSets() int32 {
	if x != nil {
		return x.CompletedSets
	}
	return 0
}

func (x *Player) GetHandCards() int32 {
	if x != nil {
		return x.HandCards
	}
	return 0
}

type Hand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hand) Reset() {
	*x = Hand{}
	mi := &file_monopoly_deal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hand) ProtoMessage() {}

func (x *Hand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hand.ProtoReflect.Descriptor instead.
func (*Hand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{5}
}

func (x *Hand) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_monopoly_deal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{6}
}

func (x *Money) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Money) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PropertySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySetId string                 `protobuf:"bytes,2,opt,name=property_set_id,json=propertySetId,proto3" json:"property_set_id,omitempty"`
	Color         Color                  `protobuf:"varint,3,opt,name=color,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"color,omitempty"`
	Cards         []*Card                `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySet) Reset() {
	*x = PropertySet{}
	mi := &file_monopoly_deal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySet) ProtoMessage() {}

func (x *PropertySet) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySet.ProtoReflect.Descriptor instead.
func (*PropertySet) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{7}
}

func (x *PropertySet) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PropertySet) GetPropertySetId() string {
	if x != nil {
		return x.PropertySetId
	}
	return ""
}

func (x *PropertySet) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *PropertySet) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PaymentDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDemand) Reset() {
	*x = PaymentDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDemand) ProtoMessage() {}

func (x *PaymentDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDemand.ProtoReflect.Descriptor instead.
func (*PaymentDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentDemand) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PropertyDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCardId  *string                `protobuf:"bytes,1,opt,name=source_card_id,json=sourceCardId,proto3,oneof" json:"source_card_id,omitempty"`
	TargetCardId  string                 `protobuf:"bytes,2,opt,name=target_card_id,json=targetCardId,proto3" json:"target_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyDemand) Reset() {
	*x = PropertyDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyDemand) ProtoMessage() {}

func (x *PropertyDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyDemand.ProtoReflect.Descriptor instead.
func (*PropertyDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{9}
}

func (x *PropertyDemand) GetSourceCardId() string {
	if x != nil && x.SourceCardId != nil {
		return *x.SourceCardId
	}
	return ""
}

func (x *PropertyDemand) GetTargetCardId() string {
	if x != nil {
		return x.TargetCardId
	}
	return ""
}

type PropertySetDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertySetId string                 `protobuf:"bytes,1,opt,name=property_set_id,json=propertySetId,proto3" json:"property_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySetDemand) Reset() {
	*x = PropertySetDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySetDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySetDemand) ProtoMessage() {}

func (x *PropertySetDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySetDemand.ProtoReflect.Descriptor instead.
func (*PropertySetDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{10}
}

func (x *PropertySetDemand) GetPropertySetId() string {
	if x != nil {
		return x.PropertySetId
	}
	return ""
}

type Demand struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceId   string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DemandKind DemandKind             `protobuf:"varint,2,opt,name=demand_kind,json=demandKind,proto3,enum=fun_kames.schema.monopoly_deal.DemandKind" json:"demand_kind,omitempty"`
	// Types that are valid to be assigned to Demand:
	//
	//	*Demand_PaymentDemand
	//	*Demand_PropertyDemand
	//	*Demand_PropertySetDemand
	Demand        isDemand_Demand `protobuf_oneof:"demand"`
	IsActive      bool            `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demand) Reset() {
	*x = Demand{}
	mi := &file_monopoly_deal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demand) ProtoMessage() {}

func (x *Demand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demand.ProtoReflect.Descriptor instead.
func (*Demand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{11}
}

func (x *Demand) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Demand) GetDemandKind() DemandKind {
	if x != nil {
		return x.DemandKind
	}
	return DemandKind_DEMAND_KIND_UNSPECIFIED
}

func (x *Demand) GetDemand() isDemand_Demand {
	if x != nil {
		return x.Demand
	}
	return nil
}

func (x *Demand) GetPaymentDemand() *PaymentDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PaymentDemand); ok {
			return x.PaymentDemand
		}
	}
	return nil
}

func (x *Demand) GetPropertyDemand() *PropertyDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PropertyDemand); ok {
			return x.PropertyDemand
		}
	}
	return nil
}

func (x *Demand) GetPropertySetDemand() *PropertySetDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PropertySetDemand); ok {
			return x.PropertySetDemand
		}
	}
	return nil
}

func (x *Demand) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type isDemand_Demand interface {
	isDemand_Demand()
}

type Demand_PaymentDemand struct {
	PaymentDemand *PaymentDemand `protobuf:"bytes,3,opt,name=payment_demand,json=paymentDemand,proto3,oneof"`
}

type Demand_PropertyDemand struct {
	PropertyDemand *PropertyDemand `protobuf:"bytes,4,opt,name=property_demand,json=propertyDemand,proto3,oneof"`
}

type Demand_PropertySetDemand struct {
	PropertySetDemand *PropertySetDemand `protobuf:"bytes,5,opt,name=property_set_demand,json=propertySetDemand,proto3,oneof"`
}

func (*Demand_PaymentDemand) isDemand_Demand() {}

func (*Demand_PropertyDemand) isDemand_Demand() {}

func (*Demand_PropertySetDemand) isDemand_Demand() {}

type PendingRent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetIds     []string               `protobuf:"bytes,2,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	BaseAmount    int32                  `protobuf:"varint,3,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	Multiplier    int32                  `protobuf:"varint,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRent) Reset() {
	*x = PendingRent{}
	mi := &file_monopoly_deal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRent) ProtoMessage() {}

func (x *PendingRent) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRent.ProtoReflect.Descriptor instead.
func (*PendingRent) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{12}
}

func (x *PendingRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PendingRent) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *PendingRent) GetBaseAmount() int32 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *PendingRent) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type AssetImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetKey      AssetKey               `protobuf:"varint,1,opt,name=asset_key,json=assetKey,proto3,enum=fun_kames.schema.monopoly_deal.AssetKey" json:"asset_key,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetImage) Reset() {
	*x = AssetImage{}
	mi := &file_monopoly_deal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetImage) ProtoMessage() {}

func (x *AssetImage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetImage.ProtoReflect.Descriptor instead.
func (*AssetImage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{13}
}

func (x *AssetImage) GetAssetKey() AssetKey {
	if x != nil {
		return x.AssetKey
	}
	return AssetKey_ASSET_KEY_UNSPECIFIED
}

func (x *AssetImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GameState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SeqNum          int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Players         []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	CurrentPlayerId string                 `protobuf:"bytes,3,opt,name=current_player_id,json=currentPlayerId,proto3" json:"current_player_id,omitempty"`
	MovesLeft       int32                  `protobuf:"varint,4,opt,name=moves_left,json=movesLeft,proto3" json:"moves_left,omitempty"`
	YourHand        *Hand                  `protobuf:"bytes,5,opt,name=your_hand,json=yourHand,proto3" json:"your_hand,omitempty"`
	Money           []*Money               `protobuf:"bytes,6,rep,name=money,proto3" json:"money,omitempty"`
	Properties      []*PropertySet         `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty"`
	Demand          *Demand                `protobuf:"bytes,8,opt,name=demand,proto3,oneof" json:"demand,omitempty"`
	PendingRent     *PendingRent           `protobuf:"bytes,9,opt,name=pending_rent,json=pendingRent,proto3,oneof" json:"pending_rent,omitempty"`
	LastAction      *Card                  `protobuf:"bytes,10,opt,name=last_action,json=lastAction,proto3" json:"last_action,omitempty"`
	AssetImages     []*AssetImage          `protobuf:"bytes,11,rep,name=asset_images,json=assetImages,proto3" json:"asset_images,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_monopoly_deal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{14}
}

func (x *GameState) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *GameState) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetCurrentPlayerId() string {
	if x != nil {
		return x.CurrentPlayerId
	}
	return ""
}

func (x *GameState) GetMovesLeft() int32 {
	if x != nil {
		return x.MovesLeft
	}
	return 0
}

func (x *GameState) GetYourHand() *Hand {
	if x != nil {
		return x.YourHand
	}
	return nil
}

func (x *GameState) GetMoney() []*Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *GameState) GetProperties() []*PropertySet {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GameState) GetDemand() *Demand {
	if x != nil {
		return x.Demand
	}
	return nil
}

func (x *GameState) GetPendingRent() *PendingRent {
	if x != nil {
		return x.PendingRent
	}
	return nil
}

func (x *GameState) GetLastAction() *Card {
	if x != nil {
		return x.LastAction
	}
	return nil
}

func (x *GameState) GetAssetImages() []*AssetImage {
	if x != nil {
		return x.AssetImages
	}
	return nil
}

type StartTurnRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	MovesLeft     int32                  `protobuf:"varint,4,opt,name=moves_left,json=movesLeft,proto3" json:"moves_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTurnRes) Reset() {
	*x = StartTurnRes{}
	mi := &file_monopoly_deal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTurnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTurnRes) ProtoMessage() {}

func (x *StartTurnRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTurnRes.ProtoReflect.Descriptor instead.
func (*StartTurnRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{15}
}

func (x *StartTurnRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *StartTurnRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StartTurnRes) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *StartTurnRes) GetMovesLeft() int32 {
	if x != nil {
		return x.MovesLeft
	}
	return 0
}

type StartTurnMaskedRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NumCards      int32                  `protobuf:"varint,3,opt,name=num_cards,json=numCards,proto3" json:"num_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTurnMaskedRes) Reset() {
	*x = StartTurnMaskedRes{}
	mi := &file_monopoly_deal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTurnMaskedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTurnMaskedRes) ProtoMessage() {}

func (x *StartTurnMaskedRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTurnMaskedRes.ProtoReflect.Descriptor instead.
func (*StartTurnMaskedRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{16}
}

func (x *StartTurnMaskedRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *StartTurnMaskedRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StartTurnMaskedRes) GetNumCards() int32 {
	if x != nil {
		return x.NumCards
	}
	return 0
}

type PlayMoney struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoney) Reset() {
	*x = PlayMoney{}
	mi := &file_monopoly_deal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoney) ProtoMessage() {}

func (x *PlayMoney) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoney.ProtoReflect.Descriptor instead.
func (*PlayMoney) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{17}
}

func (x *PlayMoney) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type PlayMoneyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoneyRes) Reset() {
	*x = PlayMoneyRes{}
	mi := &file_monopoly_deal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoneyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoneyRes) ProtoMessage() {}

func (x *PlayMoneyRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoneyRes.ProtoReflect.Descriptor instead.
func (*PlayMoneyRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{18}
}

func (x *PlayMoneyRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayMoneyRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayMoneyRes) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type PlayProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	PropertySetId *string                `protobuf:"bytes,2,opt,name=property_set_id,json=propertySetId,proto3,oneof" json:"property_set_id,omitempty"`
	ActiveColor   *Color                 `protobuf:"varint,3,opt,name=active_color,json=activeColor,proto3,enum=fun_kames.schema.monopoly_deal.Color,oneof" json:"active_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayProperty) Reset() {
	*x = PlayProperty{}
	mi := &file_monopoly_deal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayProperty) ProtoMessage() {}

func (x *PlayProperty) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayProperty.ProtoReflect.Descriptor instead.
func (*PlayProperty) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{19}
}

func (x *PlayProperty) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PlayProperty) GetPropertySetId() string {
	if x != nil && x.PropertySetId != nil {
		return *x.PropertySetId
	}
	return ""
}

func (x *PlayProperty) GetActiveColor() Color {
	if x != nil && x.ActiveColor != nil {
		return *x.ActiveColor
	}
	return Color_COLOR_UNSPECIFIED
}

type PlayPropertyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySet           `protobuf:"bytes,3,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPropertyRes) Reset() {
	*x = PlayPropertyRes{}
	mi := &file_monopoly_deal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPropertyRes) ProtoMessage() {}

func (x *PlayPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPropertyRes.ProtoReflect.Descriptor instead.
func (*PlayPropertyRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{20}
}

func (x *PlayPropertyRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayPropertyRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayPropertyRes) GetPropertySet() *PropertySet {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type CompleteTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTurn) Reset() {
	*x = CompleteTurn{}
	mi := &file_monopoly_deal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTurn) ProtoMessage() {}

func (x *CompleteTurn) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTurn.ProtoReflect.Descriptor instead.
func (*CompleteTurn) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{21}
}

type PlayPassGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPassGo) Reset() {
	*x = PlayPassGo{}
	mi := &file_monopoly_deal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPassGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPassGo) ProtoMessage() {}

func (x *PlayPassGo) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPassGo.ProtoReflect.Descriptor instead.
func (*PlayPassGo) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{22}
}

func (x *PlayPassGo) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type PlayPassGoRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SeqNum         int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards          []*Card                `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	LastPlayedCard *Card                  `protobuf:"bytes,4,opt,name=last_played_card,json=lastPlayedCard,proto3" json:"last_played_card,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayPassGoRes) Reset() {
	*x = PlayPassGoRes{}
	mi := &file_monopoly_deal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPassGoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPassGoRes) ProtoMessage() {}

func (x *PlayPassGoRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPassGoRes.ProtoReflect.Descriptor instead.
func (*PlayPassGoRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{23}
}

func (x *PlayPassGoRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayPassGoRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayPassGoRes) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *PlayPassGoRes) GetLastPlayedCard() *Card {
	if x != nil {
		return x.LastPlayedCard
	}
	return nil
}

type PlayPassGoMaskedRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SeqNum         int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NumCards       int32                  `protobuf:"varint,3,opt,name=num_cards,json=numCards,proto3" json:"num_cards,omitempty"`
	LastPlayedCard *Card                  `protobuf:"bytes,4,opt,name=last_played_card,json=lastPlayedCard,proto3" json:"last_played_card,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayPassGoMaskedRes) Reset() {
	*x = PlayPassGoMaskedRes{}
	mi := &file_monopoly_deal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPassGoMaskedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPassGoMaskedRes) ProtoMessage() {}

func (x *PlayPassGoMaskedRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPassGoMaskedRes.ProtoReflect.Descriptor instead.
func (*PlayPassGoMaskedRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{24}
}

func (x *PlayPassGoMaskedRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayPassGoMaskedRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayPassGoMaskedRes) GetNumCards() int32 {
	if x != nil {
		return x.NumCards
	}
	return 0
}

func (x *PlayPassGoMaskedRes) GetLastPlayedCard() *Card {
	if x != nil {
		return x.LastPlayedCard
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Chat
	//	*ClientMessage_PlayMoney
	//	*ClientMessage_PlayProperty
	//	*ClientMessage_CompleteTurn
	//	*ClientMessage_PlayPassGo
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{25}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayMoney() *PlayMoney {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayMoney); ok {
			return x.PlayMoney
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayProperty() *PlayProperty {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayProperty); ok {
			return x.PlayProperty
		}
	}
	return nil
}

func (x *ClientMessage) GetCompleteTurn() *CompleteTurn {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CompleteTurn); ok {
			return x.CompleteTurn
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayPassGo() *PlayPassGo {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayPassGo); ok {
			return x.PlayPassGo
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Chat struct {
	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

type ClientMessage_PlayMoney struct {
	PlayMoney *PlayMoney `protobuf:"bytes,2,opt,name=play_money,json=playMoney,proto3,oneof"`
}

type ClientMessage_PlayProperty struct {
	PlayProperty *PlayProperty `protobuf:"bytes,3,opt,name=play_property,json=playProperty,proto3,oneof"`
}

type ClientMessage_CompleteTurn struct {
	CompleteTurn *CompleteTurn `protobuf:"bytes,4,opt,name=complete_turn,json=completeTurn,proto3,oneof"`
}

type ClientMessage_PlayPassGo struct {
	PlayPassGo *PlayPassGo `protobuf:"bytes,5,opt,name=play_pass_go,json=playPassGo,proto3,oneof"`
}

func (*ClientMessage_Chat) isClientMessage_Payload() {}

func (*ClientMessage_PlayMoney) isClientMessage_Payload() {}

func (*ClientMessage_PlayProperty) isClientMessage_Payload() {}

func (*ClientMessage_CompleteTurn) isClientMessage_Payload() {}

func (*ClientMessage_PlayPassGo) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Error
	//	*ServerMessage_ChatReceived
	//	*ServerMessage_GameState
	//	*ServerMessage_StartTurnRes
	//	*ServerMessage_StartTurnMaskedRes
	//	*ServerMessage_PlayMoneyRes
	//	*ServerMessage_PlayPropertyRes
	//	*ServerMessage_PlayPassGoRes
	//	*ServerMessage_PlayPassGoMaskedRes
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{26}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetChatReceived() *ChatReceived {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ChatReceived); ok {
			return x.ChatReceived
		}
	}
	return nil
}

func (x *ServerMessage) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerMessage) GetStartTurnRes() *StartTurnRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StartTurnRes); ok {
			return x.StartTurnRes
		}
	}
	return nil
}

func (x *ServerMessage) GetStartTurnMaskedRes() *StartTurnMaskedRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StartTurnMaskedRes); ok {
			return x.StartTurnMaskedRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayMoneyRes() *PlayMoneyRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayMoneyRes); ok {
			return x.PlayMoneyRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayPropertyRes() *PlayPropertyRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayPropertyRes); ok {
			return x.PlayPropertyRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayPassGoRes() *PlayPassGoRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayPassGoRes); ok {
			return x.PlayPassGoRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayPassGoMaskedRes() *PlayPassGoMaskedRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayPassGoMaskedRes); ok {
			return x.PlayPassGoMaskedRes
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type ServerMessage_ChatReceived struct {
	ChatReceived *ChatReceived `protobuf:"bytes,2,opt,name=chat_received,json=chatReceived,proto3,oneof"`
}

type ServerMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,3,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerMessage_StartTurnRes struct {
	StartTurnRes *StartTurnRes `protobuf:"bytes,4,opt,name=start_turn_res,json=startTurnRes,proto3,oneof"`
}

type ServerMessage_StartTurnMaskedRes struct {
	StartTurnMaskedRes *StartTurnMaskedRes `protobuf:"bytes,5,opt,name=start_turn_masked_res,json=startTurnMaskedRes,proto3,oneof"`
}

type ServerMessage_PlayMoneyRes struct {
	PlayMoneyRes *PlayMoneyRes `protobuf:"bytes,6,opt,name=play_money_res,json=playMoneyRes,proto3,oneof"`
}

type ServerMessage_PlayPropertyRes struct {
	PlayPropertyRes *PlayPropertyRes `protobuf:"bytes,7,opt,name=play_property_res,json=playPropertyRes,proto3,oneof"`
}

type ServerMessage_PlayPassGoRes struct {
	PlayPassGoRes *PlayPassGoRes `protobuf:"bytes,8,opt,name=play_pass_go_res,json=playPassGoRes,proto3,oneof"`
}

type ServerMessage_PlayPassGoMaskedRes struct {
	PlayPassGoMaskedRes *PlayPassGoMaskedRes `protobuf:"bytes,9,opt,name=play_pass_go_masked_res,json=playPassGoMaskedRes,proto3,oneof"`
}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_ChatReceived) isServerMessage_Payload() {}

func (*ServerMessage_GameState) isServerMessage_Payload() {}

func (*ServerMessage_StartTurnRes) isServerMessage_Payload() {}

func (*ServerMessage_StartTurnMaskedRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayMoneyRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayPropertyRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayPassGoRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayPassGoMaskedRes) isServerMessage_Payload() {}

var File_monopoly_deal_proto protoreflect.FileDescriptor

const file_monopoly_deal_proto_rawDesc = "" +
	"\n" +
	"\x13monopoly_deal.proto\x12\x1efun_kames.schema.monopoly_deal\"M\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\" \n" +
	"\x04Chat\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"E\n" +
	"\fChatReceived\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\xcb\x02\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12E\n" +
	"\tasset_key\x18\x02 \x01(\x0e2(.fun_kames.schema.monopoly_deal.AssetKeyR\bassetKey\x12D\n" +
	"\bcategory\x18\x03 \x01(\x0e2(.fun_kames.schema.monopoly_deal.CategoryR\bcategory\x12H\n" +
	"\factive_color\x18\x04 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\vactiveColor\x12=\n" +
	"\x06colors\x18\x05 \x03(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\x06colors\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x05R\x05value\"\xc3\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05money\x18\x04 \x01(\x05R\x05money\x12%\n" +
	"\x0ecompleted_sets\x18\x05 \x01(\x05R\rcompletedSets\x12\x1d\n" +
	"\n" +
	"hand_cards\x18\x06 \x01(\x05R\thandCards\"B\n" +
	"\x04Hand\x12:\n" +
	"\x05cards\x18\x01 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"`\n" +
	"\x05Money\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\x05cards\x18\x02 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"\xcb\x01\n" +
	"\vPropertySet\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12&\n" +
	"\x0fproperty_set_id\x18\x02 \x01(\tR\rpropertySetId\x12;\n" +
	"\x05color\x18\x03 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\x05color\x12:\n" +
	"\x05cards\x18\x04 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"'\n" +
	"\rPaymentDemand\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"t\n" +
	"\x0ePropertyDemand\x12)\n" +
	"\x0esource_card_id\x18\x01 \x01(\tH\x00R\fsourceCardId\x88\x01\x01\x12$\n" +
	"\x0etarget_card_id\x18\x02 \x01(\tR\ftargetCardIdB\x11\n" +
	"\x0f_source_card_id\";\n" +
	"\x11PropertySetDemand\x12&\n" +
	"\x0fproperty_set_id\x18\x01 \x01(\tR\rpropertySetId\"\xb1\x03\n" +
	"\x06Demand\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12K\n" +
	"\vdemand_kind\x18\x02 \x01(\x0e2*.fun_kames.schema.monopoly_deal.DemandKindR\n" +
	"demandKind\x12V\n" +
	"\x0epayment_demand\x18\x03 \x01(\v2-.fun_kames.schema.monopoly_deal.PaymentDemandH\x00R\rpaymentDemand\x12Y\n" +
	"\x0fproperty_demand\x18\x04 \x01(\v2..fun_kames.schema.monopoly_deal.PropertyDemandH\x00R\x0epropertyDemand\x12c\n" +
	"\x13property_set_demand\x18\x05 \x01(\v21.fun_kames.schema.monopoly_deal.PropertySetDemandH\x00R\x11propertySetDemand\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActiveB\b\n" +
	"\x06demand\"\x8a\x01\n" +
	"\vPendingRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\tR\ttargetIds\x12\x1f\n" +
	"\vbase_amount\x18\x03 \x01(\x05R\n" +
	"baseAmount\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x05R\n" +
	"multiplier\"p\n" +
	"\n" +
	"AssetImage\x12E\n" +
	"\tasset_key\x18\x01 \x01(\x0e2(.fun_kames.schema.monopoly_deal.AssetKeyR\bassetKey\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"\xca\x05\n" +
	"\tGameState\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.fun_kames.schema.monopoly_deal.PlayerR\aplayers\x12*\n" +
	"\x11current_player_id\x18\x03 \x01(\tR\x0fcurrentPlayerId\x12\x1d\n" +
	"\n" +
	"moves_left\x18\x04 \x01(\x05R\tmovesLeft\x12A\n" +
	"\tyour_hand\x18\x05 \x01(\v2$.fun_kames.schema.monopoly_deal.HandR\byourHand\x12;\n" +
	"\x05money\x18\x06 \x03(\v2%.fun_kames.schema.monopoly_deal.MoneyR\x05money\x12K\n" +
	"\n" +
	"properties\x18\a \x03(\v2+.fun_kames.schema.monopoly_deal.PropertySetR\n" +
	"properties\x12C\n" +
	"\x06demand\x18\b \x01(\v2&.fun_kames.schema.monopoly_deal.DemandH\x00R\x06demand\x88\x01\x01\x12S\n" +
	"\fpending_rent\x18\t \x01(\v2+.fun_kames.schema.monopoly_deal.PendingRentH\x01R\vpendingRent\x88\x01\x01\x12E\n" +
	"\vlast_action\x18\n" +
	" \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\n" +
	"lastAction\x12M\n" +
	"\fasset_images\x18\v \x03(\v2*.fun_kames.schema.monopoly_deal.AssetImageR\vassetImagesB\t\n" +
	"\a_demandB\x0f\n" +
	"\r_pending_rent\"\x9f\x01\n" +
	"\fStartTurnRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12:\n" +
	"\x05cards\x18\x03 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\x12\x1d\n" +
	"\n" +
	"moves_left\x18\x04 \x01(\x05R\tmovesLeft\"g\n" +
	"\x12StartTurnMaskedRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tnum_cards\x18\x03 \x01(\x05R\bnumCards\"$\n" +
	"\tPlayMoney\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"~\n" +
	"\fPlayMoneyRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x128\n" +
	"\x04card\x18\x03 \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\x04card\"\xc8\x01\n" +
	"\fPlayProperty\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12+\n" +
	"\x0fproperty_set_id\x18\x02 \x01(\tH\x00R\rpropertySetId\x88\x01\x01\x12M\n" +
	"\factive_color\x18\x03 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorH\x01R\vactiveColor\x88\x01\x01B\x12\n" +
	"\x10_property_set_idB\x0f\n" +
	"\r_active_color\"\x97\x01\n" +
	"\x0fPlayPropertyRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12N\n" +
	"\fproperty_set\x18\x03 \x01(\v2+.fun_kames.schema.monopoly_deal.PropertySetR\vpropertySet\"\x0e\n" +
	"\fCompleteTurn\"%\n" +
	"\n" +
	"PlayPassGo\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\xd1\x01\n" +
	"\rPlayPassGoRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12:\n" +
	"\x05cards\x18\x03 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\x12N\n" +
	"\x10last_played_card\x18\x04 \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\x0elastPlayedCard\"\xb8\x01\n" +
	"\x13PlayPassGoMaskedRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tnum_cards\x18\x03 \x01(\x05R\bnumCards\x12N\n" +
	"\x10last_played_card\x18\x04 \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\x0elastPlayedCard\"\x9c\x03\n" +
	"\rClientMessage\x12:\n" +
	"\x04chat\x18\x01 \x01(\v2$.fun_kames.schema.monopoly_deal.ChatH\x00R\x04chat\x12J\n" +
	"\n" +
	"play_money\x18\x02 \x01(\v2).fun_kames.schema.monopoly_deal.PlayMoneyH\x00R\tplayMoney\x12S\n" +
	"\rplay_property\x18\x03 \x01(\v2,.fun_kames.schema.monopoly_deal.PlayPropertyH\x00R\fplayProperty\x12S\n" +
	"\rcomplete_turn\x18\x04 \x01(\v2,.fun_kames.schema.monopoly_deal.CompleteTurnH\x00R\fcompleteTurn\x12N\n" +
	"\fplay_pass_go\x18\x05 \x01(\v2*.fun_kames.schema.monopoly_deal.PlayPassGoH\x00R\n" +
	"playPassGoB\t\n" +
	"\apayload\"\xb5\x06\n" +
	"\rServerMessage\x12=\n" +
	"\x05error\x18\x01 \x01(\v2%.fun_kames.schema.monopoly_deal.ErrorH\x00R\x05error\x12S\n" +
	"\rchat_received\x18\x02 \x01(\v2,.fun_kames.schema.monopoly_deal.ChatReceivedH\x00R\fchatReceived\x12J\n" +
	"\n" +
	"game_state\x18\x03 \x01(\v2).fun_kames.schema.monopoly_deal.GameStateH\x00R\tgameState\x12T\n" +
	"\x0estart_turn_res\x18\x04 \x01(\v2,.fun_kames.schema.monopoly_deal.StartTurnResH\x00R\fstartTurnRes\x12g\n" +
	"\x15start_turn_masked_res\x18\x05 \x01(\v22.fun_kames.schema.monopoly_deal.StartTurnMaskedResH\x00R\x12startTurnMaskedRes\x12T\n" +
	"\x0eplay_money_res\x18\x06 \x01(\v2,.fun_kames.schema.monopoly_deal.PlayMoneyResH\x00R\fplayMoneyRes\x12]\n" +
	"\x11play_property_res\x18\a \x01(\v2/.fun_kames.schema.monopoly_deal.PlayPropertyResH\x00R\x0fplayPropertyRes\x12X\n" +
	"\x10play_pass_go_res\x18\b \x01(\v2-.fun_kames.schema.monopoly_deal.PlayPassGoResH\x00R\rplayPassGoRes\x12k\n" +
	"\x17play_pass_go_masked_res\x18\t \x01(\v23.fun_kames.schema.monopoly_deal.PlayPassGoMaskedResH\x00R\x13playPassGoMaskedResB\t\n" +
	"\apayload*\x9f\r\n" +
	"\bAssetKey\x12\x19\n" +
	"\x15ASSET_KEY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ASSET_KEY_BALTIC_AVE\x10\x01\x12\x1f\n" +
	"\x1bASSET_KEY_MEDITERRANEAN_AVE\x10\x02\x12\x1d\n" +
	"\x19ASSET_KEY_CONNECTICUT_AVE\x10\x03\x12\x1a\n" +
	"\x16ASSET_KEY_ORIENTAL_AVE\x10\x04\x12\x19\n" +
	"\x15ASSET_KEY_VERMONT_AVE\x10\x05\x12\x1e\n" +
	"\x1aASSET_KEY_ST_CHARLES_PLACE\x10\x06\x12\x1a\n" +
	"\x16ASSET_KEY_VIRGINIA_AVE\x10\a\x12\x18\n" +
	"\x14ASSET_KEY_STATES_AVE\x10\b\x12\x1a\n" +
	"\x16ASSET_KEY_NEW_YORK_AVE\x10\t\x12\x1c\n" +
	"\x18ASSET_KEY_ST_JAMES_PLACE\x10\n" +
	"\x12\x1b\n" +
	"\x17ASSET_KEY_TENNESSEE_AVE\x10\v\x12\x1a\n" +
	"\x16ASSET_KEY_KENTUCKY_AVE\x10\f\x12\x19\n" +
	"\x15ASSET_KEY_INDIANA_AVE\x10\r\x12\x1a\n" +
	"\x16ASSET_KEY_ILLINOIS_AVE\x10\x0e\x12\x19\n" +
	"\x15ASSET_KEY_VENTNOR_AVE\x10\x0f\x12\x1c\n" +
	"\x18ASSET_KEY_MARVIN_GARDENS\x10\x10\x12\x1a\n" +
	"\x16ASSET_KEY_ATLANTIC_AVE\x10\x11\x12 \n" +
	"\x1cASSET_KEY_NORTH_CAROLINA_AVE\x10\x12\x12\x19\n" +
	"\x15ASSET_KEY_PACIFIC_AVE\x10\x13\x12\x1e\n" +
	"\x1aASSET_KEY_PENNSYLVANIA_AVE\x10\x14\x12\x17\n" +
	"\x13ASSET_KEY_BOARDWALK\x10\x15\x12\x18\n" +
	"\x14ASSET_KEY_PARK_PLACE\x10\x16\x12\x19\n" +
	"\x15ASSET_KEY_WATER_WORKS\x10\x17\x12\x1e\n" +
	"\x1aASSET_KEY_ELECTRIC_COMPANY\x10\x18\x12\x18\n" +
	"\x14ASSET_KEY_SHORT_LINE\x10\x19\x12\x1e\n" +
	"\x1aASSET_KEY_B_AND_O_RAILROAD\x10\x1a\x12\x1e\n" +
	"\x1aASSET_KEY_READING_RAILROAD\x10\x1b\x12#\n" +
	"\x1fASSET_KEY_PENNSYLVANIA_RAILROAD\x10\x1c\x12\x1c\n" +
	"\x18ASSET_KEY_WILD_BROWN_SKY\x10\x1d\x12\x1f\n" +
	"\x1bASSET_KEY_WILD_SKY_RAILROAD\x10\x1e\x12\x1e\n" +
	"\x1aASSET_KEY_WILD_PINK_ORANGE\x10\x1f\x12\x1d\n" +
	"\x19ASSET_KEY_WILD_RED_YELLOW\x10 \x12\x1d\n" +
	"\x19ASSET_KEY_WILD_GREEN_BLUE\x10!\x12!\n" +
	"\x1dASSET_KEY_WILD_GREEN_RAILROAD\x10\"\x12#\n" +
	"\x1fASSET_KEY_WILD_UTILITY_RAILROAD\x10#\x12\x17\n" +
	"\x13ASSET_KEY_WILD_WILD\x10$\x12\x16\n" +
	"\x12ASSET_KEY_MONEY_10\x10%\x12\x15\n" +
	"\x11ASSET_KEY_MONEY_5\x10&\x12\x15\n" +
	"\x11ASSET_KEY_MONEY_4\x10'\x12\x15\n" +
	"\x11ASSET_KEY_MONEY_3\x10(\x12\x15\n" +
	"\x11ASSET_KEY_MONEY_2\x10)\x12\x15\n" +
	"\x11ASSET_KEY_MONEY_1\x10*\x12\x1a\n" +
	"\x16ASSET_KEY_DEAL_BREAKER\x10+\x12\x19\n" +
	"\x15ASSET_KEY_JUST_SAY_NO\x10,\x12\x13\n" +
	"\x0fASSET_KEY_HOTEL\x10-\x12\x1c\n" +
	"\x18ASSET_KEY_DEBT_COLLECTOR\x10.\x12\x19\n" +
	"\x15ASSET_KEY_FORCED_DEAL\x10/\x12\x16\n" +
	"\x12ASSET_KEY_SLY_DEAL\x100\x12\x13\n" +
	"\x0fASSET_KEY_HOUSE\x101\x12\x1d\n" +
	"\x19ASSET_KEY_ITS_MY_BIRTHDAY\x102\x12\x1d\n" +
	"\x19ASSET_KEY_DOUBLE_THE_RENT\x103\x12\x15\n" +
	"\x11ASSET_KEY_PASS_GO\x104\x12\x17\n" +
	"\x13ASSET_KEY_RENT_WILD\x105\x12\x1c\n" +
	"\x18ASSET_KEY_RENT_BROWN_SKY\x106\x12\x1e\n" +
	"\x1aASSET_KEY_RENT_PINK_ORANGE\x107\x12\x1d\n" +
	"\x19ASSET_KEY_RENT_RED_YELLOW\x108\x12\x1d\n" +
	"\x19ASSET_KEY_RENT_GREEN_BLUE\x109\x12#\n" +
	"\x1fASSET_KEY_RENT_UTILITY_RAILROAD\x10:*\x85\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CATEGORY_PURE_PROPERTY\x10\x01\x12\x1a\n" +
	"\x16CATEGORY_WILD_PROPERTY\x10\x02\x12\x12\n" +
	"\x0eCATEGORY_MONEY\x10\x03\x12\x13\n" +
	"\x0fCATEGORY_ACTION\x10\x04*\xc9\x01\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCOLOR_BROWN\x10\x01\x12\r\n" +
	"\tCOLOR_SKY\x10\x02\x12\x0e\n" +
	"\n" +
	"COLOR_PINK\x10\x03\x12\x10\n" +
	"\fCOLOR_ORANGE\x10\x04\x12\r\n" +
	"\tCOLOR_RED\x10\x05\x12\x10\n" +
	"\fCOLOR_YELLOW\x10\x06\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\a\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\b\x12\x11\n" +
	"\rCOLOR_UTILITY\x10\t\x12\x12\n" +
	"\x0eCOLOR_RAILROAD\x10\n" +
	"*z\n" +
	"\n" +
	"DemandKind\x12\x1b\n" +
	"\x17DEMAND_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEMAND_KIND_PAYMENT\x10\x01\x12\x18\n" +
	"\x14DEMAND_KIND_PROPERTY\x10\x02\x12\x1c\n" +
	"\x18DEMAND_KIND_PROPERTY_SET\x10\x03BEZCfun-kames/internal/schema/monopoly_deal_schema;monopoly_deal_schemab\x06proto3"

var (
	file_monopoly_deal_proto_rawDescOnce sync.Once
	file_monopoly_deal_proto_rawDescData []byte
)

func file_monopoly_deal_proto_rawDescGZIP() []byte {
	file_monopoly_deal_proto_rawDescOnce.Do(func() {
		file_monopoly_deal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)))
	})
	return file_monopoly_deal_proto_rawDescData
}

var file_monopoly_deal_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_monopoly_deal_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_monopoly_deal_proto_goTypes = []any{
	(AssetKey)(0),               // 0: fun_kames.schema.monopoly_deal.AssetKey
	(Category)(0),               // 1: fun_kames.schema.monopoly_deal.Category
	(Color)(0),                  // 2: fun_kames.schema.monopoly_deal.Color
	(DemandKind)(0),             // 3: fun_kames.schema.monopoly_deal.DemandKind
	(*Error)(nil),               // 4: fun_kames.schema.monopoly_deal.Error
	(*Chat)(nil),                // 5: fun_kames.schema.monopoly_deal.Chat
	(*ChatReceived)(nil),        // 6: fun_kames.schema.monopoly_deal.ChatReceived
	(*Card)(nil),                // 7: fun_kames.schema.monopoly_deal.Card
	(*Player)(nil),              // 8: fun_kames.schema.monopoly_deal.Player
	(*Hand)(nil),                // 9: fun_kames.schema.monopoly_deal.Hand
	(*Money)(nil),               // 10: fun_kames.schema.monopoly_deal.Money
	(*PropertySet)(nil),         // 11: fun_kames.schema.monopoly_deal.PropertySet
	(*PaymentDemand)(nil),       // 12: fun_kames.schema.monopoly_deal.PaymentDemand
	(*PropertyDemand)(nil),      // 13: fun_kames.schema.monopoly_deal.PropertyDemand
	(*PropertySetDemand)(nil),   // 14: fun_kames.schema.monopoly_deal.PropertySetDemand
	(*Demand)(nil),              // 15: fun_kames.schema.monopoly_deal.Demand
	(*PendingRent)(nil),         // 16: fun_kames.schema.monopoly_deal.PendingRent
	(*AssetImage)(nil),          // 17: fun_kames.schema.monopoly_deal.AssetImage
	(*GameState)(nil),           // 18: fun_kames.schema.monopoly_deal.GameState
	(*StartTurnRes)(nil),        // 19: fun_kames.schema.monopoly_deal.StartTurnRes
	(*StartTurnMaskedRes)(nil),  // 20: fun_kames.schema.monopoly_deal.StartTurnMaskedRes
	(*PlayMoney)(nil),           // 21: fun_kames.schema.monopoly_deal.PlayMoney
	(*PlayMoneyRes)(nil),        // 22: fun_kames.schema.monopoly_deal.PlayMoneyRes
	(*PlayProperty)(nil),        // 23: fun_kames.schema.monopoly_deal.PlayProperty
	(*PlayPropertyRes)(nil),     // 24: fun_kames.schema.monopoly_deal.PlayPropertyRes
	(*CompleteTurn)(nil),        // 25: fun_kames.schema.monopoly_deal.CompleteTurn
	(*PlayPassGo)(nil),          // 26: fun_kames.schema.monopoly_deal.PlayPassGo
	(*PlayPassGoRes)(nil),       // 27: fun_kames.schema.monopoly_deal.PlayPassGoRes
	(*PlayPassGoMaskedRes)(nil), // 28: fun_kames.schema.monopoly_deal.PlayPassGoMaskedRes
	(*ClientMessage)(nil),       // 29: fun_kames.schema.monopoly_deal.ClientMessage
	(*ServerMessage)(nil),       // 30: fun_kames.schema.monopoly_deal.ServerMessage
}
var file_monopoly_deal_proto_depIdxs = []int32{
	0,  // 0: fun_kames.schema.monopoly_deal.Card.asset_key:type_name -> fun_kames.schema.monopoly_deal.AssetKey
	1,  // 1: fun_kames.schema.monopoly_deal.Card.category:type_name -> fun_kames.schema.monopoly_deal.Category
	2,  // 2: fun_kames.schema.monopoly_deal.Card.active_color:type_name -> fun_kames.schema.monopoly_deal.Color
	2,  // 3: fun_kames.schema.monopoly_deal.Card.colors:type_name -> fun_kames.schema.monopoly_deal.Color
	7,  // 4: fun_kames.schema.monopoly_deal.Hand.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	7,  // 5: fun_kames.schema.monopoly_deal.Money.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	2,  // 6: fun_kames.schema.monopoly_deal.PropertySet.color:type_name -> fun_kames.schema.monopoly_deal.Color
	7,  // 7: fun_kames.schema.monopoly_deal.PropertySet.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	3,  // 8: fun_kames.schema.monopoly_deal.Demand.demand_kind:type_name -> fun_kames.schema.monopoly_deal.DemandKind
	12, // 9: fun_kames.schema.monopoly_deal.Demand.payment_demand:type_name -> fun_kames.schema.monopoly_deal.PaymentDemand
	13, // 10: fun_kames.schema.monopoly_deal.Demand.property_demand:type_name -> fun_kames.schema.monopoly_deal.PropertyDemand
	14, // 11: fun_kames.schema.monopoly_deal.Demand.property_set_demand:type_name -> fun_kames.schema.monopoly_deal.PropertySetDemand
	0,  // 12: fun_kames.schema.monopoly_deal.AssetImage.asset_key:type_name -> fun_kames.schema.monopoly_deal.AssetKey
	8,  // 13: fun_kames.schema.monopoly_deal.GameState.players:type_name -> fun_kames.schema.monopoly_deal.Player
	9,  // 14: fun_kames.schema.monopoly_deal.GameState.your_hand:type_name -> fun_kames.schema.monopoly_deal.Hand
	10, // 15: fun_kames.schema.monopoly_deal.GameState.money:type_name -> fun_kames.schema.monopoly_deal.Money
	11, // 16: fun_kames.schema.monopoly_deal.GameState.properties:type_name -> fun_kames.schema.monopoly_deal.PropertySet
	15, // 17: fun_kames.schema.monopoly_deal.GameState.demand:type_name -> fun_kames.schema.monopoly_deal.Demand
	16, // 18: fun_kames.schema.monopoly_deal.GameState.pending_rent:type_name -> fun_kames.schema.monopoly_deal.PendingRent
	7,  // 19: fun_kames.schema.monopoly_deal.GameState.last_action:type_name -> fun_kames.schema.monopoly_deal.Card
	17, // 20: fun_kames.schema.monopoly_deal.GameState.asset_images:type_name -> fun_kames.schema.monopoly_deal.AssetImage
	7,  // 21: fun_kames.schema.monopoly_deal.StartTurnRes.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	7,  // 22: fun_kames.schema.monopoly_deal.PlayMoneyRes.card:type_name -> fun_kames.schema.monopoly_deal.Card
	2,  // 23: fun_kames.schema.monopoly_deal.PlayProperty.active_color:type_name -> fun_kames.schema.monopoly_deal.Color
	11, // 24: fun_kames.schema.monopoly_deal.PlayPropertyRes.property_set:type_name -> fun_kames.schema.monopoly_deal.PropertySet
	7,  // 25: fun_kames.schema.monopoly_deal.PlayPassGoRes.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	7,  // 26: fun_kames.schema.monopoly_deal.PlayPassGoRes.last_played_card:type_name -> fun_kames.schema.monopoly_deal.Card
	7,  // 27: fun_kames.schema.monopoly_deal.PlayPassGoMaskedRes.last_played_card:type_name -> fun_kames.schema.monopoly_deal.Card
	5,  // 28: fun_kames.schema.monopoly_deal.ClientMessage.chat:type_name -> fun_kames.schema.monopoly_deal.Chat
	21, // 29: fun_kames.schema.monopoly_deal.ClientMessage.play_money:type_name -> fun_kames.schema.monopoly_deal.PlayMoney
	23, // 30: fun_kames.schema.monopoly_deal.ClientMessage.play_property:type_name -> fun_kames.schema.monopoly_deal.PlayProperty
	25, // 31: fun_kames.schema.monopoly_deal.ClientMessage.complete_turn:type_name -> fun_kames.schema.monopoly_deal.CompleteTurn
	26, // 32: fun_kames.schema.monopoly_deal.ClientMessage.play_pass_go:type_name -> fun_kames.schema.monopoly_deal.PlayPassGo
	4,  // 33: fun_kames.schema.monopoly_deal.ServerMessage.error:type_name -> fun_kames.schema.monopoly_deal.Error
	6,  // 34: fun_kames.schema.monopoly_deal.ServerMessage.chat_received:type_name -> fun_kames.schema.monopoly_deal.ChatReceived
	18, // 35: fun_kames.schema.monopoly_deal.ServerMessage.game_state:type_name -> fun_kames.schema.monopoly_deal.GameState
	19, // 36: fun_kames.schema.monopoly_deal.ServerMessage.start_turn_res:type_name -> fun_kames.schema.monopoly_deal.StartTurnRes
	20, // 37: fun_kames.schema.monopoly_deal.ServerMessage.start_turn_masked_res:type_name -> fun_kames.schema.monopoly_deal.StartTurnMaskedRes
	22, // 38: fun_kames.schema.monopoly_deal.ServerMessage.play_money_res:type_name -> fun_kames.schema.monopoly_deal.PlayMoneyRes
	24, // 39: fun_kames.schema.monopoly_deal.ServerMessage.play_property_res:type_name -> fun_kames.schema.monopoly_deal.PlayPropertyRes
	27, // 40: fun_kames.schema.monopoly_deal.ServerMessage.play_pass_go_res:type_name -> fun_kames.schema.monopoly_deal.PlayPassGoRes
	28, // 41: fun_kames.schema.monopoly_deal.ServerMessage.play_pass_go_masked_res:type_name -> fun_kames.schema.monopoly_deal.PlayPassGoMaskedRes
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_monopoly_deal_proto_init() }
func file_monopoly_deal_proto_init() {
	if File_monopoly_deal_proto != nil {
		return
	}
	file_monopoly_deal_proto_msgTypes[9].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[11].OneofWrappers = []any{
		(*Demand_PaymentDemand)(nil),
		(*Demand_PropertyDemand)(nil),
		(*Demand_PropertySetDemand)(nil),
	}
	file_monopoly_deal_proto_msgTypes[14].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[19].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[25].OneofWrappers = []any{
		(*ClientMessage_Chat)(nil),
		(*ClientMessage_PlayMoney)(nil),
		(*ClientMessage_PlayProperty)(nil),
		(*ClientMessage_CompleteTurn)(nil),
		(*ClientMessage_PlayPassGo)(nil),
	}
	file_monopoly_deal_proto_msgTypes[26].OneofWrappers = []any{
		(*ServerMessage_Error)(nil),
		(*ServerMessage_ChatReceived)(nil),
		(*ServerMessage_GameState)(nil),
		(*ServerMessage_StartTurnRes)(nil),
		(*ServerMessage_StartTurnMaskedRes)(nil),
		(*ServerMessage_PlayMoneyRes)(nil),
		(*ServerMessage_PlayPropertyRes)(nil),
		(*ServerMessage_PlayPassGoRes)(nil),
		(*ServerMessage_PlayPassGoMaskedRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monopoly_deal_proto_goTypes,
		DependencyIndexes: file_monopoly_deal_proto_depIdxs,
		EnumInfos:         file_monopoly_deal_proto_enumTypes,
		MessageInfos:      file_monopoly_deal_proto_msgTypes,
	}.Build()
	File_monopoly_deal_proto = out.File
	file_monopoly_deal_proto_goTypes = nil
	file_monopoly_deal_proto_depIdxs = nil
}
