// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: monopoly_deal.proto

package monopoly_deal_schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetKey int32

const (
	AssetKey_BALTIC_AVE            AssetKey = 0
	AssetKey_MEDITERRANEAN_AVE     AssetKey = 1
	AssetKey_CONNECTICUT_AVE       AssetKey = 2
	AssetKey_ORIENTAL_AVE          AssetKey = 3
	AssetKey_VERMONT_AVE           AssetKey = 4
	AssetKey_ST_CHARLES_PLACE      AssetKey = 5
	AssetKey_VIRGINIA_AVE          AssetKey = 6
	AssetKey_STATE_AVE             AssetKey = 7
	AssetKey_NEW_YORK_AVE          AssetKey = 8
	AssetKey_ST_JAMES_PLACE        AssetKey = 9
	AssetKey_TENNESSEE_AVE         AssetKey = 10
	AssetKey_KENTUCKY_AVE          AssetKey = 11
	AssetKey_INDIANA_AVE           AssetKey = 12
	AssetKey_ILLINOIS_AVE          AssetKey = 13
	AssetKey_VENTNOR_AVE           AssetKey = 14
	AssetKey_MARVIN_GARDENS        AssetKey = 15
	AssetKey_ATLANTIC_AVE          AssetKey = 16
	AssetKey_NORTH_CAROLINA_AVE    AssetKey = 17
	AssetKey_PACIFIC_AVE           AssetKey = 18
	AssetKey_PENNSYLVANIA_AVE      AssetKey = 19
	AssetKey_BOARDWALK             AssetKey = 20
	AssetKey_PARK_PLACE            AssetKey = 21
	AssetKey_WATER_WORKS           AssetKey = 22
	AssetKey_ELECTRIC_COMPANY      AssetKey = 23
	AssetKey_SHORT_LINE            AssetKey = 24
	AssetKey_B_AND_O_RAILROAD      AssetKey = 25
	AssetKey_READING_RAILROAD      AssetKey = 26
	AssetKey_PENNSYLVANIA_RAILROAD AssetKey = 27
	AssetKey_WILD_BROWN_SKY        AssetKey = 28
	AssetKey_WILD_SKY_RAILROAD     AssetKey = 29
	AssetKey_WILD_PINK_ORANGE      AssetKey = 30
	AssetKey_WILD_RED_YELLOW       AssetKey = 31
	AssetKey_WILD_GREEN_BLUE       AssetKey = 32
	AssetKey_WILD_GREEN_RAILROAD   AssetKey = 33
	AssetKey_WILD_UTILITY_RAILROAD AssetKey = 34
	AssetKey_WILD_WILD             AssetKey = 35
	AssetKey_MONEY_10              AssetKey = 36
	AssetKey_MONEY_5               AssetKey = 37
	AssetKey_MONEY_4               AssetKey = 38
	AssetKey_MONEY_3               AssetKey = 39
	AssetKey_MONEY_2               AssetKey = 40
	AssetKey_MONEY_1               AssetKey = 41
	AssetKey_DEAL_BREAKER          AssetKey = 42
	AssetKey_JUST_SAY_NO           AssetKey = 43
	AssetKey_HOTEL                 AssetKey = 44
	AssetKey_DEBT_COLLECTOR        AssetKey = 45
	AssetKey_FORCED_DEAL           AssetKey = 46
	AssetKey_SLY_DEAL              AssetKey = 47
	AssetKey_HOUSE                 AssetKey = 48
	AssetKey_ITS_MY_BIRTHDAY       AssetKey = 49
	AssetKey_DOUBLE_THE_RENT       AssetKey = 50
	AssetKey_PASS_GO               AssetKey = 51
	AssetKey_RENT_WILD             AssetKey = 52
	AssetKey_RENT_BROWN_SKY        AssetKey = 53
	AssetKey_RENT_PINK_ORANGE      AssetKey = 54
	AssetKey_RENT_RED_YELLOW       AssetKey = 55
	AssetKey_RENT_GREEN_BLUE       AssetKey = 56
	AssetKey_RENT_UTILITY_RAILROAD AssetKey = 57
)

// Enum value maps for AssetKey.
var (
	AssetKey_name = map[int32]string{
		0:  "BALTIC_AVE",
		1:  "MEDITERRANEAN_AVE",
		2:  "CONNECTICUT_AVE",
		3:  "ORIENTAL_AVE",
		4:  "VERMONT_AVE",
		5:  "ST_CHARLES_PLACE",
		6:  "VIRGINIA_AVE",
		7:  "STATE_AVE",
		8:  "NEW_YORK_AVE",
		9:  "ST_JAMES_PLACE",
		10: "TENNESSEE_AVE",
		11: "KENTUCKY_AVE",
		12: "INDIANA_AVE",
		13: "ILLINOIS_AVE",
		14: "VENTNOR_AVE",
		15: "MARVIN_GARDENS",
		16: "ATLANTIC_AVE",
		17: "NORTH_CAROLINA_AVE",
		18: "PACIFIC_AVE",
		19: "PENNSYLVANIA_AVE",
		20: "BOARDWALK",
		21: "PARK_PLACE",
		22: "WATER_WORKS",
		23: "ELECTRIC_COMPANY",
		24: "SHORT_LINE",
		25: "B_AND_O_RAILROAD",
		26: "READING_RAILROAD",
		27: "PENNSYLVANIA_RAILROAD",
		28: "WILD_BROWN_SKY",
		29: "WILD_SKY_RAILROAD",
		30: "WILD_PINK_ORANGE",
		31: "WILD_RED_YELLOW",
		32: "WILD_GREEN_BLUE",
		33: "WILD_GREEN_RAILROAD",
		34: "WILD_UTILITY_RAILROAD",
		35: "WILD_WILD",
		36: "MONEY_10",
		37: "MONEY_5",
		38: "MONEY_4",
		39: "MONEY_3",
		40: "MONEY_2",
		41: "MONEY_1",
		42: "DEAL_BREAKER",
		43: "JUST_SAY_NO",
		44: "HOTEL",
		45: "DEBT_COLLECTOR",
		46: "FORCED_DEAL",
		47: "SLY_DEAL",
		48: "HOUSE",
		49: "ITS_MY_BIRTHDAY",
		50: "DOUBLE_THE_RENT",
		51: "PASS_GO",
		52: "RENT_WILD",
		53: "RENT_BROWN_SKY",
		54: "RENT_PINK_ORANGE",
		55: "RENT_RED_YELLOW",
		56: "RENT_GREEN_BLUE",
		57: "RENT_UTILITY_RAILROAD",
	}
	AssetKey_value = map[string]int32{
		"BALTIC_AVE":            0,
		"MEDITERRANEAN_AVE":     1,
		"CONNECTICUT_AVE":       2,
		"ORIENTAL_AVE":          3,
		"VERMONT_AVE":           4,
		"ST_CHARLES_PLACE":      5,
		"VIRGINIA_AVE":          6,
		"STATE_AVE":             7,
		"NEW_YORK_AVE":          8,
		"ST_JAMES_PLACE":        9,
		"TENNESSEE_AVE":         10,
		"KENTUCKY_AVE":          11,
		"INDIANA_AVE":           12,
		"ILLINOIS_AVE":          13,
		"VENTNOR_AVE":           14,
		"MARVIN_GARDENS":        15,
		"ATLANTIC_AVE":          16,
		"NORTH_CAROLINA_AVE":    17,
		"PACIFIC_AVE":           18,
		"PENNSYLVANIA_AVE":      19,
		"BOARDWALK":             20,
		"PARK_PLACE":            21,
		"WATER_WORKS":           22,
		"ELECTRIC_COMPANY":      23,
		"SHORT_LINE":            24,
		"B_AND_O_RAILROAD":      25,
		"READING_RAILROAD":      26,
		"PENNSYLVANIA_RAILROAD": 27,
		"WILD_BROWN_SKY":        28,
		"WILD_SKY_RAILROAD":     29,
		"WILD_PINK_ORANGE":      30,
		"WILD_RED_YELLOW":       31,
		"WILD_GREEN_BLUE":       32,
		"WILD_GREEN_RAILROAD":   33,
		"WILD_UTILITY_RAILROAD": 34,
		"WILD_WILD":             35,
		"MONEY_10":              36,
		"MONEY_5":               37,
		"MONEY_4":               38,
		"MONEY_3":               39,
		"MONEY_2":               40,
		"MONEY_1":               41,
		"DEAL_BREAKER":          42,
		"JUST_SAY_NO":           43,
		"HOTEL":                 44,
		"DEBT_COLLECTOR":        45,
		"FORCED_DEAL":           46,
		"SLY_DEAL":              47,
		"HOUSE":                 48,
		"ITS_MY_BIRTHDAY":       49,
		"DOUBLE_THE_RENT":       50,
		"PASS_GO":               51,
		"RENT_WILD":             52,
		"RENT_BROWN_SKY":        53,
		"RENT_PINK_ORANGE":      54,
		"RENT_RED_YELLOW":       55,
		"RENT_GREEN_BLUE":       56,
		"RENT_UTILITY_RAILROAD": 57,
	}
)

func (x AssetKey) Enum() *AssetKey {
	p := new(AssetKey)
	*p = x
	return p
}

func (x AssetKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKey) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[0].Descriptor()
}

func (AssetKey) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[0]
}

func (x AssetKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKey.Descriptor instead.
func (AssetKey) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_PURE_PROPERTY Category = 0
	Category_WILD_PROPERTY Category = 1
	Category_MONEY         Category = 2
	Category_ACTION        Category = 3
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "PURE_PROPERTY",
		1: "WILD_PROPERTY",
		2: "MONEY",
		3: "ACTION",
	}
	Category_value = map[string]int32{
		"PURE_PROPERTY": 0,
		"WILD_PROPERTY": 1,
		"MONEY":         2,
		"ACTION":        3,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

type Color int32

const (
	Color_NONE     Color = 0
	Color_BROWN    Color = 1
	Color_SKY      Color = 2
	Color_PINK     Color = 3
	Color_ORANGE   Color = 4
	Color_RED      Color = 5
	Color_YELLOW   Color = 6
	Color_GREEN    Color = 7
	Color_BLUE     Color = 8
	Color_UTILITY  Color = 9
	Color_RAILROAD Color = 10
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0:  "NONE",
		1:  "BROWN",
		2:  "SKY",
		3:  "PINK",
		4:  "ORANGE",
		5:  "RED",
		6:  "YELLOW",
		7:  "GREEN",
		8:  "BLUE",
		9:  "UTILITY",
		10: "RAILROAD",
	}
	Color_value = map[string]int32{
		"NONE":     0,
		"BROWN":    1,
		"SKY":      2,
		"PINK":     3,
		"ORANGE":   4,
		"RED":      5,
		"YELLOW":   6,
		"GREEN":    7,
		"BLUE":     8,
		"UTILITY":  9,
		"RAILROAD": 10,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[2].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[2]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

type DemandKind int32

const (
	DemandKind_PAYMENT      DemandKind = 0
	DemandKind_PROPERTY     DemandKind = 1
	DemandKind_PROPERTY_SET DemandKind = 2
)

// Enum value maps for DemandKind.
var (
	DemandKind_name = map[int32]string{
		0: "PAYMENT",
		1: "PROPERTY",
		2: "PROPERTY_SET",
	}
	DemandKind_value = map[string]int32{
		"PAYMENT":      0,
		"PROPERTY":     1,
		"PROPERTY_SET": 2,
	}
)

func (x DemandKind) Enum() *DemandKind {
	p := new(DemandKind)
	*p = x
	return p
}

func (x DemandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DemandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[3].Descriptor()
}

func (DemandKind) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[3]
}

func (x DemandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DemandKind.Descriptor instead.
func (DemandKind) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_monopoly_deal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AssetKey      AssetKey               `protobuf:"varint,2,opt,name=asset_key,json=assetKey,proto3,enum=fun_kames.schema.monopoly_deal.AssetKey" json:"asset_key,omitempty"`
	Category      Category               `protobuf:"varint,3,opt,name=category,proto3,enum=fun_kames.schema.monopoly_deal.Category" json:"category,omitempty"`
	ActiveColor   Color                  `protobuf:"varint,4,opt,name=active_color,json=activeColor,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"active_color,omitempty"`
	Colors        []Color                `protobuf:"varint,5,rep,packed,name=colors,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"colors,omitempty"`
	Value         int32                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_monopoly_deal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetAssetKey() AssetKey {
	if x != nil {
		return x.AssetKey
	}
	return AssetKey_BALTIC_AVE
}

func (x *Card) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_PURE_PROPERTY
}

func (x *Card) GetActiveColor() Color {
	if x != nil {
		return x.ActiveColor
	}
	return Color_NONE
}

func (x *Card) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Card) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_monopoly_deal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Player) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Hand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hand) Reset() {
	*x = Hand{}
	mi := &file_monopoly_deal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hand) ProtoMessage() {}

func (x *Hand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hand.ProtoReflect.Descriptor instead.
func (*Hand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

func (x *Hand) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type MaskedHand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NumCards      int32                  `protobuf:"varint,2,opt,name=num_cards,json=numCards,proto3" json:"num_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskedHand) Reset() {
	*x = MaskedHand{}
	mi := &file_monopoly_deal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskedHand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskedHand) ProtoMessage() {}

func (x *MaskedHand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskedHand.ProtoReflect.Descriptor instead.
func (*MaskedHand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{4}
}

func (x *MaskedHand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MaskedHand) GetNumCards() int32 {
	if x != nil {
		return x.NumCards
	}
	return 0
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_monopoly_deal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{5}
}

func (x *Money) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Money) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PropertySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySetId string                 `protobuf:"bytes,2,opt,name=property_set_id,json=propertySetId,proto3" json:"property_set_id,omitempty"`
	Color         Color                  `protobuf:"varint,3,opt,name=color,proto3,enum=fun_kames.schema.monopoly_deal.Color" json:"color,omitempty"`
	Cards         []*Card                `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySet) Reset() {
	*x = PropertySet{}
	mi := &file_monopoly_deal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySet) ProtoMessage() {}

func (x *PropertySet) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySet.ProtoReflect.Descriptor instead.
func (*PropertySet) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{6}
}

func (x *PropertySet) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PropertySet) GetPropertySetId() string {
	if x != nil {
		return x.PropertySetId
	}
	return ""
}

func (x *PropertySet) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_NONE
}

func (x *PropertySet) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PaymentDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDemand) Reset() {
	*x = PaymentDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDemand) ProtoMessage() {}

func (x *PaymentDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDemand.ProtoReflect.Descriptor instead.
func (*PaymentDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentDemand) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PropertyDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCardId  *string                `protobuf:"bytes,1,opt,name=source_card_id,json=sourceCardId,proto3,oneof" json:"source_card_id,omitempty"`
	TargetCardId  string                 `protobuf:"bytes,2,opt,name=target_card_id,json=targetCardId,proto3" json:"target_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyDemand) Reset() {
	*x = PropertyDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyDemand) ProtoMessage() {}

func (x *PropertyDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyDemand.ProtoReflect.Descriptor instead.
func (*PropertyDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{8}
}

func (x *PropertyDemand) GetSourceCardId() string {
	if x != nil && x.SourceCardId != nil {
		return *x.SourceCardId
	}
	return ""
}

func (x *PropertyDemand) GetTargetCardId() string {
	if x != nil {
		return x.TargetCardId
	}
	return ""
}

type PropertySetDemand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertySetId string                 `protobuf:"bytes,1,opt,name=property_set_id,json=propertySetId,proto3" json:"property_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySetDemand) Reset() {
	*x = PropertySetDemand{}
	mi := &file_monopoly_deal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySetDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySetDemand) ProtoMessage() {}

func (x *PropertySetDemand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySetDemand.ProtoReflect.Descriptor instead.
func (*PropertySetDemand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{9}
}

func (x *PropertySetDemand) GetPropertySetId() string {
	if x != nil {
		return x.PropertySetId
	}
	return ""
}

type Demand struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceId   string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DemandKind DemandKind             `protobuf:"varint,2,opt,name=demand_kind,json=demandKind,proto3,enum=fun_kames.schema.monopoly_deal.DemandKind" json:"demand_kind,omitempty"`
	// Types that are valid to be assigned to Demand:
	//
	//	*Demand_PaymentDemand
	//	*Demand_PropertyDemand
	//	*Demand_PropertySetDemand
	Demand        isDemand_Demand `protobuf_oneof:"demand"`
	IsActive      bool            `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demand) Reset() {
	*x = Demand{}
	mi := &file_monopoly_deal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demand) ProtoMessage() {}

func (x *Demand) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demand.ProtoReflect.Descriptor instead.
func (*Demand) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{10}
}

func (x *Demand) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Demand) GetDemandKind() DemandKind {
	if x != nil {
		return x.DemandKind
	}
	return DemandKind_PAYMENT
}

func (x *Demand) GetDemand() isDemand_Demand {
	if x != nil {
		return x.Demand
	}
	return nil
}

func (x *Demand) GetPaymentDemand() *PaymentDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PaymentDemand); ok {
			return x.PaymentDemand
		}
	}
	return nil
}

func (x *Demand) GetPropertyDemand() *PropertyDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PropertyDemand); ok {
			return x.PropertyDemand
		}
	}
	return nil
}

func (x *Demand) GetPropertySetDemand() *PropertySetDemand {
	if x != nil {
		if x, ok := x.Demand.(*Demand_PropertySetDemand); ok {
			return x.PropertySetDemand
		}
	}
	return nil
}

func (x *Demand) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type isDemand_Demand interface {
	isDemand_Demand()
}

type Demand_PaymentDemand struct {
	PaymentDemand *PaymentDemand `protobuf:"bytes,3,opt,name=payment_demand,json=paymentDemand,proto3,oneof"`
}

type Demand_PropertyDemand struct {
	PropertyDemand *PropertyDemand `protobuf:"bytes,4,opt,name=property_demand,json=propertyDemand,proto3,oneof"`
}

type Demand_PropertySetDemand struct {
	PropertySetDemand *PropertySetDemand `protobuf:"bytes,5,opt,name=property_set_demand,json=propertySetDemand,proto3,oneof"`
}

func (*Demand_PaymentDemand) isDemand_Demand() {}

func (*Demand_PropertyDemand) isDemand_Demand() {}

func (*Demand_PropertySetDemand) isDemand_Demand() {}

type PendingRent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetIds     []string               `protobuf:"bytes,2,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	BaseAmount    int32                  `protobuf:"varint,3,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	Multiplier    int32                  `protobuf:"varint,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRent) Reset() {
	*x = PendingRent{}
	mi := &file_monopoly_deal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRent) ProtoMessage() {}

func (x *PendingRent) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRent.ProtoReflect.Descriptor instead.
func (*PendingRent) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{11}
}

func (x *PendingRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PendingRent) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *PendingRent) GetBaseAmount() int32 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *PendingRent) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type AssetImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetKey      AssetKey               `protobuf:"varint,1,opt,name=asset_key,json=assetKey,proto3,enum=fun_kames.schema.monopoly_deal.AssetKey" json:"asset_key,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetImage) Reset() {
	*x = AssetImage{}
	mi := &file_monopoly_deal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetImage) ProtoMessage() {}

func (x *AssetImage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetImage.ProtoReflect.Descriptor instead.
func (*AssetImage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{12}
}

func (x *AssetImage) GetAssetKey() AssetKey {
	if x != nil {
		return x.AssetKey
	}
	return AssetKey_BALTIC_AVE
}

func (x *AssetImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GameState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SeqNum          int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Players         []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	CurrentPlayerId string                 `protobuf:"bytes,3,opt,name=current_player_id,json=currentPlayerId,proto3" json:"current_player_id,omitempty"`
	MovesLeft       int32                  `protobuf:"varint,4,opt,name=moves_left,json=movesLeft,proto3" json:"moves_left,omitempty"`
	YourHand        *Hand                  `protobuf:"bytes,5,opt,name=your_hand,json=yourHand,proto3" json:"your_hand,omitempty"`
	OtherHands      []*MaskedHand          `protobuf:"bytes,6,rep,name=other_hands,json=otherHands,proto3" json:"other_hands,omitempty"`
	Money           []*Money               `protobuf:"bytes,7,rep,name=money,proto3" json:"money,omitempty"`
	Properties      []*PropertySet         `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty"`
	Demand          *Demand                `protobuf:"bytes,9,opt,name=demand,proto3,oneof" json:"demand,omitempty"`
	PendingRent     *PendingRent           `protobuf:"bytes,10,opt,name=pending_rent,json=pendingRent,proto3,oneof" json:"pending_rent,omitempty"`
	LastAction      *Card                  `protobuf:"bytes,11,opt,name=last_action,json=lastAction,proto3" json:"last_action,omitempty"`
	AssetImages     []*AssetImage          `protobuf:"bytes,12,rep,name=asset_images,json=assetImages,proto3" json:"asset_images,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_monopoly_deal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{13}
}

func (x *GameState) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *GameState) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetCurrentPlayerId() string {
	if x != nil {
		return x.CurrentPlayerId
	}
	return ""
}

func (x *GameState) GetMovesLeft() int32 {
	if x != nil {
		return x.MovesLeft
	}
	return 0
}

func (x *GameState) GetYourHand() *Hand {
	if x != nil {
		return x.YourHand
	}
	return nil
}

func (x *GameState) GetOtherHands() []*MaskedHand {
	if x != nil {
		return x.OtherHands
	}
	return nil
}

func (x *GameState) GetMoney() []*Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *GameState) GetProperties() []*PropertySet {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GameState) GetDemand() *Demand {
	if x != nil {
		return x.Demand
	}
	return nil
}

func (x *GameState) GetPendingRent() *PendingRent {
	if x != nil {
		return x.PendingRent
	}
	return nil
}

func (x *GameState) GetLastAction() *Card {
	if x != nil {
		return x.LastAction
	}
	return nil
}

func (x *GameState) GetAssetImages() []*AssetImage {
	if x != nil {
		return x.AssetImages
	}
	return nil
}

type StartTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTurn) Reset() {
	*x = StartTurn{}
	mi := &file_monopoly_deal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTurn) ProtoMessage() {}

func (x *StartTurn) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTurn.ProtoReflect.Descriptor instead.
func (*StartTurn) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{14}
}

type StartTurnRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTurnRes) Reset() {
	*x = StartTurnRes{}
	mi := &file_monopoly_deal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTurnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTurnRes) ProtoMessage() {}

func (x *StartTurnRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTurnRes.ProtoReflect.Descriptor instead.
func (*StartTurnRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{15}
}

func (x *StartTurnRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *StartTurnRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StartTurnRes) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type StartTurnMaskedRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NumCards      int32                  `protobuf:"varint,3,opt,name=num_cards,json=numCards,proto3" json:"num_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTurnMaskedRes) Reset() {
	*x = StartTurnMaskedRes{}
	mi := &file_monopoly_deal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTurnMaskedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTurnMaskedRes) ProtoMessage() {}

func (x *StartTurnMaskedRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTurnMaskedRes.ProtoReflect.Descriptor instead.
func (*StartTurnMaskedRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{16}
}

func (x *StartTurnMaskedRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *StartTurnMaskedRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StartTurnMaskedRes) GetNumCards() int32 {
	if x != nil {
		return x.NumCards
	}
	return 0
}

type PlayMoney struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoney) Reset() {
	*x = PlayMoney{}
	mi := &file_monopoly_deal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoney) ProtoMessage() {}

func (x *PlayMoney) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoney.ProtoReflect.Descriptor instead.
func (*PlayMoney) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{17}
}

func (x *PlayMoney) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type PlayMoneyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoneyRes) Reset() {
	*x = PlayMoneyRes{}
	mi := &file_monopoly_deal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoneyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoneyRes) ProtoMessage() {}

func (x *PlayMoneyRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoneyRes.ProtoReflect.Descriptor instead.
func (*PlayMoneyRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{18}
}

func (x *PlayMoneyRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayMoneyRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayMoneyRes) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type PlayProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	PropertySetId *string                `protobuf:"bytes,2,opt,name=property_set_id,json=propertySetId,proto3,oneof" json:"property_set_id,omitempty"`
	ActiveColor   *Color                 `protobuf:"varint,3,opt,name=active_color,json=activeColor,proto3,enum=fun_kames.schema.monopoly_deal.Color,oneof" json:"active_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayProperty) Reset() {
	*x = PlayProperty{}
	mi := &file_monopoly_deal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayProperty) ProtoMessage() {}

func (x *PlayProperty) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayProperty.ProtoReflect.Descriptor instead.
func (*PlayProperty) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{19}
}

func (x *PlayProperty) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PlayProperty) GetPropertySetId() string {
	if x != nil && x.PropertySetId != nil {
		return *x.PropertySetId
	}
	return ""
}

func (x *PlayProperty) GetActiveColor() Color {
	if x != nil && x.ActiveColor != nil {
		return *x.ActiveColor
	}
	return Color_NONE
}

type PlayPropertyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySet           `protobuf:"bytes,3,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPropertyRes) Reset() {
	*x = PlayPropertyRes{}
	mi := &file_monopoly_deal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPropertyRes) ProtoMessage() {}

func (x *PlayPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPropertyRes.ProtoReflect.Descriptor instead.
func (*PlayPropertyRes) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{20}
}

func (x *PlayPropertyRes) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlayPropertyRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayPropertyRes) GetPropertySet() *PropertySet {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_StartTurn
	//	*ClientMessage_PlayMoney
	//	*ClientMessage_PlayProperty
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{21}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetStartTurn() *StartTurn {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_StartTurn); ok {
			return x.StartTurn
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayMoney() *PlayMoney {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayMoney); ok {
			return x.PlayMoney
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayProperty() *PlayProperty {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayProperty); ok {
			return x.PlayProperty
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_StartTurn struct {
	StartTurn *StartTurn `protobuf:"bytes,1,opt,name=start_turn,json=startTurn,proto3,oneof"`
}

type ClientMessage_PlayMoney struct {
	PlayMoney *PlayMoney `protobuf:"bytes,2,opt,name=play_money,json=playMoney,proto3,oneof"`
}

type ClientMessage_PlayProperty struct {
	PlayProperty *PlayProperty `protobuf:"bytes,3,opt,name=play_property,json=playProperty,proto3,oneof"`
}

func (*ClientMessage_StartTurn) isClientMessage_Payload() {}

func (*ClientMessage_PlayMoney) isClientMessage_Payload() {}

func (*ClientMessage_PlayProperty) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Error
	//	*ServerMessage_GameState
	//	*ServerMessage_StartTurnRes
	//	*ServerMessage_StartTurnMaskedRes
	//	*ServerMessage_PlayMoneyRes
	//	*ServerMessage_PlayPropertyRes
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{22}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerMessage) GetStartTurnRes() *StartTurnRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StartTurnRes); ok {
			return x.StartTurnRes
		}
	}
	return nil
}

func (x *ServerMessage) GetStartTurnMaskedRes() *StartTurnMaskedRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_StartTurnMaskedRes); ok {
			return x.StartTurnMaskedRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayMoneyRes() *PlayMoneyRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayMoneyRes); ok {
			return x.PlayMoneyRes
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayPropertyRes() *PlayPropertyRes {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayPropertyRes); ok {
			return x.PlayPropertyRes
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type ServerMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,2,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerMessage_StartTurnRes struct {
	StartTurnRes *StartTurnRes `protobuf:"bytes,3,opt,name=start_turn_res,json=startTurnRes,proto3,oneof"`
}

type ServerMessage_StartTurnMaskedRes struct {
	StartTurnMaskedRes *StartTurnMaskedRes `protobuf:"bytes,4,opt,name=start_turn_masked_res,json=startTurnMaskedRes,proto3,oneof"`
}

type ServerMessage_PlayMoneyRes struct {
	PlayMoneyRes *PlayMoneyRes `protobuf:"bytes,5,opt,name=play_money_res,json=playMoneyRes,proto3,oneof"`
}

type ServerMessage_PlayPropertyRes struct {
	PlayPropertyRes *PlayPropertyRes `protobuf:"bytes,6,opt,name=play_property_res,json=playPropertyRes,proto3,oneof"`
}

func (*ServerMessage_Error) isServerMessage_Payload() {}

func (*ServerMessage_GameState) isServerMessage_Payload() {}

func (*ServerMessage_StartTurnRes) isServerMessage_Payload() {}

func (*ServerMessage_StartTurnMaskedRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayMoneyRes) isServerMessage_Payload() {}

func (*ServerMessage_PlayPropertyRes) isServerMessage_Payload() {}

var File_monopoly_deal_proto protoreflect.FileDescriptor

const file_monopoly_deal_proto_rawDesc = "" +
	"\n" +
	"\x13monopoly_deal.proto\x12\x1efun_kames.schema.monopoly_deal\"M\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xcb\x02\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12E\n" +
	"\tasset_key\x18\x02 \x01(\x0e2(.fun_kames.schema.monopoly_deal.AssetKeyR\bassetKey\x12D\n" +
	"\bcategory\x18\x03 \x01(\x0e2(.fun_kames.schema.monopoly_deal.CategoryR\bcategory\x12H\n" +
	"\factive_color\x18\x04 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\vactiveColor\x12=\n" +
	"\x06colors\x18\x05 \x03(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\x06colors\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x05R\x05value\"g\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"B\n" +
	"\x04Hand\x12:\n" +
	"\x05cards\x18\x01 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"F\n" +
	"\n" +
	"MaskedHand\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tnum_cards\x18\x02 \x01(\x05R\bnumCards\"`\n" +
	"\x05Money\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\x05cards\x18\x02 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"\xcb\x01\n" +
	"\vPropertySet\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12&\n" +
	"\x0fproperty_set_id\x18\x02 \x01(\tR\rpropertySetId\x12;\n" +
	"\x05color\x18\x03 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorR\x05color\x12:\n" +
	"\x05cards\x18\x04 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"'\n" +
	"\rPaymentDemand\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"t\n" +
	"\x0ePropertyDemand\x12)\n" +
	"\x0esource_card_id\x18\x01 \x01(\tH\x00R\fsourceCardId\x88\x01\x01\x12$\n" +
	"\x0etarget_card_id\x18\x02 \x01(\tR\ftargetCardIdB\x11\n" +
	"\x0f_source_card_id\";\n" +
	"\x11PropertySetDemand\x12&\n" +
	"\x0fproperty_set_id\x18\x01 \x01(\tR\rpropertySetId\"\xb1\x03\n" +
	"\x06Demand\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12K\n" +
	"\vdemand_kind\x18\x02 \x01(\x0e2*.fun_kames.schema.monopoly_deal.DemandKindR\n" +
	"demandKind\x12V\n" +
	"\x0epayment_demand\x18\x03 \x01(\v2-.fun_kames.schema.monopoly_deal.PaymentDemandH\x00R\rpaymentDemand\x12Y\n" +
	"\x0fproperty_demand\x18\x04 \x01(\v2..fun_kames.schema.monopoly_deal.PropertyDemandH\x00R\x0epropertyDemand\x12c\n" +
	"\x13property_set_demand\x18\x05 \x01(\v21.fun_kames.schema.monopoly_deal.PropertySetDemandH\x00R\x11propertySetDemand\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActiveB\b\n" +
	"\x06demand\"\x8a\x01\n" +
	"\vPendingRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x02 \x03(\tR\ttargetIds\x12\x1f\n" +
	"\vbase_amount\x18\x03 \x01(\x05R\n" +
	"baseAmount\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x05R\n" +
	"multiplier\"p\n" +
	"\n" +
	"AssetImage\x12E\n" +
	"\tasset_key\x18\x01 \x01(\x0e2(.fun_kames.schema.monopoly_deal.AssetKeyR\bassetKey\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"\x97\x06\n" +
	"\tGameState\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12@\n" +
	"\aplayers\x18\x02 \x03(\v2&.fun_kames.schema.monopoly_deal.PlayerR\aplayers\x12*\n" +
	"\x11current_player_id\x18\x03 \x01(\tR\x0fcurrentPlayerId\x12\x1d\n" +
	"\n" +
	"moves_left\x18\x04 \x01(\x05R\tmovesLeft\x12A\n" +
	"\tyour_hand\x18\x05 \x01(\v2$.fun_kames.schema.monopoly_deal.HandR\byourHand\x12K\n" +
	"\vother_hands\x18\x06 \x03(\v2*.fun_kames.schema.monopoly_deal.MaskedHandR\n" +
	"otherHands\x12;\n" +
	"\x05money\x18\a \x03(\v2%.fun_kames.schema.monopoly_deal.MoneyR\x05money\x12K\n" +
	"\n" +
	"properties\x18\b \x03(\v2+.fun_kames.schema.monopoly_deal.PropertySetR\n" +
	"properties\x12C\n" +
	"\x06demand\x18\t \x01(\v2&.fun_kames.schema.monopoly_deal.DemandH\x00R\x06demand\x88\x01\x01\x12S\n" +
	"\fpending_rent\x18\n" +
	" \x01(\v2+.fun_kames.schema.monopoly_deal.PendingRentH\x01R\vpendingRent\x88\x01\x01\x12E\n" +
	"\vlast_action\x18\v \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\n" +
	"lastAction\x12M\n" +
	"\fasset_images\x18\f \x03(\v2*.fun_kames.schema.monopoly_deal.AssetImageR\vassetImagesB\t\n" +
	"\a_demandB\x0f\n" +
	"\r_pending_rent\"\v\n" +
	"\tStartTurn\"\x80\x01\n" +
	"\fStartTurnRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12:\n" +
	"\x05cards\x18\x03 \x03(\v2$.fun_kames.schema.monopoly_deal.CardR\x05cards\"g\n" +
	"\x12StartTurnMaskedRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tnum_cards\x18\x03 \x01(\x05R\bnumCards\"$\n" +
	"\tPlayMoney\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"~\n" +
	"\fPlayMoneyRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x128\n" +
	"\x04card\x18\x03 \x01(\v2$.fun_kames.schema.monopoly_deal.CardR\x04card\"\xc8\x01\n" +
	"\fPlayProperty\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12+\n" +
	"\x0fproperty_set_id\x18\x02 \x01(\tH\x00R\rpropertySetId\x88\x01\x01\x12M\n" +
	"\factive_color\x18\x03 \x01(\x0e2%.fun_kames.schema.monopoly_deal.ColorH\x01R\vactiveColor\x88\x01\x01B\x12\n" +
	"\x10_property_set_idB\x0f\n" +
	"\r_active_color\"\x97\x01\n" +
	"\x0fPlayPropertyRes\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12N\n" +
	"\fproperty_set\x18\x03 \x01(\v2+.fun_kames.schema.monopoly_deal.PropertySetR\vpropertySet\"\x87\x02\n" +
	"\rClientMessage\x12J\n" +
	"\n" +
	"start_turn\x18\x01 \x01(\v2).fun_kames.schema.monopoly_deal.StartTurnH\x00R\tstartTurn\x12J\n" +
	"\n" +
	"play_money\x18\x02 \x01(\v2).fun_kames.schema.monopoly_deal.PlayMoneyH\x00R\tplayMoney\x12S\n" +
	"\rplay_property\x18\x03 \x01(\v2,.fun_kames.schema.monopoly_deal.PlayPropertyH\x00R\fplayPropertyB\t\n" +
	"\apayload\"\x99\x04\n" +
	"\rServerMessage\x12=\n" +
	"\x05error\x18\x01 \x01(\v2%.fun_kames.schema.monopoly_deal.ErrorH\x00R\x05error\x12J\n" +
	"\n" +
	"game_state\x18\x02 \x01(\v2).fun_kames.schema.monopoly_deal.GameStateH\x00R\tgameState\x12T\n" +
	"\x0estart_turn_res\x18\x03 \x01(\v2,.fun_kames.schema.monopoly_deal.StartTurnResH\x00R\fstartTurnRes\x12g\n" +
	"\x15start_turn_masked_res\x18\x04 \x01(\v22.fun_kames.schema.monopoly_deal.StartTurnMaskedResH\x00R\x12startTurnMaskedRes\x12T\n" +
	"\x0eplay_money_res\x18\x05 \x01(\v2,.fun_kames.schema.monopoly_deal.PlayMoneyResH\x00R\fplayMoneyRes\x12]\n" +
	"\x11play_property_res\x18\x06 \x01(\v2/.fun_kames.schema.monopoly_deal.PlayPropertyResH\x00R\x0fplayPropertyResB\t\n" +
	"\apayload*\xbf\b\n" +
	"\bAssetKey\x12\x0e\n" +
	"\n" +
	"BALTIC_AVE\x10\x00\x12\x15\n" +
	"\x11MEDITERRANEAN_AVE\x10\x01\x12\x13\n" +
	"\x0fCONNECTICUT_AVE\x10\x02\x12\x10\n" +
	"\fORIENTAL_AVE\x10\x03\x12\x0f\n" +
	"\vVERMONT_AVE\x10\x04\x12\x14\n" +
	"\x10ST_CHARLES_PLACE\x10\x05\x12\x10\n" +
	"\fVIRGINIA_AVE\x10\x06\x12\r\n" +
	"\tSTATE_AVE\x10\a\x12\x10\n" +
	"\fNEW_YORK_AVE\x10\b\x12\x12\n" +
	"\x0eST_JAMES_PLACE\x10\t\x12\x11\n" +
	"\rTENNESSEE_AVE\x10\n" +
	"\x12\x10\n" +
	"\fKENTUCKY_AVE\x10\v\x12\x0f\n" +
	"\vINDIANA_AVE\x10\f\x12\x10\n" +
	"\fILLINOIS_AVE\x10\r\x12\x0f\n" +
	"\vVENTNOR_AVE\x10\x0e\x12\x12\n" +
	"\x0eMARVIN_GARDENS\x10\x0f\x12\x10\n" +
	"\fATLANTIC_AVE\x10\x10\x12\x16\n" +
	"\x12NORTH_CAROLINA_AVE\x10\x11\x12\x0f\n" +
	"\vPACIFIC_AVE\x10\x12\x12\x14\n" +
	"\x10PENNSYLVANIA_AVE\x10\x13\x12\r\n" +
	"\tBOARDWALK\x10\x14\x12\x0e\n" +
	"\n" +
	"PARK_PLACE\x10\x15\x12\x0f\n" +
	"\vWATER_WORKS\x10\x16\x12\x14\n" +
	"\x10ELECTRIC_COMPANY\x10\x17\x12\x0e\n" +
	"\n" +
	"SHORT_LINE\x10\x18\x12\x14\n" +
	"\x10B_AND_O_RAILROAD\x10\x19\x12\x14\n" +
	"\x10READING_RAILROAD\x10\x1a\x12\x19\n" +
	"\x15PENNSYLVANIA_RAILROAD\x10\x1b\x12\x12\n" +
	"\x0eWILD_BROWN_SKY\x10\x1c\x12\x15\n" +
	"\x11WILD_SKY_RAILROAD\x10\x1d\x12\x14\n" +
	"\x10WILD_PINK_ORANGE\x10\x1e\x12\x13\n" +
	"\x0fWILD_RED_YELLOW\x10\x1f\x12\x13\n" +
	"\x0fWILD_GREEN_BLUE\x10 \x12\x17\n" +
	"\x13WILD_GREEN_RAILROAD\x10!\x12\x19\n" +
	"\x15WILD_UTILITY_RAILROAD\x10\"\x12\r\n" +
	"\tWILD_WILD\x10#\x12\f\n" +
	"\bMONEY_10\x10$\x12\v\n" +
	"\aMONEY_5\x10%\x12\v\n" +
	"\aMONEY_4\x10&\x12\v\n" +
	"\aMONEY_3\x10'\x12\v\n" +
	"\aMONEY_2\x10(\x12\v\n" +
	"\aMONEY_1\x10)\x12\x10\n" +
	"\fDEAL_BREAKER\x10*\x12\x0f\n" +
	"\vJUST_SAY_NO\x10+\x12\t\n" +
	"\x05HOTEL\x10,\x12\x12\n" +
	"\x0eDEBT_COLLECTOR\x10-\x12\x0f\n" +
	"\vFORCED_DEAL\x10.\x12\f\n" +
	"\bSLY_DEAL\x10/\x12\t\n" +
	"\x05HOUSE\x100\x12\x13\n" +
	"\x0fITS_MY_BIRTHDAY\x101\x12\x13\n" +
	"\x0fDOUBLE_THE_RENT\x102\x12\v\n" +
	"\aPASS_GO\x103\x12\r\n" +
	"\tRENT_WILD\x104\x12\x12\n" +
	"\x0eRENT_BROWN_SKY\x105\x12\x14\n" +
	"\x10RENT_PINK_ORANGE\x106\x12\x13\n" +
	"\x0fRENT_RED_YELLOW\x107\x12\x13\n" +
	"\x0fRENT_GREEN_BLUE\x108\x12\x19\n" +
	"\x15RENT_UTILITY_RAILROAD\x109*G\n" +
	"\bCategory\x12\x11\n" +
	"\rPURE_PROPERTY\x10\x00\x12\x11\n" +
	"\rWILD_PROPERTY\x10\x01\x12\t\n" +
	"\x05MONEY\x10\x02\x12\n" +
	"\n" +
	"\x06ACTION\x10\x03*\x80\x01\n" +
	"\x05Color\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05BROWN\x10\x01\x12\a\n" +
	"\x03SKY\x10\x02\x12\b\n" +
	"\x04PINK\x10\x03\x12\n" +
	"\n" +
	"\x06ORANGE\x10\x04\x12\a\n" +
	"\x03RED\x10\x05\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x06\x12\t\n" +
	"\x05GREEN\x10\a\x12\b\n" +
	"\x04BLUE\x10\b\x12\v\n" +
	"\aUTILITY\x10\t\x12\f\n" +
	"\bRAILROAD\x10\n" +
	"*9\n" +
	"\n" +
	"DemandKind\x12\v\n" +
	"\aPAYMENT\x10\x00\x12\f\n" +
	"\bPROPERTY\x10\x01\x12\x10\n" +
	"\fPROPERTY_SET\x10\x02BEZCfun-kames/internal/schema/monopoly_deal_schema;monopoly_deal_schemab\x06proto3"

var (
	file_monopoly_deal_proto_rawDescOnce sync.Once
	file_monopoly_deal_proto_rawDescData []byte
)

func file_monopoly_deal_proto_rawDescGZIP() []byte {
	file_monopoly_deal_proto_rawDescOnce.Do(func() {
		file_monopoly_deal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)))
	})
	return file_monopoly_deal_proto_rawDescData
}

var file_monopoly_deal_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_monopoly_deal_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_monopoly_deal_proto_goTypes = []any{
	(AssetKey)(0),              // 0: fun_kames.schema.monopoly_deal.AssetKey
	(Category)(0),              // 1: fun_kames.schema.monopoly_deal.Category
	(Color)(0),                 // 2: fun_kames.schema.monopoly_deal.Color
	(DemandKind)(0),            // 3: fun_kames.schema.monopoly_deal.DemandKind
	(*Error)(nil),              // 4: fun_kames.schema.monopoly_deal.Error
	(*Card)(nil),               // 5: fun_kames.schema.monopoly_deal.Card
	(*Player)(nil),             // 6: fun_kames.schema.monopoly_deal.Player
	(*Hand)(nil),               // 7: fun_kames.schema.monopoly_deal.Hand
	(*MaskedHand)(nil),         // 8: fun_kames.schema.monopoly_deal.MaskedHand
	(*Money)(nil),              // 9: fun_kames.schema.monopoly_deal.Money
	(*PropertySet)(nil),        // 10: fun_kames.schema.monopoly_deal.PropertySet
	(*PaymentDemand)(nil),      // 11: fun_kames.schema.monopoly_deal.PaymentDemand
	(*PropertyDemand)(nil),     // 12: fun_kames.schema.monopoly_deal.PropertyDemand
	(*PropertySetDemand)(nil),  // 13: fun_kames.schema.monopoly_deal.PropertySetDemand
	(*Demand)(nil),             // 14: fun_kames.schema.monopoly_deal.Demand
	(*PendingRent)(nil),        // 15: fun_kames.schema.monopoly_deal.PendingRent
	(*AssetImage)(nil),         // 16: fun_kames.schema.monopoly_deal.AssetImage
	(*GameState)(nil),          // 17: fun_kames.schema.monopoly_deal.GameState
	(*StartTurn)(nil),          // 18: fun_kames.schema.monopoly_deal.StartTurn
	(*StartTurnRes)(nil),       // 19: fun_kames.schema.monopoly_deal.StartTurnRes
	(*StartTurnMaskedRes)(nil), // 20: fun_kames.schema.monopoly_deal.StartTurnMaskedRes
	(*PlayMoney)(nil),          // 21: fun_kames.schema.monopoly_deal.PlayMoney
	(*PlayMoneyRes)(nil),       // 22: fun_kames.schema.monopoly_deal.PlayMoneyRes
	(*PlayProperty)(nil),       // 23: fun_kames.schema.monopoly_deal.PlayProperty
	(*PlayPropertyRes)(nil),    // 24: fun_kames.schema.monopoly_deal.PlayPropertyRes
	(*ClientMessage)(nil),      // 25: fun_kames.schema.monopoly_deal.ClientMessage
	(*ServerMessage)(nil),      // 26: fun_kames.schema.monopoly_deal.ServerMessage
}
var file_monopoly_deal_proto_depIdxs = []int32{
	0,  // 0: fun_kames.schema.monopoly_deal.Card.asset_key:type_name -> fun_kames.schema.monopoly_deal.AssetKey
	1,  // 1: fun_kames.schema.monopoly_deal.Card.category:type_name -> fun_kames.schema.monopoly_deal.Category
	2,  // 2: fun_kames.schema.monopoly_deal.Card.active_color:type_name -> fun_kames.schema.monopoly_deal.Color
	2,  // 3: fun_kames.schema.monopoly_deal.Card.colors:type_name -> fun_kames.schema.monopoly_deal.Color
	5,  // 4: fun_kames.schema.monopoly_deal.Hand.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	5,  // 5: fun_kames.schema.monopoly_deal.Money.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	2,  // 6: fun_kames.schema.monopoly_deal.PropertySet.color:type_name -> fun_kames.schema.monopoly_deal.Color
	5,  // 7: fun_kames.schema.monopoly_deal.PropertySet.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	3,  // 8: fun_kames.schema.monopoly_deal.Demand.demand_kind:type_name -> fun_kames.schema.monopoly_deal.DemandKind
	11, // 9: fun_kames.schema.monopoly_deal.Demand.payment_demand:type_name -> fun_kames.schema.monopoly_deal.PaymentDemand
	12, // 10: fun_kames.schema.monopoly_deal.Demand.property_demand:type_name -> fun_kames.schema.monopoly_deal.PropertyDemand
	13, // 11: fun_kames.schema.monopoly_deal.Demand.property_set_demand:type_name -> fun_kames.schema.monopoly_deal.PropertySetDemand
	0,  // 12: fun_kames.schema.monopoly_deal.AssetImage.asset_key:type_name -> fun_kames.schema.monopoly_deal.AssetKey
	6,  // 13: fun_kames.schema.monopoly_deal.GameState.players:type_name -> fun_kames.schema.monopoly_deal.Player
	7,  // 14: fun_kames.schema.monopoly_deal.GameState.your_hand:type_name -> fun_kames.schema.monopoly_deal.Hand
	8,  // 15: fun_kames.schema.monopoly_deal.GameState.other_hands:type_name -> fun_kames.schema.monopoly_deal.MaskedHand
	9,  // 16: fun_kames.schema.monopoly_deal.GameState.money:type_name -> fun_kames.schema.monopoly_deal.Money
	10, // 17: fun_kames.schema.monopoly_deal.GameState.properties:type_name -> fun_kames.schema.monopoly_deal.PropertySet
	14, // 18: fun_kames.schema.monopoly_deal.GameState.demand:type_name -> fun_kames.schema.monopoly_deal.Demand
	15, // 19: fun_kames.schema.monopoly_deal.GameState.pending_rent:type_name -> fun_kames.schema.monopoly_deal.PendingRent
	5,  // 20: fun_kames.schema.monopoly_deal.GameState.last_action:type_name -> fun_kames.schema.monopoly_deal.Card
	16, // 21: fun_kames.schema.monopoly_deal.GameState.asset_images:type_name -> fun_kames.schema.monopoly_deal.AssetImage
	5,  // 22: fun_kames.schema.monopoly_deal.StartTurnRes.cards:type_name -> fun_kames.schema.monopoly_deal.Card
	5,  // 23: fun_kames.schema.monopoly_deal.PlayMoneyRes.card:type_name -> fun_kames.schema.monopoly_deal.Card
	2,  // 24: fun_kames.schema.monopoly_deal.PlayProperty.active_color:type_name -> fun_kames.schema.monopoly_deal.Color
	10, // 25: fun_kames.schema.monopoly_deal.PlayPropertyRes.property_set:type_name -> fun_kames.schema.monopoly_deal.PropertySet
	18, // 26: fun_kames.schema.monopoly_deal.ClientMessage.start_turn:type_name -> fun_kames.schema.monopoly_deal.StartTurn
	21, // 27: fun_kames.schema.monopoly_deal.ClientMessage.play_money:type_name -> fun_kames.schema.monopoly_deal.PlayMoney
	23, // 28: fun_kames.schema.monopoly_deal.ClientMessage.play_property:type_name -> fun_kames.schema.monopoly_deal.PlayProperty
	4,  // 29: fun_kames.schema.monopoly_deal.ServerMessage.error:type_name -> fun_kames.schema.monopoly_deal.Error
	17, // 30: fun_kames.schema.monopoly_deal.ServerMessage.game_state:type_name -> fun_kames.schema.monopoly_deal.GameState
	19, // 31: fun_kames.schema.monopoly_deal.ServerMessage.start_turn_res:type_name -> fun_kames.schema.monopoly_deal.StartTurnRes
	20, // 32: fun_kames.schema.monopoly_deal.ServerMessage.start_turn_masked_res:type_name -> fun_kames.schema.monopoly_deal.StartTurnMaskedRes
	22, // 33: fun_kames.schema.monopoly_deal.ServerMessage.play_money_res:type_name -> fun_kames.schema.monopoly_deal.PlayMoneyRes
	24, // 34: fun_kames.schema.monopoly_deal.ServerMessage.play_property_res:type_name -> fun_kames.schema.monopoly_deal.PlayPropertyRes
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_monopoly_deal_proto_init() }
func file_monopoly_deal_proto_init() {
	if File_monopoly_deal_proto != nil {
		return
	}
	file_monopoly_deal_proto_msgTypes[8].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[10].OneofWrappers = []any{
		(*Demand_PaymentDemand)(nil),
		(*Demand_PropertyDemand)(nil),
		(*Demand_PropertySetDemand)(nil),
	}
	file_monopoly_deal_proto_msgTypes[13].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[19].OneofWrappers = []any{}
	file_monopoly_deal_proto_msgTypes[21].OneofWrappers = []any{
		(*ClientMessage_StartTurn)(nil),
		(*ClientMessage_PlayMoney)(nil),
		(*ClientMessage_PlayProperty)(nil),
	}
	file_monopoly_deal_proto_msgTypes[22].OneofWrappers = []any{
		(*ServerMessage_Error)(nil),
		(*ServerMessage_GameState)(nil),
		(*ServerMessage_StartTurnRes)(nil),
		(*ServerMessage_StartTurnMaskedRes)(nil),
		(*ServerMessage_PlayMoneyRes)(nil),
		(*ServerMessage_PlayPropertyRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monopoly_deal_proto_goTypes,
		DependencyIndexes: file_monopoly_deal_proto_depIdxs,
		EnumInfos:         file_monopoly_deal_proto_enumTypes,
		MessageInfos:      file_monopoly_deal_proto_msgTypes,
	}.Build()
	File_monopoly_deal_proto = out.File
	file_monopoly_deal_proto_goTypes = nil
	file_monopoly_deal_proto_depIdxs = nil
}
