// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: message.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs    int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Ping
	//	*ClientMessage_RoomMessage
	//	*ClientMessage_MonopolyDealMessage
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetRoomMessage() *ClientRoomMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_RoomMessage); ok {
			return x.RoomMessage
		}
	}
	return nil
}

func (x *ClientMessage) GetMonopolyDealMessage() *ClientMonopolyDealMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_MonopolyDealMessage); ok {
			return x.MonopolyDealMessage
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ClientMessage_RoomMessage struct {
	RoomMessage *ClientRoomMessage `protobuf:"bytes,10,opt,name=room_message,json=roomMessage,proto3,oneof"`
}

type ClientMessage_MonopolyDealMessage struct {
	MonopolyDealMessage *ClientMonopolyDealMessage `protobuf:"bytes,11,opt,name=monopoly_deal_message,json=monopolyDealMessage,proto3,oneof"`
}

func (*ClientMessage_Ping) isClientMessage_Payload() {}

func (*ClientMessage_RoomMessage) isClientMessage_Payload() {}

func (*ClientMessage_MonopolyDealMessage) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ping
	//	*ServerMessage_RoomMessage
	//	*ServerMessage_MonopolyDealMessage
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomMessage() *ServerRoomMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RoomMessage); ok {
			return x.RoomMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetMonopolyDealMessage() *ServerMonopolyDealMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_MonopolyDealMessage); ok {
			return x.MonopolyDealMessage
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ServerMessage_RoomMessage struct {
	RoomMessage *ServerRoomMessage `protobuf:"bytes,10,opt,name=room_message,json=roomMessage,proto3,oneof"`
}

type ServerMessage_MonopolyDealMessage struct {
	MonopolyDealMessage *ServerMonopolyDealMessage `protobuf:"bytes,11,opt,name=monopoly_deal_message,json=monopolyDealMessage,proto3,oneof"`
}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_RoomMessage) isServerMessage_Payload() {}

func (*ServerMessage_MonopolyDealMessage) isServerMessage_Payload() {}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x0ffunkames.schema\x1a\x13monopoly_deal.proto\x1a\n" +
	"room.proto\"(\n" +
	"\x04Ping\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\"\xf2\x01\n" +
	"\rClientMessage\x12+\n" +
	"\x04ping\x18\x01 \x01(\v2\x15.funkames.schema.PingH\x00R\x04ping\x12G\n" +
	"\froom_message\x18\n" +
	" \x01(\v2\".funkames.schema.ClientRoomMessageH\x00R\vroomMessage\x12`\n" +
	"\x15monopoly_deal_message\x18\v \x01(\v2*.funkames.schema.ClientMonopolyDealMessageH\x00R\x13monopolyDealMessageB\t\n" +
	"\apayload\"\xf2\x01\n" +
	"\rServerMessage\x12+\n" +
	"\x04ping\x18\x01 \x01(\v2\x15.funkames.schema.PingH\x00R\x04ping\x12G\n" +
	"\froom_message\x18\n" +
	" \x01(\v2\".funkames.schema.ServerRoomMessageH\x00R\vroomMessage\x12`\n" +
	"\x15monopoly_deal_message\x18\v \x01(\v2*.funkames.schema.ServerMonopolyDealMessageH\x00R\x13monopolyDealMessageB\t\n" +
	"\apayloadB)Z'funkames/backend/internal/schema;schemab\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_proto_goTypes = []any{
	(*Ping)(nil),                      // 0: funkames.schema.Ping
	(*ClientMessage)(nil),             // 1: funkames.schema.ClientMessage
	(*ServerMessage)(nil),             // 2: funkames.schema.ServerMessage
	(*ClientRoomMessage)(nil),         // 3: funkames.schema.ClientRoomMessage
	(*ClientMonopolyDealMessage)(nil), // 4: funkames.schema.ClientMonopolyDealMessage
	(*ServerRoomMessage)(nil),         // 5: funkames.schema.ServerRoomMessage
	(*ServerMonopolyDealMessage)(nil), // 6: funkames.schema.ServerMonopolyDealMessage
}
var file_message_proto_depIdxs = []int32{
	0, // 0: funkames.schema.ClientMessage.ping:type_name -> funkames.schema.Ping
	3, // 1: funkames.schema.ClientMessage.room_message:type_name -> funkames.schema.ClientRoomMessage
	4, // 2: funkames.schema.ClientMessage.monopoly_deal_message:type_name -> funkames.schema.ClientMonopolyDealMessage
	0, // 3: funkames.schema.ServerMessage.ping:type_name -> funkames.schema.Ping
	5, // 4: funkames.schema.ServerMessage.room_message:type_name -> funkames.schema.ServerRoomMessage
	6, // 5: funkames.schema.ServerMessage.monopoly_deal_message:type_name -> funkames.schema.ServerMonopolyDealMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_monopoly_deal_proto_init()
	file_room_proto_init()
	file_message_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_RoomMessage)(nil),
		(*ClientMessage_MonopolyDealMessage)(nil),
	}
	file_message_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_RoomMessage)(nil),
		(*ServerMessage_MonopolyDealMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
