// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: monopoly_deal.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gameplay
type PurePropertyType int32

const (
	PurePropertyType_PURE_PROPERTY_TYPE_BROWN      PurePropertyType = 0
	PurePropertyType_PURE_PROPERTY_TYPE_LIGHT_BLUE PurePropertyType = 1
	PurePropertyType_PURE_PROPERTY_TYPE_PINK       PurePropertyType = 2
	PurePropertyType_PURE_PROPERTY_TYPE_ORANGE     PurePropertyType = 3
	PurePropertyType_PURE_PROPERTY_TYPE_RED        PurePropertyType = 4
	PurePropertyType_PURE_PROPERTY_TYPE_YELLOW     PurePropertyType = 5
	PurePropertyType_PURE_PROPERTY_TYPE_GREEN      PurePropertyType = 6
	PurePropertyType_PURE_PROPERTY_TYPE_DARK_BLUE  PurePropertyType = 7
	PurePropertyType_PURE_PROPERTY_TYPE_UTILITY    PurePropertyType = 8
	PurePropertyType_PURE_PROPERTY_TYPE_RAILROAD   PurePropertyType = 9
)

// Enum value maps for PurePropertyType.
var (
	PurePropertyType_name = map[int32]string{
		0: "PURE_PROPERTY_TYPE_BROWN",
		1: "PURE_PROPERTY_TYPE_LIGHT_BLUE",
		2: "PURE_PROPERTY_TYPE_PINK",
		3: "PURE_PROPERTY_TYPE_ORANGE",
		4: "PURE_PROPERTY_TYPE_RED",
		5: "PURE_PROPERTY_TYPE_YELLOW",
		6: "PURE_PROPERTY_TYPE_GREEN",
		7: "PURE_PROPERTY_TYPE_DARK_BLUE",
		8: "PURE_PROPERTY_TYPE_UTILITY",
		9: "PURE_PROPERTY_TYPE_RAILROAD",
	}
	PurePropertyType_value = map[string]int32{
		"PURE_PROPERTY_TYPE_BROWN":      0,
		"PURE_PROPERTY_TYPE_LIGHT_BLUE": 1,
		"PURE_PROPERTY_TYPE_PINK":       2,
		"PURE_PROPERTY_TYPE_ORANGE":     3,
		"PURE_PROPERTY_TYPE_RED":        4,
		"PURE_PROPERTY_TYPE_YELLOW":     5,
		"PURE_PROPERTY_TYPE_GREEN":      6,
		"PURE_PROPERTY_TYPE_DARK_BLUE":  7,
		"PURE_PROPERTY_TYPE_UTILITY":    8,
		"PURE_PROPERTY_TYPE_RAILROAD":   9,
	}
)

func (x PurePropertyType) Enum() *PurePropertyType {
	p := new(PurePropertyType)
	*p = x
	return p
}

func (x PurePropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurePropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[0].Descriptor()
}

func (PurePropertyType) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[0]
}

func (x PurePropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurePropertyType.Descriptor instead.
func (PurePropertyType) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

type WildPropertyType int32

const (
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_BROWN_LIGHT_BLUE   WildPropertyType = 0
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_LIGHT_BLUE_RAIROAD WildPropertyType = 1
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_PINK_ORANGE        WildPropertyType = 2
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_ORANGE_UTILITY     WildPropertyType = 3
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_GREEN_DARK_BLUE    WildPropertyType = 4
	WildPropertyType_WILD_PROPERTY_TYPE_WILRD_GREEN_RAILROAD    WildPropertyType = 5
	WildPropertyType_WILD_PROPERTY_TYPE_WILD_UTLITY_RAILROAD    WildPropertyType = 6
	WildPropertyType_WILD_PROPERTY_TYPE_WILD                    WildPropertyType = 7
)

// Enum value maps for WildPropertyType.
var (
	WildPropertyType_name = map[int32]string{
		0: "WILD_PROPERTY_TYPE_WILD_BROWN_LIGHT_BLUE",
		1: "WILD_PROPERTY_TYPE_WILD_LIGHT_BLUE_RAIROAD",
		2: "WILD_PROPERTY_TYPE_WILD_PINK_ORANGE",
		3: "WILD_PROPERTY_TYPE_WILD_ORANGE_UTILITY",
		4: "WILD_PROPERTY_TYPE_WILD_GREEN_DARK_BLUE",
		5: "WILD_PROPERTY_TYPE_WILRD_GREEN_RAILROAD",
		6: "WILD_PROPERTY_TYPE_WILD_UTLITY_RAILROAD",
		7: "WILD_PROPERTY_TYPE_WILD",
	}
	WildPropertyType_value = map[string]int32{
		"WILD_PROPERTY_TYPE_WILD_BROWN_LIGHT_BLUE":   0,
		"WILD_PROPERTY_TYPE_WILD_LIGHT_BLUE_RAIROAD": 1,
		"WILD_PROPERTY_TYPE_WILD_PINK_ORANGE":        2,
		"WILD_PROPERTY_TYPE_WILD_ORANGE_UTILITY":     3,
		"WILD_PROPERTY_TYPE_WILD_GREEN_DARK_BLUE":    4,
		"WILD_PROPERTY_TYPE_WILRD_GREEN_RAILROAD":    5,
		"WILD_PROPERTY_TYPE_WILD_UTLITY_RAILROAD":    6,
		"WILD_PROPERTY_TYPE_WILD":                    7,
	}
)

func (x WildPropertyType) Enum() *WildPropertyType {
	p := new(WildPropertyType)
	*p = x
	return p
}

func (x WildPropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WildPropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[1].Descriptor()
}

func (WildPropertyType) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[1]
}

func (x WildPropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WildPropertyType.Descriptor instead.
func (WildPropertyType) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

type MoneyType int32

const (
	MoneyType_MONEY_TYPE_1  MoneyType = 0
	MoneyType_MONEY_TYPE_2  MoneyType = 1
	MoneyType_MONEY_TYPE_3  MoneyType = 2
	MoneyType_MONEY_TYPE_4  MoneyType = 3
	MoneyType_MONEY_TYPE_5  MoneyType = 4
	MoneyType_MONEY_TYPE_10 MoneyType = 5
)

// Enum value maps for MoneyType.
var (
	MoneyType_name = map[int32]string{
		0: "MONEY_TYPE_1",
		1: "MONEY_TYPE_2",
		2: "MONEY_TYPE_3",
		3: "MONEY_TYPE_4",
		4: "MONEY_TYPE_5",
		5: "MONEY_TYPE_10",
	}
	MoneyType_value = map[string]int32{
		"MONEY_TYPE_1":  0,
		"MONEY_TYPE_2":  1,
		"MONEY_TYPE_3":  2,
		"MONEY_TYPE_4":  3,
		"MONEY_TYPE_5":  4,
		"MONEY_TYPE_10": 5,
	}
)

func (x MoneyType) Enum() *MoneyType {
	p := new(MoneyType)
	*p = x
	return p
}

func (x MoneyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoneyType) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[2].Descriptor()
}

func (MoneyType) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[2]
}

func (x MoneyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoneyType.Descriptor instead.
func (MoneyType) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_PASS_GO         ActionType = 0
	ActionType_ACTION_TYPE_DOUBLE_THE_RENT ActionType = 1
	ActionType_ACTION_TYPE_ITS_MY_BIRTHDAY ActionType = 2
	ActionType_ACTION_TYPE_HOUSE           ActionType = 3
	ActionType_ACTION_TYPE_SLY_DEAL        ActionType = 4
	ActionType_ACTION_TYPE_FORCED_DEAL     ActionType = 5
	ActionType_ACTION_TYPE_DEBT_COLLECTOR  ActionType = 6
	ActionType_ACTION_TYPE_HOTEL           ActionType = 7
	ActionType_ACTION_TYPE_JUST_SAY_NO     ActionType = 8
	ActionType_ACTION_TYPE_DEAL_BREAKER    ActionType = 9
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_PASS_GO",
		1: "ACTION_TYPE_DOUBLE_THE_RENT",
		2: "ACTION_TYPE_ITS_MY_BIRTHDAY",
		3: "ACTION_TYPE_HOUSE",
		4: "ACTION_TYPE_SLY_DEAL",
		5: "ACTION_TYPE_FORCED_DEAL",
		6: "ACTION_TYPE_DEBT_COLLECTOR",
		7: "ACTION_TYPE_HOTEL",
		8: "ACTION_TYPE_JUST_SAY_NO",
		9: "ACTION_TYPE_DEAL_BREAKER",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_PASS_GO":         0,
		"ACTION_TYPE_DOUBLE_THE_RENT": 1,
		"ACTION_TYPE_ITS_MY_BIRTHDAY": 2,
		"ACTION_TYPE_HOUSE":           3,
		"ACTION_TYPE_SLY_DEAL":        4,
		"ACTION_TYPE_FORCED_DEAL":     5,
		"ACTION_TYPE_DEBT_COLLECTOR":  6,
		"ACTION_TYPE_HOTEL":           7,
		"ACTION_TYPE_JUST_SAY_NO":     8,
		"ACTION_TYPE_DEAL_BREAKER":    9,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[3].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[3]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

type RentType int32

const (
	RentType_RENT_TYPE_BROWN_LIGHT_BLUE RentType = 0
	RentType_RENT_TYPE_PINK_ORANGE      RentType = 1
	RentType_RENT_TYPE_RED_YELLOW       RentType = 2
	RentType_RENT_TYPE_GREEN_DARK_BLUE  RentType = 3
	RentType_RENT_TYPE_UTILITY_RAILROAD RentType = 4
	RentType_RENT_TYPE_WILD             RentType = 5
)

// Enum value maps for RentType.
var (
	RentType_name = map[int32]string{
		0: "RENT_TYPE_BROWN_LIGHT_BLUE",
		1: "RENT_TYPE_PINK_ORANGE",
		2: "RENT_TYPE_RED_YELLOW",
		3: "RENT_TYPE_GREEN_DARK_BLUE",
		4: "RENT_TYPE_UTILITY_RAILROAD",
		5: "RENT_TYPE_WILD",
	}
	RentType_value = map[string]int32{
		"RENT_TYPE_BROWN_LIGHT_BLUE": 0,
		"RENT_TYPE_PINK_ORANGE":      1,
		"RENT_TYPE_RED_YELLOW":       2,
		"RENT_TYPE_GREEN_DARK_BLUE":  3,
		"RENT_TYPE_UTILITY_RAILROAD": 4,
		"RENT_TYPE_WILD":             5,
	}
)

func (x RentType) Enum() *RentType {
	p := new(RentType)
	*p = x
	return p
}

func (x RentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RentType) Descriptor() protoreflect.EnumDescriptor {
	return file_monopoly_deal_proto_enumTypes[4].Descriptor()
}

func (RentType) Type() protoreflect.EnumType {
	return &file_monopoly_deal_proto_enumTypes[4]
}

func (x RentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RentType.Descriptor instead.
func (RentType) EnumDescriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{4}
}

type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Card:
	//
	//	*Card_PureProperty
	//	*Card_WildProperty
	//	*Card_Money
	//	*Card_Action
	//	*Card_Rent
	Card          isCard_Card `protobuf_oneof:"card"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_monopoly_deal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetCard() isCard_Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *Card) GetPureProperty() PurePropertyType {
	if x != nil {
		if x, ok := x.Card.(*Card_PureProperty); ok {
			return x.PureProperty
		}
	}
	return PurePropertyType_PURE_PROPERTY_TYPE_BROWN
}

func (x *Card) GetWildProperty() WildPropertyType {
	if x != nil {
		if x, ok := x.Card.(*Card_WildProperty); ok {
			return x.WildProperty
		}
	}
	return WildPropertyType_WILD_PROPERTY_TYPE_WILD_BROWN_LIGHT_BLUE
}

func (x *Card) GetMoney() MoneyType {
	if x != nil {
		if x, ok := x.Card.(*Card_Money); ok {
			return x.Money
		}
	}
	return MoneyType_MONEY_TYPE_1
}

func (x *Card) GetAction() ActionType {
	if x != nil {
		if x, ok := x.Card.(*Card_Action); ok {
			return x.Action
		}
	}
	return ActionType_ACTION_TYPE_PASS_GO
}

func (x *Card) GetRent() RentType {
	if x != nil {
		if x, ok := x.Card.(*Card_Rent); ok {
			return x.Rent
		}
	}
	return RentType_RENT_TYPE_BROWN_LIGHT_BLUE
}

type isCard_Card interface {
	isCard_Card()
}

type Card_PureProperty struct {
	PureProperty PurePropertyType `protobuf:"varint,1,opt,name=pure_property,json=pureProperty,proto3,enum=funkames.schema.PurePropertyType,oneof"`
}

type Card_WildProperty struct {
	WildProperty WildPropertyType `protobuf:"varint,2,opt,name=wild_property,json=wildProperty,proto3,enum=funkames.schema.WildPropertyType,oneof"`
}

type Card_Money struct {
	Money MoneyType `protobuf:"varint,3,opt,name=money,proto3,enum=funkames.schema.MoneyType,oneof"`
}

type Card_Action struct {
	Action ActionType `protobuf:"varint,4,opt,name=action,proto3,enum=funkames.schema.ActionType,oneof"`
}

type Card_Rent struct {
	Rent RentType `protobuf:"varint,5,opt,name=rent,proto3,enum=funkames.schema.RentType,oneof"`
}

func (*Card_PureProperty) isCard_Card() {}

func (*Card_WildProperty) isCard_Card() {}

func (*Card_Money) isCard_Card() {}

func (*Card_Action) isCard_Card() {}

func (*Card_Rent) isCard_Card() {}

type PropertyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	PropertyName  *string                `protobuf:"bytes,2,opt,name=property_name,json=propertyName,proto3,oneof" json:"property_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyType) Reset() {
	*x = PropertyType{}
	mi := &file_monopoly_deal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyType) ProtoMessage() {}

func (x *PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyType.ProtoReflect.Descriptor instead.
func (*PropertyType) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyType) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PropertyType) GetPropertyName() string {
	if x != nil && x.PropertyName != nil {
		return *x.PropertyName
	}
	return ""
}

type PropertySetType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyTypes []*PropertyType        `protobuf:"bytes,1,rep,name=property_types,json=propertyTypes,proto3" json:"property_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySetType) Reset() {
	*x = PropertySetType{}
	mi := &file_monopoly_deal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySetType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySetType) ProtoMessage() {}

func (x *PropertySetType) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySetType.ProtoReflect.Descriptor instead.
func (*PropertySetType) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{2}
}

func (x *PropertySetType) GetPropertyTypes() []*PropertyType {
	if x != nil {
		return x.PropertyTypes
	}
	return nil
}

type PlayProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Property      *PropertyType          `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayProperty) Reset() {
	*x = PlayProperty{}
	mi := &file_monopoly_deal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayProperty) ProtoMessage() {}

func (x *PlayProperty) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayProperty.ProtoReflect.Descriptor instead.
func (*PlayProperty) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{3}
}

func (x *PlayProperty) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayProperty) GetProperty() *PropertyType {
	if x != nil {
		return x.Property
	}
	return nil
}

type PlayMoney struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoney) Reset() {
	*x = PlayMoney{}
	mi := &file_monopoly_deal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoney) ProtoMessage() {}

func (x *PlayMoney) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoney.ProtoReflect.Descriptor instead.
func (*PlayMoney) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{4}
}

func (x *PlayMoney) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayMoney) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

// pass go loop
type PassGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassGo) Reset() {
	*x = PassGo{}
	mi := &file_monopoly_deal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassGo) ProtoMessage() {}

func (x *PassGo) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassGo.ProtoReflect.Descriptor instead.
func (*PassGo) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{5}
}

func (x *PassGo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PassGoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassGoResponse) Reset() {
	*x = PassGoResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassGoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassGoResponse) ProtoMessage() {}

func (x *PassGoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassGoResponse.ProtoReflect.Descriptor instead.
func (*PassGoResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{6}
}

func (x *PassGoResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PassGoResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type DoubleTheRent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleTheRent) Reset() {
	*x = DoubleTheRent{}
	mi := &file_monopoly_deal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleTheRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleTheRent) ProtoMessage() {}

func (x *DoubleTheRent) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleTheRent.ProtoReflect.Descriptor instead.
func (*DoubleTheRent) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{7}
}

func (x *DoubleTheRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// its my birthday loop
type ItsMyBirthday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItsMyBirthday) Reset() {
	*x = ItsMyBirthday{}
	mi := &file_monopoly_deal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItsMyBirthday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItsMyBirthday) ProtoMessage() {}

func (x *ItsMyBirthday) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItsMyBirthday.ProtoReflect.Descriptor instead.
func (*ItsMyBirthday) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{8}
}

func (x *ItsMyBirthday) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ItsMyBirthdayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	SaidNo        bool                   `protobuf:"varint,3,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItsMyBirthdayResponse) Reset() {
	*x = ItsMyBirthdayResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItsMyBirthdayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItsMyBirthdayResponse) ProtoMessage() {}

func (x *ItsMyBirthdayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItsMyBirthdayResponse.ProtoReflect.Descriptor instead.
func (*ItsMyBirthdayResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{9}
}

func (x *ItsMyBirthdayResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ItsMyBirthdayResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ItsMyBirthdayResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type House struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySetType       `protobuf:"bytes,2,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *House) Reset() {
	*x = House{}
	mi := &file_monopoly_deal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *House) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*House) ProtoMessage() {}

func (x *House) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use House.ProtoReflect.Descriptor instead.
func (*House) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{10}
}

func (x *House) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *House) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type SlyDeal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Property       *PropertyType          `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlyDeal) Reset() {
	*x = SlyDeal{}
	mi := &file_monopoly_deal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlyDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlyDeal) ProtoMessage() {}

func (x *SlyDeal) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlyDeal.ProtoReflect.Descriptor instead.
func (*SlyDeal) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{11}
}

func (x *SlyDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SlyDeal) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *SlyDeal) GetProperty() *PropertyType {
	if x != nil {
		return x.Property
	}
	return nil
}

type SlyDealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlyDealResponse) Reset() {
	*x = SlyDealResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlyDealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlyDealResponse) ProtoMessage() {}

func (x *SlyDealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlyDealResponse.ProtoReflect.Descriptor instead.
func (*SlyDealResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{12}
}

func (x *SlyDealResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SlyDealResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type ForcedDeal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	SourceProperty *PropertyType          `protobuf:"bytes,3,opt,name=source_property,json=sourceProperty,proto3" json:"source_property,omitempty"`
	TargetProperty *PropertyType          `protobuf:"bytes,4,opt,name=target_property,json=targetProperty,proto3" json:"target_property,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForcedDeal) Reset() {
	*x = ForcedDeal{}
	mi := &file_monopoly_deal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForcedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcedDeal) ProtoMessage() {}

func (x *ForcedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcedDeal.ProtoReflect.Descriptor instead.
func (*ForcedDeal) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{13}
}

func (x *ForcedDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ForcedDeal) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *ForcedDeal) GetSourceProperty() *PropertyType {
	if x != nil {
		return x.SourceProperty
	}
	return nil
}

func (x *ForcedDeal) GetTargetProperty() *PropertyType {
	if x != nil {
		return x.TargetProperty
	}
	return nil
}

type ForcedDealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForcedDealResponse) Reset() {
	*x = ForcedDealResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForcedDealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcedDealResponse) ProtoMessage() {}

func (x *ForcedDealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcedDealResponse.ProtoReflect.Descriptor instead.
func (*ForcedDealResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{14}
}

func (x *ForcedDealResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ForcedDealResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type DebtCollector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DebtCollector) Reset() {
	*x = DebtCollector{}
	mi := &file_monopoly_deal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtCollector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtCollector) ProtoMessage() {}

func (x *DebtCollector) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtCollector.ProtoReflect.Descriptor instead.
func (*DebtCollector) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{15}
}

func (x *DebtCollector) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DebtCollector) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

type DebtCollectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	SaidNo        bool                   `protobuf:"varint,3,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebtCollectorResponse) Reset() {
	*x = DebtCollectorResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebtCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebtCollectorResponse) ProtoMessage() {}

func (x *DebtCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebtCollectorResponse.ProtoReflect.Descriptor instead.
func (*DebtCollectorResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{16}
}

func (x *DebtCollectorResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DebtCollectorResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *DebtCollectorResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type Hotel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySetType       `protobuf:"bytes,2,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_monopoly_deal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{17}
}

func (x *Hotel) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Hotel) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type JustSayNoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JustSayNoResponse) Reset() {
	*x = JustSayNoResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JustSayNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JustSayNoResponse) ProtoMessage() {}

func (x *JustSayNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JustSayNoResponse.ProtoReflect.Descriptor instead.
func (*JustSayNoResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{18}
}

func (x *JustSayNoResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JustSayNoResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type DealBreaker struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	PropertySet    *PropertySetType       `protobuf:"bytes,3,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DealBreaker) Reset() {
	*x = DealBreaker{}
	mi := &file_monopoly_deal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreaker) ProtoMessage() {}

func (x *DealBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreaker.ProtoReflect.Descriptor instead.
func (*DealBreaker) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{19}
}

func (x *DealBreaker) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DealBreaker) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *DealBreaker) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type DealBreakerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealBreakerResponse) Reset() {
	*x = DealBreakerResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreakerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreakerResponse) ProtoMessage() {}

func (x *DealBreakerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreakerResponse.ProtoReflect.Descriptor instead.
func (*DealBreakerResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{20}
}

func (x *DealBreakerResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DealBreakerResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type Rent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rent) Reset() {
	*x = Rent{}
	mi := &file_monopoly_deal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rent) ProtoMessage() {}

func (x *Rent) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rent.ProtoReflect.Descriptor instead.
func (*Rent) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{21}
}

func (x *Rent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Rent) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type RentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	SaidNo        bool                   `protobuf:"varint,3,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentResponse) Reset() {
	*x = RentResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentResponse) ProtoMessage() {}

func (x *RentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentResponse.ProtoReflect.Descriptor instead.
func (*RentResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{22}
}

func (x *RentResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RentResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *RentResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

// TODO
type WildRent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WildRent) Reset() {
	*x = WildRent{}
	mi := &file_monopoly_deal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildRent) ProtoMessage() {}

func (x *WildRent) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildRent.ProtoReflect.Descriptor instead.
func (*WildRent) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{23}
}

func (x *WildRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WildRent) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

type WildRentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	SaidNo        bool                   `protobuf:"varint,3,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WildRentResponse) Reset() {
	*x = WildRentResponse{}
	mi := &file_monopoly_deal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildRentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildRentResponse) ProtoMessage() {}

func (x *WildRentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildRentResponse.ProtoReflect.Descriptor instead.
func (*WildRentResponse) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{24}
}

func (x *WildRentResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *WildRentResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *WildRentResponse) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type ClientMonopolyDealMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMonopolyDealMessage) Reset() {
	*x = ClientMonopolyDealMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMonopolyDealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMonopolyDealMessage) ProtoMessage() {}

func (x *ClientMonopolyDealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMonopolyDealMessage.ProtoReflect.Descriptor instead.
func (*ClientMonopolyDealMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{25}
}

type ServerMonopolyDealMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMonopolyDealMessage) Reset() {
	*x = ServerMonopolyDealMessage{}
	mi := &file_monopoly_deal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMonopolyDealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMonopolyDealMessage) ProtoMessage() {}

func (x *ServerMonopolyDealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monopoly_deal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMonopolyDealMessage.ProtoReflect.Descriptor instead.
func (*ServerMonopolyDealMessage) Descriptor() ([]byte, []int) {
	return file_monopoly_deal_proto_rawDescGZIP(), []int{26}
}

var File_monopoly_deal_proto protoreflect.FileDescriptor

const file_monopoly_deal_proto_rawDesc = "" +
	"\n" +
	"\x13monopoly_deal.proto\x12\x0ffunkames.schema\"\xbe\x02\n" +
	"\x04Card\x12H\n" +
	"\rpure_property\x18\x01 \x01(\x0e2!.funkames.schema.PurePropertyTypeH\x00R\fpureProperty\x12H\n" +
	"\rwild_property\x18\x02 \x01(\x0e2!.funkames.schema.WildPropertyTypeH\x00R\fwildProperty\x122\n" +
	"\x05money\x18\x03 \x01(\x0e2\x1a.funkames.schema.MoneyTypeH\x00R\x05money\x125\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1b.funkames.schema.ActionTypeH\x00R\x06action\x12/\n" +
	"\x04rent\x18\x05 \x01(\x0e2\x19.funkames.schema.RentTypeH\x00R\x04rentB\x06\n" +
	"\x04card\"u\n" +
	"\fPropertyType\x12)\n" +
	"\x04card\x18\x01 \x01(\v2\x15.funkames.schema.CardR\x04card\x12(\n" +
	"\rproperty_name\x18\x02 \x01(\tH\x00R\fpropertyName\x88\x01\x01B\x10\n" +
	"\x0e_property_name\"W\n" +
	"\x0fPropertySetType\x12D\n" +
	"\x0eproperty_types\x18\x01 \x03(\v2\x1d.funkames.schema.PropertyTypeR\rpropertyTypes\"f\n" +
	"\fPlayProperty\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x129\n" +
	"\bproperty\x18\x02 \x01(\v2\x1d.funkames.schema.PropertyTypeR\bproperty\"S\n" +
	"\tPlayMoney\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12)\n" +
	"\x04card\x18\x02 \x01(\v2\x15.funkames.schema.CardR\x04card\"%\n" +
	"\x06PassGo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"Z\n" +
	"\x0ePassGoResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05cards\x18\x02 \x03(\v2\x15.funkames.schema.CardR\x05cards\",\n" +
	"\rDoubleTheRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\",\n" +
	"\rItsMyBirthday\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"z\n" +
	"\x15ItsMyBirthdayResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05cards\x18\x02 \x03(\v2\x15.funkames.schema.CardR\x05cards\x12\x17\n" +
	"\asaid_no\x18\x03 \x01(\bR\x06saidNo\"i\n" +
	"\x05House\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12C\n" +
	"\fproperty_set\x18\x02 \x01(\v2 .funkames.schema.PropertySetTypeR\vpropertySet\"\x8b\x01\n" +
	"\aSlyDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x129\n" +
	"\bproperty\x18\x03 \x01(\v2\x1d.funkames.schema.PropertyTypeR\bproperty\"G\n" +
	"\x0fSlyDealResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"\xe3\x01\n" +
	"\n" +
	"ForcedDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x12F\n" +
	"\x0fsource_property\x18\x03 \x01(\v2\x1d.funkames.schema.PropertyTypeR\x0esourceProperty\x12F\n" +
	"\x0ftarget_property\x18\x04 \x01(\v2\x1d.funkames.schema.PropertyTypeR\x0etargetProperty\"J\n" +
	"\x12ForcedDealResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"V\n" +
	"\rDebtCollector\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\"z\n" +
	"\x15DebtCollectorResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05cards\x18\x02 \x03(\v2\x15.funkames.schema.CardR\x05cards\x12\x17\n" +
	"\asaid_no\x18\x03 \x01(\bR\x06saidNo\"i\n" +
	"\x05Hotel\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12C\n" +
	"\fproperty_set\x18\x02 \x01(\v2 .funkames.schema.PropertySetTypeR\vpropertySet\"I\n" +
	"\x11JustSayNoResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"\x99\x01\n" +
	"\vDealBreaker\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x12C\n" +
	"\fproperty_set\x18\x03 \x01(\v2 .funkames.schema.PropertySetTypeR\vpropertySet\"K\n" +
	"\x13DealBreakerResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"N\n" +
	"\x04Rent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12)\n" +
	"\x04card\x18\x02 \x01(\v2\x15.funkames.schema.CardR\x04card\"q\n" +
	"\fRentResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05cards\x18\x02 \x03(\v2\x15.funkames.schema.CardR\x05cards\x12\x17\n" +
	"\asaid_no\x18\x03 \x01(\bR\x06saidNo\"Q\n" +
	"\bWildRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\"u\n" +
	"\x10WildRentResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05cards\x18\x02 \x03(\v2\x15.funkames.schema.CardR\x05cards\x12\x17\n" +
	"\asaid_no\x18\x03 \x01(\bR\x06saidNo\"\x1b\n" +
	"\x19ClientMonopolyDealMessage\"\x1b\n" +
	"\x19ServerMonopolyDealMessage*\xcb\x02\n" +
	"\x10PurePropertyType\x12\x1c\n" +
	"\x18PURE_PROPERTY_TYPE_BROWN\x10\x00\x12!\n" +
	"\x1dPURE_PROPERTY_TYPE_LIGHT_BLUE\x10\x01\x12\x1b\n" +
	"\x17PURE_PROPERTY_TYPE_PINK\x10\x02\x12\x1d\n" +
	"\x19PURE_PROPERTY_TYPE_ORANGE\x10\x03\x12\x1a\n" +
	"\x16PURE_PROPERTY_TYPE_RED\x10\x04\x12\x1d\n" +
	"\x19PURE_PROPERTY_TYPE_YELLOW\x10\x05\x12\x1c\n" +
	"\x18PURE_PROPERTY_TYPE_GREEN\x10\x06\x12 \n" +
	"\x1cPURE_PROPERTY_TYPE_DARK_BLUE\x10\a\x12\x1e\n" +
	"\x1aPURE_PROPERTY_TYPE_UTILITY\x10\b\x12\x1f\n" +
	"\x1bPURE_PROPERTY_TYPE_RAILROAD\x10\t*\xe9\x02\n" +
	"\x10WildPropertyType\x12,\n" +
	"(WILD_PROPERTY_TYPE_WILD_BROWN_LIGHT_BLUE\x10\x00\x12.\n" +
	"*WILD_PROPERTY_TYPE_WILD_LIGHT_BLUE_RAIROAD\x10\x01\x12'\n" +
	"#WILD_PROPERTY_TYPE_WILD_PINK_ORANGE\x10\x02\x12*\n" +
	"&WILD_PROPERTY_TYPE_WILD_ORANGE_UTILITY\x10\x03\x12+\n" +
	"'WILD_PROPERTY_TYPE_WILD_GREEN_DARK_BLUE\x10\x04\x12+\n" +
	"'WILD_PROPERTY_TYPE_WILRD_GREEN_RAILROAD\x10\x05\x12+\n" +
	"'WILD_PROPERTY_TYPE_WILD_UTLITY_RAILROAD\x10\x06\x12\x1b\n" +
	"\x17WILD_PROPERTY_TYPE_WILD\x10\a*x\n" +
	"\tMoneyType\x12\x10\n" +
	"\fMONEY_TYPE_1\x10\x00\x12\x10\n" +
	"\fMONEY_TYPE_2\x10\x01\x12\x10\n" +
	"\fMONEY_TYPE_3\x10\x02\x12\x10\n" +
	"\fMONEY_TYPE_4\x10\x03\x12\x10\n" +
	"\fMONEY_TYPE_5\x10\x04\x12\x11\n" +
	"\rMONEY_TYPE_10\x10\x05*\xa7\x02\n" +
	"\n" +
	"ActionType\x12\x17\n" +
	"\x13ACTION_TYPE_PASS_GO\x10\x00\x12\x1f\n" +
	"\x1bACTION_TYPE_DOUBLE_THE_RENT\x10\x01\x12\x1f\n" +
	"\x1bACTION_TYPE_ITS_MY_BIRTHDAY\x10\x02\x12\x15\n" +
	"\x11ACTION_TYPE_HOUSE\x10\x03\x12\x18\n" +
	"\x14ACTION_TYPE_SLY_DEAL\x10\x04\x12\x1b\n" +
	"\x17ACTION_TYPE_FORCED_DEAL\x10\x05\x12\x1e\n" +
	"\x1aACTION_TYPE_DEBT_COLLECTOR\x10\x06\x12\x15\n" +
	"\x11ACTION_TYPE_HOTEL\x10\a\x12\x1b\n" +
	"\x17ACTION_TYPE_JUST_SAY_NO\x10\b\x12\x1c\n" +
	"\x18ACTION_TYPE_DEAL_BREAKER\x10\t*\xb2\x01\n" +
	"\bRentType\x12\x1e\n" +
	"\x1aRENT_TYPE_BROWN_LIGHT_BLUE\x10\x00\x12\x19\n" +
	"\x15RENT_TYPE_PINK_ORANGE\x10\x01\x12\x18\n" +
	"\x14RENT_TYPE_RED_YELLOW\x10\x02\x12\x1d\n" +
	"\x19RENT_TYPE_GREEN_DARK_BLUE\x10\x03\x12\x1e\n" +
	"\x1aRENT_TYPE_UTILITY_RAILROAD\x10\x04\x12\x12\n" +
	"\x0eRENT_TYPE_WILD\x10\x05B)Z'funkames/backend/internal/schema;schemab\x06proto3"

var (
	file_monopoly_deal_proto_rawDescOnce sync.Once
	file_monopoly_deal_proto_rawDescData []byte
)

func file_monopoly_deal_proto_rawDescGZIP() []byte {
	file_monopoly_deal_proto_rawDescOnce.Do(func() {
		file_monopoly_deal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)))
	})
	return file_monopoly_deal_proto_rawDescData
}

var file_monopoly_deal_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_monopoly_deal_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_monopoly_deal_proto_goTypes = []any{
	(PurePropertyType)(0),             // 0: funkames.schema.PurePropertyType
	(WildPropertyType)(0),             // 1: funkames.schema.WildPropertyType
	(MoneyType)(0),                    // 2: funkames.schema.MoneyType
	(ActionType)(0),                   // 3: funkames.schema.ActionType
	(RentType)(0),                     // 4: funkames.schema.RentType
	(*Card)(nil),                      // 5: funkames.schema.Card
	(*PropertyType)(nil),              // 6: funkames.schema.PropertyType
	(*PropertySetType)(nil),           // 7: funkames.schema.PropertySetType
	(*PlayProperty)(nil),              // 8: funkames.schema.PlayProperty
	(*PlayMoney)(nil),                 // 9: funkames.schema.PlayMoney
	(*PassGo)(nil),                    // 10: funkames.schema.PassGo
	(*PassGoResponse)(nil),            // 11: funkames.schema.PassGoResponse
	(*DoubleTheRent)(nil),             // 12: funkames.schema.DoubleTheRent
	(*ItsMyBirthday)(nil),             // 13: funkames.schema.ItsMyBirthday
	(*ItsMyBirthdayResponse)(nil),     // 14: funkames.schema.ItsMyBirthdayResponse
	(*House)(nil),                     // 15: funkames.schema.House
	(*SlyDeal)(nil),                   // 16: funkames.schema.SlyDeal
	(*SlyDealResponse)(nil),           // 17: funkames.schema.SlyDealResponse
	(*ForcedDeal)(nil),                // 18: funkames.schema.ForcedDeal
	(*ForcedDealResponse)(nil),        // 19: funkames.schema.ForcedDealResponse
	(*DebtCollector)(nil),             // 20: funkames.schema.DebtCollector
	(*DebtCollectorResponse)(nil),     // 21: funkames.schema.DebtCollectorResponse
	(*Hotel)(nil),                     // 22: funkames.schema.Hotel
	(*JustSayNoResponse)(nil),         // 23: funkames.schema.JustSayNoResponse
	(*DealBreaker)(nil),               // 24: funkames.schema.DealBreaker
	(*DealBreakerResponse)(nil),       // 25: funkames.schema.DealBreakerResponse
	(*Rent)(nil),                      // 26: funkames.schema.Rent
	(*RentResponse)(nil),              // 27: funkames.schema.RentResponse
	(*WildRent)(nil),                  // 28: funkames.schema.WildRent
	(*WildRentResponse)(nil),          // 29: funkames.schema.WildRentResponse
	(*ClientMonopolyDealMessage)(nil), // 30: funkames.schema.ClientMonopolyDealMessage
	(*ServerMonopolyDealMessage)(nil), // 31: funkames.schema.ServerMonopolyDealMessage
}
var file_monopoly_deal_proto_depIdxs = []int32{
	0,  // 0: funkames.schema.Card.pure_property:type_name -> funkames.schema.PurePropertyType
	1,  // 1: funkames.schema.Card.wild_property:type_name -> funkames.schema.WildPropertyType
	2,  // 2: funkames.schema.Card.money:type_name -> funkames.schema.MoneyType
	3,  // 3: funkames.schema.Card.action:type_name -> funkames.schema.ActionType
	4,  // 4: funkames.schema.Card.rent:type_name -> funkames.schema.RentType
	5,  // 5: funkames.schema.PropertyType.card:type_name -> funkames.schema.Card
	6,  // 6: funkames.schema.PropertySetType.property_types:type_name -> funkames.schema.PropertyType
	6,  // 7: funkames.schema.PlayProperty.property:type_name -> funkames.schema.PropertyType
	5,  // 8: funkames.schema.PlayMoney.card:type_name -> funkames.schema.Card
	5,  // 9: funkames.schema.PassGoResponse.cards:type_name -> funkames.schema.Card
	5,  // 10: funkames.schema.ItsMyBirthdayResponse.cards:type_name -> funkames.schema.Card
	7,  // 11: funkames.schema.House.property_set:type_name -> funkames.schema.PropertySetType
	6,  // 12: funkames.schema.SlyDeal.property:type_name -> funkames.schema.PropertyType
	6,  // 13: funkames.schema.ForcedDeal.source_property:type_name -> funkames.schema.PropertyType
	6,  // 14: funkames.schema.ForcedDeal.target_property:type_name -> funkames.schema.PropertyType
	5,  // 15: funkames.schema.DebtCollectorResponse.cards:type_name -> funkames.schema.Card
	7,  // 16: funkames.schema.Hotel.property_set:type_name -> funkames.schema.PropertySetType
	7,  // 17: funkames.schema.DealBreaker.property_set:type_name -> funkames.schema.PropertySetType
	5,  // 18: funkames.schema.Rent.card:type_name -> funkames.schema.Card
	5,  // 19: funkames.schema.RentResponse.cards:type_name -> funkames.schema.Card
	5,  // 20: funkames.schema.WildRentResponse.cards:type_name -> funkames.schema.Card
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_monopoly_deal_proto_init() }
func file_monopoly_deal_proto_init() {
	if File_monopoly_deal_proto != nil {
		return
	}
	file_monopoly_deal_proto_msgTypes[0].OneofWrappers = []any{
		(*Card_PureProperty)(nil),
		(*Card_WildProperty)(nil),
		(*Card_Money)(nil),
		(*Card_Action)(nil),
		(*Card_Rent)(nil),
	}
	file_monopoly_deal_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monopoly_deal_proto_rawDesc), len(file_monopoly_deal_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monopoly_deal_proto_goTypes,
		DependencyIndexes: file_monopoly_deal_proto_depIdxs,
		EnumInfos:         file_monopoly_deal_proto_enumTypes,
		MessageInfos:      file_monopoly_deal_proto_msgTypes,
	}.Build()
	File_monopoly_deal_proto = out.File
	file_monopoly_deal_proto_goTypes = nil
	file_monopoly_deal_proto_depIdxs = nil
}
