// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: room.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game int32

const (
	Game_MonopolyDeal Game = 0
)

// Enum value maps for Game.
var (
	Game_name = map[int32]string{
		0: "MonopolyDeal",
	}
	Game_value = map[string]int32{
		"MonopolyDeal": 0,
	}
)

func (x Game) Enum() *Game {
	p := new(Game)
	*p = x
	return p
}

func (x Game) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (Game) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x Game) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game.Descriptor instead.
func (Game) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsReady       bool                   `protobuf:"varint,4,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	IsHost        bool                   `protobuf:"varint,5,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Player) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Player) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

func (x *Player) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Occupied      int32                  `protobuf:"varint,5,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Game          Game                   `protobuf:"varint,6,opt,name=game,proto3,enum=funkames.schema.Game" json:"game,omitempty"`
	Settings      string                 `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Room) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Room) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Room) GetOccupied() int32 {
	if x != nil {
		return x.Occupied
	}
	return 0
}

func (x *Room) GetGame() Game {
	if x != nil {
		return x.Game
	}
	return Game_MonopolyDeal
}

func (x *Room) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type RoomCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreated) Reset() {
	*x = RoomCreated{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreated) ProtoMessage() {}

func (x *RoomCreated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreated.ProtoReflect.Descriptor instead.
func (*RoomCreated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomCreated) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type PlayerJoinedRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player        *Player                `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinedRoom) Reset() {
	*x = PlayerJoinedRoom{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedRoom) ProtoMessage() {}

func (x *PlayerJoinedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedRoom.ProtoReflect.Descriptor instead.
func (*PlayerJoinedRoom) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerJoinedRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerJoinedRoom) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerLeftRoom struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayedId        string                 `protobuf:"bytes,2,opt,name=played_id,json=playedId,proto3" json:"played_id,omitempty"`
	NewHostPlayerId *string                `protobuf:"bytes,3,opt,name=new_host_player_id,json=newHostPlayerId,proto3,oneof" json:"new_host_player_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerLeftRoom) Reset() {
	*x = PlayerLeftRoom{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftRoom) ProtoMessage() {}

func (x *PlayerLeftRoom) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftRoom.ProtoReflect.Descriptor instead.
func (*PlayerLeftRoom) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerLeftRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerLeftRoom) GetPlayedId() string {
	if x != nil {
		return x.PlayedId
	}
	return ""
}

func (x *PlayerLeftRoom) GetNewHostPlayerId() string {
	if x != nil && x.NewHostPlayerId != nil {
		return *x.NewHostPlayerId
	}
	return ""
}

type RoomDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDeleted) Reset() {
	*x = RoomDeleted{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDeleted) ProtoMessage() {}

func (x *RoomDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDeleted.ProtoReflect.Descriptor instead.
func (*RoomDeleted) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomDeleted) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *Chat) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ChatReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReceived) Reset() {
	*x = ChatReceived{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReceived) ProtoMessage() {}

func (x *ChatReceived) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReceived.ProtoReflect.Descriptor instead.
func (*ChatReceived) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *ChatReceived) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatReceived) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type PlayerToggledReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsReady       bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerToggledReady) Reset() {
	*x = PlayerToggledReady{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerToggledReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerToggledReady) ProtoMessage() {}

func (x *PlayerToggledReady) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerToggledReady.ProtoReflect.Descriptor instead.
func (*PlayerToggledReady) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerToggledReady) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerToggledReady) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type SettingsUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Game          Game                   `protobuf:"varint,2,opt,name=game,proto3,enum=funkames.schema.Game" json:"game,omitempty"`
	Settings      string                 `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsUpdated) Reset() {
	*x = SettingsUpdated{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsUpdated) ProtoMessage() {}

func (x *SettingsUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsUpdated.ProtoReflect.Descriptor instead.
func (*SettingsUpdated) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *SettingsUpdated) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *SettingsUpdated) GetGame() Game {
	if x != nil {
		return x.Game
	}
	return Game_MonopolyDeal
}

func (x *SettingsUpdated) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type ServerRoomMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerRoomMessage_RoomCreated
	//	*ServerRoomMessage_PlayerJoinedRoom
	//	*ServerRoomMessage_PlayerLeftRoom
	//	*ServerRoomMessage_ChatReceived
	//	*ServerRoomMessage_PlayerToggledReady
	//	*ServerRoomMessage_SettingsUpdated
	Payload       isServerRoomMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRoomMessage) Reset() {
	*x = ServerRoomMessage{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRoomMessage) ProtoMessage() {}

func (x *ServerRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRoomMessage.ProtoReflect.Descriptor instead.
func (*ServerRoomMessage) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *ServerRoomMessage) GetPayload() isServerRoomMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerRoomMessage) GetRoomCreated() *RoomCreated {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_RoomCreated); ok {
			return x.RoomCreated
		}
	}
	return nil
}

func (x *ServerRoomMessage) GetPlayerJoinedRoom() *PlayerJoinedRoom {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_PlayerJoinedRoom); ok {
			return x.PlayerJoinedRoom
		}
	}
	return nil
}

func (x *ServerRoomMessage) GetPlayerLeftRoom() *PlayerLeftRoom {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_PlayerLeftRoom); ok {
			return x.PlayerLeftRoom
		}
	}
	return nil
}

func (x *ServerRoomMessage) GetChatReceived() *ChatReceived {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_ChatReceived); ok {
			return x.ChatReceived
		}
	}
	return nil
}

func (x *ServerRoomMessage) GetPlayerToggledReady() *PlayerToggledReady {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_PlayerToggledReady); ok {
			return x.PlayerToggledReady
		}
	}
	return nil
}

func (x *ServerRoomMessage) GetSettingsUpdated() *SettingsUpdated {
	if x != nil {
		if x, ok := x.Payload.(*ServerRoomMessage_SettingsUpdated); ok {
			return x.SettingsUpdated
		}
	}
	return nil
}

type isServerRoomMessage_Payload interface {
	isServerRoomMessage_Payload()
}

type ServerRoomMessage_RoomCreated struct {
	RoomCreated *RoomCreated `protobuf:"bytes,1,opt,name=room_created,json=roomCreated,proto3,oneof"`
}

type ServerRoomMessage_PlayerJoinedRoom struct {
	PlayerJoinedRoom *PlayerJoinedRoom `protobuf:"bytes,2,opt,name=player_joined_room,json=playerJoinedRoom,proto3,oneof"`
}

type ServerRoomMessage_PlayerLeftRoom struct {
	PlayerLeftRoom *PlayerLeftRoom `protobuf:"bytes,3,opt,name=player_left_room,json=playerLeftRoom,proto3,oneof"`
}

type ServerRoomMessage_ChatReceived struct {
	ChatReceived *ChatReceived `protobuf:"bytes,4,opt,name=chat_received,json=chatReceived,proto3,oneof"`
}

type ServerRoomMessage_PlayerToggledReady struct {
	PlayerToggledReady *PlayerToggledReady `protobuf:"bytes,5,opt,name=player_toggled_ready,json=playerToggledReady,proto3,oneof"`
}

type ServerRoomMessage_SettingsUpdated struct {
	SettingsUpdated *SettingsUpdated `protobuf:"bytes,6,opt,name=settings_updated,json=settingsUpdated,proto3,oneof"`
}

func (*ServerRoomMessage_RoomCreated) isServerRoomMessage_Payload() {}

func (*ServerRoomMessage_PlayerJoinedRoom) isServerRoomMessage_Payload() {}

func (*ServerRoomMessage_PlayerLeftRoom) isServerRoomMessage_Payload() {}

func (*ServerRoomMessage_ChatReceived) isServerRoomMessage_Payload() {}

func (*ServerRoomMessage_PlayerToggledReady) isServerRoomMessage_Payload() {}

func (*ServerRoomMessage_SettingsUpdated) isServerRoomMessage_Payload() {}

type ClientRoomMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientRoomMessage_Chat
	Payload       isClientRoomMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRoomMessage) Reset() {
	*x = ClientRoomMessage{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRoomMessage) ProtoMessage() {}

func (x *ClientRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRoomMessage.ProtoReflect.Descriptor instead.
func (*ClientRoomMessage) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *ClientRoomMessage) GetPayload() isClientRoomMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientRoomMessage) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Payload.(*ClientRoomMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isClientRoomMessage_Payload interface {
	isClientRoomMessage_Payload()
}

type ClientRoomMessage_Chat struct {
	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

func (*ClientRoomMessage_Chat) isClientRoomMessage_Payload() {}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x0ffunkames.schema\"\xb8\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bis_ready\x18\x04 \x01(\bR\aisReady\x12\x17\n" +
	"\ais_host\x18\x05 \x01(\bR\x06isHost\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\x03R\bjoinedAt\"\xf4\x01\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x121\n" +
	"\aplayers\x18\x03 \x03(\v2\x17.funkames.schema.PlayerR\aplayers\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1a\n" +
	"\boccupied\x18\x05 \x01(\x05R\boccupied\x12)\n" +
	"\x04game\x18\x06 \x01(\x0e2\x15.funkames.schema.GameR\x04game\x12\x1a\n" +
	"\bsettings\x18\a \x01(\tR\bsettings\"8\n" +
	"\vRoomCreated\x12)\n" +
	"\x04room\x18\x01 \x01(\v2\x15.funkames.schema.RoomR\x04room\"\\\n" +
	"\x10PlayerJoinedRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12/\n" +
	"\x06player\x18\x02 \x01(\v2\x17.funkames.schema.PlayerR\x06player\"\x8f\x01\n" +
	"\x0ePlayerLeftRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayed_id\x18\x02 \x01(\tR\bplayedId\x120\n" +
	"\x12new_host_player_id\x18\x03 \x01(\tH\x00R\x0fnewHostPlayerId\x88\x01\x01B\x15\n" +
	"\x13_new_host_player_id\"&\n" +
	"\vRoomDeleted\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\" \n" +
	"\x04Chat\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"E\n" +
	"\fChatReceived\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"L\n" +
	"\x12PlayerToggledReady\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady\"t\n" +
	"\x0fSettingsUpdated\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x12)\n" +
	"\x04game\x18\x02 \x01(\x0e2\x15.funkames.schema.GameR\x04game\x12\x1a\n" +
	"\bsettings\x18\x03 \x01(\tR\bsettings\"\xef\x03\n" +
	"\x11ServerRoomMessage\x12A\n" +
	"\froom_created\x18\x01 \x01(\v2\x1c.funkames.schema.RoomCreatedH\x00R\vroomCreated\x12Q\n" +
	"\x12player_joined_room\x18\x02 \x01(\v2!.funkames.schema.PlayerJoinedRoomH\x00R\x10playerJoinedRoom\x12K\n" +
	"\x10player_left_room\x18\x03 \x01(\v2\x1f.funkames.schema.PlayerLeftRoomH\x00R\x0eplayerLeftRoom\x12D\n" +
	"\rchat_received\x18\x04 \x01(\v2\x1d.funkames.schema.ChatReceivedH\x00R\fchatReceived\x12W\n" +
	"\x14player_toggled_ready\x18\x05 \x01(\v2#.funkames.schema.PlayerToggledReadyH\x00R\x12playerToggledReady\x12M\n" +
	"\x10settings_updated\x18\x06 \x01(\v2 .funkames.schema.SettingsUpdatedH\x00R\x0fsettingsUpdatedB\t\n" +
	"\apayload\"K\n" +
	"\x11ClientRoomMessage\x12+\n" +
	"\x04chat\x18\x01 \x01(\v2\x15.funkames.schema.ChatH\x00R\x04chatB\t\n" +
	"\apayload*\x18\n" +
	"\x04Game\x12\x10\n" +
	"\fMonopolyDeal\x10\x00B)Z'funkames/backend/internal/schema;schemab\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_room_proto_goTypes = []any{
	(Game)(0),                  // 0: funkames.schema.Game
	(*Player)(nil),             // 1: funkames.schema.Player
	(*Room)(nil),               // 2: funkames.schema.Room
	(*RoomCreated)(nil),        // 3: funkames.schema.RoomCreated
	(*PlayerJoinedRoom)(nil),   // 4: funkames.schema.PlayerJoinedRoom
	(*PlayerLeftRoom)(nil),     // 5: funkames.schema.PlayerLeftRoom
	(*RoomDeleted)(nil),        // 6: funkames.schema.RoomDeleted
	(*Chat)(nil),               // 7: funkames.schema.Chat
	(*ChatReceived)(nil),       // 8: funkames.schema.ChatReceived
	(*PlayerToggledReady)(nil), // 9: funkames.schema.PlayerToggledReady
	(*SettingsUpdated)(nil),    // 10: funkames.schema.SettingsUpdated
	(*ServerRoomMessage)(nil),  // 11: funkames.schema.ServerRoomMessage
	(*ClientRoomMessage)(nil),  // 12: funkames.schema.ClientRoomMessage
}
var file_room_proto_depIdxs = []int32{
	1,  // 0: funkames.schema.Room.players:type_name -> funkames.schema.Player
	0,  // 1: funkames.schema.Room.game:type_name -> funkames.schema.Game
	2,  // 2: funkames.schema.RoomCreated.room:type_name -> funkames.schema.Room
	1,  // 3: funkames.schema.PlayerJoinedRoom.player:type_name -> funkames.schema.Player
	0,  // 4: funkames.schema.SettingsUpdated.game:type_name -> funkames.schema.Game
	3,  // 5: funkames.schema.ServerRoomMessage.room_created:type_name -> funkames.schema.RoomCreated
	4,  // 6: funkames.schema.ServerRoomMessage.player_joined_room:type_name -> funkames.schema.PlayerJoinedRoom
	5,  // 7: funkames.schema.ServerRoomMessage.player_left_room:type_name -> funkames.schema.PlayerLeftRoom
	8,  // 8: funkames.schema.ServerRoomMessage.chat_received:type_name -> funkames.schema.ChatReceived
	9,  // 9: funkames.schema.ServerRoomMessage.player_toggled_ready:type_name -> funkames.schema.PlayerToggledReady
	10, // 10: funkames.schema.ServerRoomMessage.settings_updated:type_name -> funkames.schema.SettingsUpdated
	7,  // 11: funkames.schema.ClientRoomMessage.chat:type_name -> funkames.schema.Chat
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	file_room_proto_msgTypes[4].OneofWrappers = []any{}
	file_room_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerRoomMessage_RoomCreated)(nil),
		(*ServerRoomMessage_PlayerJoinedRoom)(nil),
		(*ServerRoomMessage_PlayerLeftRoom)(nil),
		(*ServerRoomMessage_ChatReceived)(nil),
		(*ServerRoomMessage_PlayerToggledReady)(nil),
		(*ServerRoomMessage_SettingsUpdated)(nil),
	}
	file_room_proto_msgTypes[11].OneofWrappers = []any{
		(*ClientRoomMessage_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
