// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gameplay
type CardType int32

const (
	CardType_CARD_TYPE_UNSPECIFIED CardType = 0
	// pure property cards
	CardType_CARD_TYPE_PROPERTY_BROWN      CardType = 10
	CardType_CARD_TYPE_PROPERTY_LIGHT_BLUE CardType = 11
	CardType_CARD_TYPE_PROPERTY_PINK       CardType = 12
	CardType_CARD_TYPE_PROPERTY_ORANGE     CardType = 13
	CardType_CARD_TYPE_PROPERTY_RED        CardType = 14
	CardType_CARD_TYPE_PROPERTY_YELLOW     CardType = 15
	CardType_CARD_TYPE_PROPERTY_GREEN      CardType = 16
	CardType_CARD_TYPE_PROPERTY_DARK_BLUE  CardType = 17
	CardType_CARD_TYPE_PROPERTY_UTILITY    CardType = 18
	CardType_CARD_TYPE_PROPERTY_RAILROAD   CardType = 19
	// wild property cards
	CardType_CARD_TYPE_PROPERTY_WILD_BROWN_LIGHT_BLUE    CardType = 20
	CardType_CARD_TYPE_PROPERTY_WILD_LIGHT_BLUE_RAILROAD CardType = 21
	CardType_CARD_TYPE_PROPERTY_WILD_PINK_ORANGE         CardType = 22
	CardType_CARD_TYPE_PROPERTY_WILD_ORANGE_UTILITY      CardType = 23
	CardType_CARD_TYPE_PROPERTY_WILD_GREEN_DARK_BLUE     CardType = 24
	CardType_CARD_TYPE_PROPERTY_WILRD_GREEN_RAILROAD     CardType = 25
	CardType_CARD_TYPE_PROPERTY_WILD_UTILITY_RAILROAD    CardType = 26
	CardType_CARD_TYPE_PROPERTY_WILD                     CardType = 27
	// money cards
	CardType_CARD_TYPE_MONEY_1  CardType = 30
	CardType_CARD_TYPE_MONEY_2  CardType = 31
	CardType_CARD_TYPE_MONEY_3  CardType = 32
	CardType_CARD_TYPE_MONEY_4  CardType = 33
	CardType_CARD_TYPE_MONEY_5  CardType = 34
	CardType_CARD_TYPE_MONEY_10 CardType = 35
	// action cards
	CardType_CARD_TYPE_ACTION_PASS_GO         CardType = 40
	CardType_CARD_TYPE_ACTION_DOUBLE_THE_RENT CardType = 41
	CardType_CARD_TYPE_ACTION_ITS_MY_BIRTHDAY CardType = 42
	CardType_CARD_TYPE_ACTION_HOUSE           CardType = 43
	CardType_CARD_TYPE_ACTION_SLY_DEAL        CardType = 44
	CardType_CARD_TYPE_ACTION_FORCED_DEAL     CardType = 45
	CardType_CARD_TYPE_ACTION_DEBT_COLLECTOR  CardType = 46
	CardType_CARD_TYPE_ACTION_HOTEL           CardType = 47
	CardType_CARD_TYPE_ACTION_JUST_SAY_NO     CardType = 48
	CardType_CARD_TYPE_ACTION_DEAL_BREAKER    CardType = 49
	// rent cards
	CardType_CARD_TYPE_RENT_BROWN_LIGHT_BLUE CardType = 50
	CardType_CARD_TYPE_RENT_PINK_ORANGE      CardType = 51
	CardType_CARD_TYPE_RENT_RED_YELLOW       CardType = 52
	CardType_CARD_TYPE_RENT_GREEN_DARK_BLUE  CardType = 53
	CardType_CARD_TYPE_RENT_UTILITY_RAILROAD CardType = 54
	CardType_CARD_TYPE_RENT_WILD             CardType = 55
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0:  "CARD_TYPE_UNSPECIFIED",
		10: "CARD_TYPE_PROPERTY_BROWN",
		11: "CARD_TYPE_PROPERTY_LIGHT_BLUE",
		12: "CARD_TYPE_PROPERTY_PINK",
		13: "CARD_TYPE_PROPERTY_ORANGE",
		14: "CARD_TYPE_PROPERTY_RED",
		15: "CARD_TYPE_PROPERTY_YELLOW",
		16: "CARD_TYPE_PROPERTY_GREEN",
		17: "CARD_TYPE_PROPERTY_DARK_BLUE",
		18: "CARD_TYPE_PROPERTY_UTILITY",
		19: "CARD_TYPE_PROPERTY_RAILROAD",
		20: "CARD_TYPE_PROPERTY_WILD_BROWN_LIGHT_BLUE",
		21: "CARD_TYPE_PROPERTY_WILD_LIGHT_BLUE_RAILROAD",
		22: "CARD_TYPE_PROPERTY_WILD_PINK_ORANGE",
		23: "CARD_TYPE_PROPERTY_WILD_ORANGE_UTILITY",
		24: "CARD_TYPE_PROPERTY_WILD_GREEN_DARK_BLUE",
		25: "CARD_TYPE_PROPERTY_WILRD_GREEN_RAILROAD",
		26: "CARD_TYPE_PROPERTY_WILD_UTILITY_RAILROAD",
		27: "CARD_TYPE_PROPERTY_WILD",
		30: "CARD_TYPE_MONEY_1",
		31: "CARD_TYPE_MONEY_2",
		32: "CARD_TYPE_MONEY_3",
		33: "CARD_TYPE_MONEY_4",
		34: "CARD_TYPE_MONEY_5",
		35: "CARD_TYPE_MONEY_10",
		40: "CARD_TYPE_ACTION_PASS_GO",
		41: "CARD_TYPE_ACTION_DOUBLE_THE_RENT",
		42: "CARD_TYPE_ACTION_ITS_MY_BIRTHDAY",
		43: "CARD_TYPE_ACTION_HOUSE",
		44: "CARD_TYPE_ACTION_SLY_DEAL",
		45: "CARD_TYPE_ACTION_FORCED_DEAL",
		46: "CARD_TYPE_ACTION_DEBT_COLLECTOR",
		47: "CARD_TYPE_ACTION_HOTEL",
		48: "CARD_TYPE_ACTION_JUST_SAY_NO",
		49: "CARD_TYPE_ACTION_DEAL_BREAKER",
		50: "CARD_TYPE_RENT_BROWN_LIGHT_BLUE",
		51: "CARD_TYPE_RENT_PINK_ORANGE",
		52: "CARD_TYPE_RENT_RED_YELLOW",
		53: "CARD_TYPE_RENT_GREEN_DARK_BLUE",
		54: "CARD_TYPE_RENT_UTILITY_RAILROAD",
		55: "CARD_TYPE_RENT_WILD",
	}
	CardType_value = map[string]int32{
		"CARD_TYPE_UNSPECIFIED":                       0,
		"CARD_TYPE_PROPERTY_BROWN":                    10,
		"CARD_TYPE_PROPERTY_LIGHT_BLUE":               11,
		"CARD_TYPE_PROPERTY_PINK":                     12,
		"CARD_TYPE_PROPERTY_ORANGE":                   13,
		"CARD_TYPE_PROPERTY_RED":                      14,
		"CARD_TYPE_PROPERTY_YELLOW":                   15,
		"CARD_TYPE_PROPERTY_GREEN":                    16,
		"CARD_TYPE_PROPERTY_DARK_BLUE":                17,
		"CARD_TYPE_PROPERTY_UTILITY":                  18,
		"CARD_TYPE_PROPERTY_RAILROAD":                 19,
		"CARD_TYPE_PROPERTY_WILD_BROWN_LIGHT_BLUE":    20,
		"CARD_TYPE_PROPERTY_WILD_LIGHT_BLUE_RAILROAD": 21,
		"CARD_TYPE_PROPERTY_WILD_PINK_ORANGE":         22,
		"CARD_TYPE_PROPERTY_WILD_ORANGE_UTILITY":      23,
		"CARD_TYPE_PROPERTY_WILD_GREEN_DARK_BLUE":     24,
		"CARD_TYPE_PROPERTY_WILRD_GREEN_RAILROAD":     25,
		"CARD_TYPE_PROPERTY_WILD_UTILITY_RAILROAD":    26,
		"CARD_TYPE_PROPERTY_WILD":                     27,
		"CARD_TYPE_MONEY_1":                           30,
		"CARD_TYPE_MONEY_2":                           31,
		"CARD_TYPE_MONEY_3":                           32,
		"CARD_TYPE_MONEY_4":                           33,
		"CARD_TYPE_MONEY_5":                           34,
		"CARD_TYPE_MONEY_10":                          35,
		"CARD_TYPE_ACTION_PASS_GO":                    40,
		"CARD_TYPE_ACTION_DOUBLE_THE_RENT":            41,
		"CARD_TYPE_ACTION_ITS_MY_BIRTHDAY":            42,
		"CARD_TYPE_ACTION_HOUSE":                      43,
		"CARD_TYPE_ACTION_SLY_DEAL":                   44,
		"CARD_TYPE_ACTION_FORCED_DEAL":                45,
		"CARD_TYPE_ACTION_DEBT_COLLECTOR":             46,
		"CARD_TYPE_ACTION_HOTEL":                      47,
		"CARD_TYPE_ACTION_JUST_SAY_NO":                48,
		"CARD_TYPE_ACTION_DEAL_BREAKER":               49,
		"CARD_TYPE_RENT_BROWN_LIGHT_BLUE":             50,
		"CARD_TYPE_RENT_PINK_ORANGE":                  51,
		"CARD_TYPE_RENT_RED_YELLOW":                   52,
		"CARD_TYPE_RENT_GREEN_DARK_BLUE":              53,
		"CARD_TYPE_RENT_UTILITY_RAILROAD":             54,
		"CARD_TYPE_RENT_WILD":                         55,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

// generic
type Ping struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeUnixMs int64                  `protobuf:"varint,1,opt,name=client_time_unix_ms,json=clientTimeUnixMs,proto3" json:"client_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetClientTimeUnixMs() int64 {
	if x != nil {
		return x.ClientTimeUnixMs
	}
	return 0
}

type Pong struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeUnixMs int64                  `protobuf:"varint,1,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// lobby
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsReady       bool                   `protobuf:"varint,4,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Player) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Room) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type RoomList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	mi := &file_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

func (x *RoomList) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type CreateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoom) Reset() {
	*x = CreateRoom{}
	mi := &file_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom) ProtoMessage() {}

func (x *CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom.ProtoReflect.Descriptor instead.
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoom) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoomResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoom) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoomResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveRoom) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaveRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveRoomResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaveRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DeleteRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoom) Reset() {
	*x = DeleteRoom{}
	mi := &file_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoom) ProtoMessage() {}

func (x *DeleteRoom) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoom.ProtoReflect.Descriptor instead.
func (*DeleteRoom) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type PropertyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardType      CardType               `protobuf:"varint,1,opt,name=card_type,json=cardType,proto3,enum=monopolydeal.schema.CardType" json:"card_type,omitempty"`
	PropertyName  *string                `protobuf:"bytes,2,opt,name=property_name,json=propertyName,proto3,oneof" json:"property_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyType) Reset() {
	*x = PropertyType{}
	mi := &file_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyType) ProtoMessage() {}

func (x *PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyType.ProtoReflect.Descriptor instead.
func (*PropertyType) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{14}
}

func (x *PropertyType) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

func (x *PropertyType) GetPropertyName() string {
	if x != nil && x.PropertyName != nil {
		return *x.PropertyName
	}
	return ""
}

type PropertySetType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyTypes []*PropertyType        `protobuf:"bytes,1,rep,name=property_types,json=propertyTypes,proto3" json:"property_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySetType) Reset() {
	*x = PropertySetType{}
	mi := &file_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySetType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySetType) ProtoMessage() {}

func (x *PropertySetType) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySetType.ProtoReflect.Descriptor instead.
func (*PropertySetType) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{15}
}

func (x *PropertySetType) GetPropertyTypes() []*PropertyType {
	if x != nil {
		return x.PropertyTypes
	}
	return nil
}

type PlayProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Property      *PropertyType          `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayProperty) Reset() {
	*x = PlayProperty{}
	mi := &file_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayProperty) ProtoMessage() {}

func (x *PlayProperty) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayProperty.ProtoReflect.Descriptor instead.
func (*PlayProperty) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{16}
}

func (x *PlayProperty) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayProperty) GetProperty() *PropertyType {
	if x != nil {
		return x.Property
	}
	return nil
}

type PlayMoney struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          CardType               `protobuf:"varint,2,opt,name=card,proto3,enum=monopolydeal.schema.CardType" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoney) Reset() {
	*x = PlayMoney{}
	mi := &file_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoney) ProtoMessage() {}

func (x *PlayMoney) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoney.ProtoReflect.Descriptor instead.
func (*PlayMoney) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{17}
}

func (x *PlayMoney) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayMoney) GetCard() CardType {
	if x != nil {
		return x.Card
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

// pass go loop
type PlayPassGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPassGo) Reset() {
	*x = PlayPassGo{}
	mi := &file_schema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPassGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPassGo) ProtoMessage() {}

func (x *PlayPassGo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPassGo.ProtoReflect.Descriptor instead.
func (*PlayPassGo) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{18}
}

func (x *PlayPassGo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type RespondPassGo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []CardType             `protobuf:"varint,2,rep,packed,name=cards,proto3,enum=monopolydeal.schema.CardType" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondPassGo) Reset() {
	*x = RespondPassGo{}
	mi := &file_schema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondPassGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondPassGo) ProtoMessage() {}

func (x *RespondPassGo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondPassGo.ProtoReflect.Descriptor instead.
func (*RespondPassGo) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{19}
}

func (x *RespondPassGo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondPassGo) GetCards() []CardType {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PlayDoubleTheRent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayDoubleTheRent) Reset() {
	*x = PlayDoubleTheRent{}
	mi := &file_schema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayDoubleTheRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDoubleTheRent) ProtoMessage() {}

func (x *PlayDoubleTheRent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDoubleTheRent.ProtoReflect.Descriptor instead.
func (*PlayDoubleTheRent) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{20}
}

func (x *PlayDoubleTheRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// its my birthday loop
type PlayItsMyBirthday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayItsMyBirthday) Reset() {
	*x = PlayItsMyBirthday{}
	mi := &file_schema_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayItsMyBirthday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayItsMyBirthday) ProtoMessage() {}

func (x *PlayItsMyBirthday) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayItsMyBirthday.ProtoReflect.Descriptor instead.
func (*PlayItsMyBirthday) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{21}
}

func (x *PlayItsMyBirthday) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type RespondItsMyBirthday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []CardType             `protobuf:"varint,2,rep,packed,name=cards,proto3,enum=monopolydeal.schema.CardType" json:"cards,omitempty"`
	SaidNo        bool                   `protobuf:"varint,3,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondItsMyBirthday) Reset() {
	*x = RespondItsMyBirthday{}
	mi := &file_schema_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondItsMyBirthday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondItsMyBirthday) ProtoMessage() {}

func (x *RespondItsMyBirthday) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondItsMyBirthday.ProtoReflect.Descriptor instead.
func (*RespondItsMyBirthday) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{22}
}

func (x *RespondItsMyBirthday) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondItsMyBirthday) GetCards() []CardType {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *RespondItsMyBirthday) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayHouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySetType       `protobuf:"bytes,2,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayHouse) Reset() {
	*x = PlayHouse{}
	mi := &file_schema_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayHouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayHouse) ProtoMessage() {}

func (x *PlayHouse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayHouse.ProtoReflect.Descriptor instead.
func (*PlayHouse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{23}
}

func (x *PlayHouse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayHouse) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type PlaySlyDeal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Property       *PropertyType          `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaySlyDeal) Reset() {
	*x = PlaySlyDeal{}
	mi := &file_schema_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaySlyDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySlyDeal) ProtoMessage() {}

func (x *PlaySlyDeal) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySlyDeal.ProtoReflect.Descriptor instead.
func (*PlaySlyDeal) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{24}
}

func (x *PlaySlyDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlaySlyDeal) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *PlaySlyDeal) GetProperty() *PropertyType {
	if x != nil {
		return x.Property
	}
	return nil
}

type RespondSlyDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondSlyDeal) Reset() {
	*x = RespondSlyDeal{}
	mi := &file_schema_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondSlyDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondSlyDeal) ProtoMessage() {}

func (x *RespondSlyDeal) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondSlyDeal.ProtoReflect.Descriptor instead.
func (*RespondSlyDeal) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{25}
}

func (x *RespondSlyDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondSlyDeal) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayForcedDeal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	SourceProperty *PropertyType          `protobuf:"bytes,3,opt,name=source_property,json=sourceProperty,proto3" json:"source_property,omitempty"`
	TargetProperty *PropertyType          `protobuf:"bytes,4,opt,name=target_property,json=targetProperty,proto3" json:"target_property,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayForcedDeal) Reset() {
	*x = PlayForcedDeal{}
	mi := &file_schema_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayForcedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayForcedDeal) ProtoMessage() {}

func (x *PlayForcedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayForcedDeal.ProtoReflect.Descriptor instead.
func (*PlayForcedDeal) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{26}
}

func (x *PlayForcedDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayForcedDeal) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *PlayForcedDeal) GetSourceProperty() *PropertyType {
	if x != nil {
		return x.SourceProperty
	}
	return nil
}

func (x *PlayForcedDeal) GetTargetProperty() *PropertyType {
	if x != nil {
		return x.TargetProperty
	}
	return nil
}

type RespondForcedDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondForcedDeal) Reset() {
	*x = RespondForcedDeal{}
	mi := &file_schema_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondForcedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondForcedDeal) ProtoMessage() {}

func (x *RespondForcedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondForcedDeal.ProtoReflect.Descriptor instead.
func (*RespondForcedDeal) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{27}
}

func (x *RespondForcedDeal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondForcedDeal) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayDebtCollector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayDebtCollector) Reset() {
	*x = PlayDebtCollector{}
	mi := &file_schema_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayDebtCollector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDebtCollector) ProtoMessage() {}

func (x *PlayDebtCollector) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDebtCollector.ProtoReflect.Descriptor instead.
func (*PlayDebtCollector) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{28}
}

func (x *PlayDebtCollector) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayDebtCollector) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

type RespondDebtCollector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondDebtCollector) Reset() {
	*x = RespondDebtCollector{}
	mi := &file_schema_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondDebtCollector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondDebtCollector) ProtoMessage() {}

func (x *RespondDebtCollector) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondDebtCollector.ProtoReflect.Descriptor instead.
func (*RespondDebtCollector) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{29}
}

func (x *RespondDebtCollector) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondDebtCollector) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayHotel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PropertySet   *PropertySetType       `protobuf:"bytes,2,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayHotel) Reset() {
	*x = PlayHotel{}
	mi := &file_schema_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayHotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayHotel) ProtoMessage() {}

func (x *PlayHotel) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayHotel.ProtoReflect.Descriptor instead.
func (*PlayHotel) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{30}
}

func (x *PlayHotel) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayHotel) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type RespondJustSayNo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondJustSayNo) Reset() {
	*x = RespondJustSayNo{}
	mi := &file_schema_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondJustSayNo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondJustSayNo) ProtoMessage() {}

func (x *RespondJustSayNo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondJustSayNo.ProtoReflect.Descriptor instead.
func (*RespondJustSayNo) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{31}
}

func (x *RespondJustSayNo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondJustSayNo) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayDealBreaker struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	PropertySet    *PropertySetType       `protobuf:"bytes,3,opt,name=property_set,json=propertySet,proto3" json:"property_set,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayDealBreaker) Reset() {
	*x = PlayDealBreaker{}
	mi := &file_schema_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayDealBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayDealBreaker) ProtoMessage() {}

func (x *PlayDealBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayDealBreaker.ProtoReflect.Descriptor instead.
func (*PlayDealBreaker) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{32}
}

func (x *PlayDealBreaker) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayDealBreaker) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *PlayDealBreaker) GetPropertySet() *PropertySetType {
	if x != nil {
		return x.PropertySet
	}
	return nil
}

type RespondDealBreaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SaidNo        bool                   `protobuf:"varint,2,opt,name=said_no,json=saidNo,proto3" json:"said_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondDealBreaker) Reset() {
	*x = RespondDealBreaker{}
	mi := &file_schema_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondDealBreaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondDealBreaker) ProtoMessage() {}

func (x *RespondDealBreaker) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondDealBreaker.ProtoReflect.Descriptor instead.
func (*RespondDealBreaker) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{33}
}

func (x *RespondDealBreaker) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RespondDealBreaker) GetSaidNo() bool {
	if x != nil {
		return x.SaidNo
	}
	return false
}

type PlayRent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Card          CardType               `protobuf:"varint,2,opt,name=card,proto3,enum=monopolydeal.schema.CardType" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayRent) Reset() {
	*x = PlayRent{}
	mi := &file_schema_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayRent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRent) ProtoMessage() {}

func (x *PlayRent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRent.ProtoReflect.Descriptor instead.
func (*PlayRent) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{34}
}

func (x *PlayRent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayRent) GetCard() CardType {
	if x != nil {
		return x.Card
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\x13monopolydeal.schema\"5\n" +
	"\x04Ping\x12-\n" +
	"\x13client_time_unix_ms\x18\x01 \x01(\x03R\x10clientTimeUnixMs\"5\n" +
	"\x04Pong\x12-\n" +
	"\x13server_time_unix_ms\x18\x01 \x01(\x03R\x10serverTimeUnixMs\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x82\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bis_ready\x18\x04 \x01(\bR\aisReady\"\x8a\x01\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x125\n" +
	"\aplayers\x18\x02 \x03(\v2\x1b.monopolydeal.schema.PlayerR\aplayers\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\";\n" +
	"\bRoomList\x12/\n" +
	"\x05rooms\x18\x01 \x03(\v2\x19.monopolydeal.schema.RoomR\x05rooms\")\n" +
	"\n" +
	"CreateRoom\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"J\n" +
	"\x12CreateRoomResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"@\n" +
	"\bJoinRoom\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"H\n" +
	"\x10JoinRoomResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"A\n" +
	"\tLeaveRoom\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"I\n" +
	"\x11LeaveRoomResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"%\n" +
	"\n" +
	"DeleteRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"-\n" +
	"\x12DeleteRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x86\x01\n" +
	"\fPropertyType\x12:\n" +
	"\tcard_type\x18\x01 \x01(\x0e2\x1d.monopolydeal.schema.CardTypeR\bcardType\x12(\n" +
	"\rproperty_name\x18\x02 \x01(\tH\x00R\fpropertyName\x88\x01\x01B\x10\n" +
	"\x0e_property_name\"[\n" +
	"\x0fPropertySetType\x12H\n" +
	"\x0eproperty_types\x18\x01 \x03(\v2!.monopolydeal.schema.PropertyTypeR\rpropertyTypes\"j\n" +
	"\fPlayProperty\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12=\n" +
	"\bproperty\x18\x02 \x01(\v2!.monopolydeal.schema.PropertyTypeR\bproperty\"[\n" +
	"\tPlayMoney\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x121\n" +
	"\x04card\x18\x02 \x01(\x0e2\x1d.monopolydeal.schema.CardTypeR\x04card\")\n" +
	"\n" +
	"PlayPassGo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"a\n" +
	"\rRespondPassGo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x123\n" +
	"\x05cards\x18\x02 \x03(\x0e2\x1d.monopolydeal.schema.CardTypeR\x05cards\"0\n" +
	"\x11PlayDoubleTheRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"0\n" +
	"\x11PlayItsMyBirthday\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x81\x01\n" +
	"\x14RespondItsMyBirthday\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x123\n" +
	"\x05cards\x18\x02 \x03(\x0e2\x1d.monopolydeal.schema.CardTypeR\x05cards\x12\x17\n" +
	"\asaid_no\x18\x03 \x01(\bR\x06saidNo\"q\n" +
	"\tPlayHouse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12G\n" +
	"\fproperty_set\x18\x02 \x01(\v2$.monopolydeal.schema.PropertySetTypeR\vpropertySet\"\x93\x01\n" +
	"\vPlaySlyDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x12=\n" +
	"\bproperty\x18\x03 \x01(\v2!.monopolydeal.schema.PropertyTypeR\bproperty\"F\n" +
	"\x0eRespondSlyDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"\xef\x01\n" +
	"\x0ePlayForcedDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x12J\n" +
	"\x0fsource_property\x18\x03 \x01(\v2!.monopolydeal.schema.PropertyTypeR\x0esourceProperty\x12J\n" +
	"\x0ftarget_property\x18\x04 \x01(\v2!.monopolydeal.schema.PropertyTypeR\x0etargetProperty\"I\n" +
	"\x11RespondForcedDeal\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"Z\n" +
	"\x11PlayDebtCollector\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\"L\n" +
	"\x14RespondDebtCollector\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"q\n" +
	"\tPlayHotel\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12G\n" +
	"\fproperty_set\x18\x02 \x01(\v2$.monopolydeal.schema.PropertySetTypeR\vpropertySet\"H\n" +
	"\x10RespondJustSayNo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"\xa1\x01\n" +
	"\x0fPlayDealBreaker\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\x12G\n" +
	"\fproperty_set\x18\x03 \x01(\v2$.monopolydeal.schema.PropertySetTypeR\vpropertySet\"J\n" +
	"\x12RespondDealBreaker\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\asaid_no\x18\x02 \x01(\bR\x06saidNo\"Z\n" +
	"\bPlayRent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x121\n" +
	"\x04card\x18\x02 \x01(\x0e2\x1d.monopolydeal.schema.CardTypeR\x04card*\xd5\n" +
	"\n" +
	"\bCardType\x12\x19\n" +
	"\x15CARD_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CARD_TYPE_PROPERTY_BROWN\x10\n" +
	"\x12!\n" +
	"\x1dCARD_TYPE_PROPERTY_LIGHT_BLUE\x10\v\x12\x1b\n" +
	"\x17CARD_TYPE_PROPERTY_PINK\x10\f\x12\x1d\n" +
	"\x19CARD_TYPE_PROPERTY_ORANGE\x10\r\x12\x1a\n" +
	"\x16CARD_TYPE_PROPERTY_RED\x10\x0e\x12\x1d\n" +
	"\x19CARD_TYPE_PROPERTY_YELLOW\x10\x0f\x12\x1c\n" +
	"\x18CARD_TYPE_PROPERTY_GREEN\x10\x10\x12 \n" +
	"\x1cCARD_TYPE_PROPERTY_DARK_BLUE\x10\x11\x12\x1e\n" +
	"\x1aCARD_TYPE_PROPERTY_UTILITY\x10\x12\x12\x1f\n" +
	"\x1bCARD_TYPE_PROPERTY_RAILROAD\x10\x13\x12,\n" +
	"(CARD_TYPE_PROPERTY_WILD_BROWN_LIGHT_BLUE\x10\x14\x12/\n" +
	"+CARD_TYPE_PROPERTY_WILD_LIGHT_BLUE_RAILROAD\x10\x15\x12'\n" +
	"#CARD_TYPE_PROPERTY_WILD_PINK_ORANGE\x10\x16\x12*\n" +
	"&CARD_TYPE_PROPERTY_WILD_ORANGE_UTILITY\x10\x17\x12+\n" +
	"'CARD_TYPE_PROPERTY_WILD_GREEN_DARK_BLUE\x10\x18\x12+\n" +
	"'CARD_TYPE_PROPERTY_WILRD_GREEN_RAILROAD\x10\x19\x12,\n" +
	"(CARD_TYPE_PROPERTY_WILD_UTILITY_RAILROAD\x10\x1a\x12\x1b\n" +
	"\x17CARD_TYPE_PROPERTY_WILD\x10\x1b\x12\x15\n" +
	"\x11CARD_TYPE_MONEY_1\x10\x1e\x12\x15\n" +
	"\x11CARD_TYPE_MONEY_2\x10\x1f\x12\x15\n" +
	"\x11CARD_TYPE_MONEY_3\x10 \x12\x15\n" +
	"\x11CARD_TYPE_MONEY_4\x10!\x12\x15\n" +
	"\x11CARD_TYPE_MONEY_5\x10\"\x12\x16\n" +
	"\x12CARD_TYPE_MONEY_10\x10#\x12\x1c\n" +
	"\x18CARD_TYPE_ACTION_PASS_GO\x10(\x12$\n" +
	" CARD_TYPE_ACTION_DOUBLE_THE_RENT\x10)\x12$\n" +
	" CARD_TYPE_ACTION_ITS_MY_BIRTHDAY\x10*\x12\x1a\n" +
	"\x16CARD_TYPE_ACTION_HOUSE\x10+\x12\x1d\n" +
	"\x19CARD_TYPE_ACTION_SLY_DEAL\x10,\x12 \n" +
	"\x1cCARD_TYPE_ACTION_FORCED_DEAL\x10-\x12#\n" +
	"\x1fCARD_TYPE_ACTION_DEBT_COLLECTOR\x10.\x12\x1a\n" +
	"\x16CARD_TYPE_ACTION_HOTEL\x10/\x12 \n" +
	"\x1cCARD_TYPE_ACTION_JUST_SAY_NO\x100\x12!\n" +
	"\x1dCARD_TYPE_ACTION_DEAL_BREAKER\x101\x12#\n" +
	"\x1fCARD_TYPE_RENT_BROWN_LIGHT_BLUE\x102\x12\x1e\n" +
	"\x1aCARD_TYPE_RENT_PINK_ORANGE\x103\x12\x1d\n" +
	"\x19CARD_TYPE_RENT_RED_YELLOW\x104\x12\"\n" +
	"\x1eCARD_TYPE_RENT_GREEN_DARK_BLUE\x105\x12#\n" +
	"\x1fCARD_TYPE_RENT_UTILITY_RAILROAD\x106\x12\x17\n" +
	"\x13CARD_TYPE_RENT_WILD\x107B.Z,monopoly-deal/backend/internal/schema;schemab\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_schema_proto_goTypes = []any{
	(CardType)(0),                // 0: monopolydeal.schema.CardType
	(*Ping)(nil),                 // 1: monopolydeal.schema.Ping
	(*Pong)(nil),                 // 2: monopolydeal.schema.Pong
	(*Error)(nil),                // 3: monopolydeal.schema.Error
	(*Player)(nil),               // 4: monopolydeal.schema.Player
	(*Room)(nil),                 // 5: monopolydeal.schema.Room
	(*RoomList)(nil),             // 6: monopolydeal.schema.RoomList
	(*CreateRoom)(nil),           // 7: monopolydeal.schema.CreateRoom
	(*CreateRoomResponse)(nil),   // 8: monopolydeal.schema.CreateRoomResponse
	(*JoinRoom)(nil),             // 9: monopolydeal.schema.JoinRoom
	(*JoinRoomResponse)(nil),     // 10: monopolydeal.schema.JoinRoomResponse
	(*LeaveRoom)(nil),            // 11: monopolydeal.schema.LeaveRoom
	(*LeaveRoomResponse)(nil),    // 12: monopolydeal.schema.LeaveRoomResponse
	(*DeleteRoom)(nil),           // 13: monopolydeal.schema.DeleteRoom
	(*DeleteRoomResponse)(nil),   // 14: monopolydeal.schema.DeleteRoomResponse
	(*PropertyType)(nil),         // 15: monopolydeal.schema.PropertyType
	(*PropertySetType)(nil),      // 16: monopolydeal.schema.PropertySetType
	(*PlayProperty)(nil),         // 17: monopolydeal.schema.PlayProperty
	(*PlayMoney)(nil),            // 18: monopolydeal.schema.PlayMoney
	(*PlayPassGo)(nil),           // 19: monopolydeal.schema.PlayPassGo
	(*RespondPassGo)(nil),        // 20: monopolydeal.schema.RespondPassGo
	(*PlayDoubleTheRent)(nil),    // 21: monopolydeal.schema.PlayDoubleTheRent
	(*PlayItsMyBirthday)(nil),    // 22: monopolydeal.schema.PlayItsMyBirthday
	(*RespondItsMyBirthday)(nil), // 23: monopolydeal.schema.RespondItsMyBirthday
	(*PlayHouse)(nil),            // 24: monopolydeal.schema.PlayHouse
	(*PlaySlyDeal)(nil),          // 25: monopolydeal.schema.PlaySlyDeal
	(*RespondSlyDeal)(nil),       // 26: monopolydeal.schema.RespondSlyDeal
	(*PlayForcedDeal)(nil),       // 27: monopolydeal.schema.PlayForcedDeal
	(*RespondForcedDeal)(nil),    // 28: monopolydeal.schema.RespondForcedDeal
	(*PlayDebtCollector)(nil),    // 29: monopolydeal.schema.PlayDebtCollector
	(*RespondDebtCollector)(nil), // 30: monopolydeal.schema.RespondDebtCollector
	(*PlayHotel)(nil),            // 31: monopolydeal.schema.PlayHotel
	(*RespondJustSayNo)(nil),     // 32: monopolydeal.schema.RespondJustSayNo
	(*PlayDealBreaker)(nil),      // 33: monopolydeal.schema.PlayDealBreaker
	(*RespondDealBreaker)(nil),   // 34: monopolydeal.schema.RespondDealBreaker
	(*PlayRent)(nil),             // 35: monopolydeal.schema.PlayRent
}
var file_schema_proto_depIdxs = []int32{
	4,  // 0: monopolydeal.schema.Room.players:type_name -> monopolydeal.schema.Player
	5,  // 1: monopolydeal.schema.RoomList.rooms:type_name -> monopolydeal.schema.Room
	0,  // 2: monopolydeal.schema.PropertyType.card_type:type_name -> monopolydeal.schema.CardType
	15, // 3: monopolydeal.schema.PropertySetType.property_types:type_name -> monopolydeal.schema.PropertyType
	15, // 4: monopolydeal.schema.PlayProperty.property:type_name -> monopolydeal.schema.PropertyType
	0,  // 5: monopolydeal.schema.PlayMoney.card:type_name -> monopolydeal.schema.CardType
	0,  // 6: monopolydeal.schema.RespondPassGo.cards:type_name -> monopolydeal.schema.CardType
	0,  // 7: monopolydeal.schema.RespondItsMyBirthday.cards:type_name -> monopolydeal.schema.CardType
	16, // 8: monopolydeal.schema.PlayHouse.property_set:type_name -> monopolydeal.schema.PropertySetType
	15, // 9: monopolydeal.schema.PlaySlyDeal.property:type_name -> monopolydeal.schema.PropertyType
	15, // 10: monopolydeal.schema.PlayForcedDeal.source_property:type_name -> monopolydeal.schema.PropertyType
	15, // 11: monopolydeal.schema.PlayForcedDeal.target_property:type_name -> monopolydeal.schema.PropertyType
	16, // 12: monopolydeal.schema.PlayHotel.property_set:type_name -> monopolydeal.schema.PropertySetType
	16, // 13: monopolydeal.schema.PlayDealBreaker.property_set:type_name -> monopolydeal.schema.PropertySetType
	0,  // 14: monopolydeal.schema.PlayRent.card:type_name -> monopolydeal.schema.CardType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	file_schema_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
