syntax = "proto3";

package the_deal.schema.monopoly_deal;

option go_package = "the-deal/internal/schema/monopoly_deal_schema;monopoly_deal_schema";

message Error {
  string message = 1;
  int32 status = 2;
  string code = 3;
}

message Chat {
  string payload = 1;
}

message ChatReceived {
  string player_id = 1;
  string payload = 2;
}

enum AssetKey {
  ASSET_KEY_UNSPECIFIED = 0;

  ASSET_KEY_BROWN1 = 1;
  ASSET_KEY_BROWN2 = 2;
  ASSET_KEY_SKY1 = 3;
  ASSET_KEY_SKY2 = 4;
  ASSET_KEY_SKY3 = 5;
  ASSET_KEY_PINK1 = 6;
  ASSET_KEY_PINK2 = 7;
  ASSET_KEY_PINK3 = 8;
  ASSET_KEY_ORANGE1 = 9;
  ASSET_KEY_ORANGE2 = 10;
  ASSET_KEY_ORANGE3 = 11;
  ASSET_KEY_RED1 = 12;
  ASSET_KEY_RED2 = 13;
  ASSET_KEY_RED3 = 14;
  ASSET_KEY_YELLOW1 = 15;
  ASSET_KEY_YELLOW2 = 16;
  ASSET_KEY_YELLOW3 = 17;
  ASSET_KEY_GREEN1 = 18;
  ASSET_KEY_GREEN2 = 19;
  ASSET_KEY_GREEN3 = 20;
  ASSET_KEY_BLUE1 = 21;
  ASSET_KEY_BLUE2 = 22;
  ASSET_KEY_UTIL1 = 23;
  ASSET_KEY_UTIL2 = 24;
  ASSET_KEY_RAIL1 = 25;
  ASSET_KEY_RAIL2 = 26;
  ASSET_KEY_RAIL3 = 27;
  ASSET_KEY_RAIL4 = 28;

  ASSET_KEY_WILD_BROWN_SKY = 29;
  ASSET_KEY_WILD_SKY_RAILROAD = 30;
  ASSET_KEY_WILD_PINK_ORANGE = 31;
  ASSET_KEY_WILD_RED_YELLOW = 32;
  ASSET_KEY_WILD_GREEN_BLUE = 33;
  ASSET_KEY_WILD_GREEN_RAILROAD = 34;
  ASSET_KEY_WILD_UTILITY_RAILROAD = 35;
  ASSET_KEY_WILD_WILD = 36;

  ASSET_KEY_MONEY_10 = 37;
  ASSET_KEY_MONEY_5 = 38;
  ASSET_KEY_MONEY_4 = 39;
  ASSET_KEY_MONEY_3 = 40;
  ASSET_KEY_MONEY_2 = 41;
  ASSET_KEY_MONEY_1 = 42;

  ASSET_KEY_DEAL_BREAKER = 43;
  ASSET_KEY_JUST_SAY_NO = 44;
  ASSET_KEY_HOTEL = 45;
  ASSET_KEY_DEBT_COLLECTOR = 46;
  ASSET_KEY_FORCED_DEAL = 47;
  ASSET_KEY_SLY_DEAL = 48;
  ASSET_KEY_HOUSE = 49;
  ASSET_KEY_ITS_MY_BIRTHDAY = 50;
  ASSET_KEY_DOUBLE_THE_RENT = 51;
  ASSET_KEY_PASS_GO = 52;

  ASSET_KEY_RENT_WILD = 53;
  ASSET_KEY_RENT_BROWN_SKY = 54;
  ASSET_KEY_RENT_PINK_ORANGE = 55;
  ASSET_KEY_RENT_RED_YELLOW = 56;
  ASSET_KEY_RENT_GREEN_BLUE = 57;
  ASSET_KEY_RENT_UTILITY_RAILROAD = 58;
}

enum Category {
  CATEGORY_UNSPECIFIED = 0;

  CATEGORY_PURE_PROPERTY = 1;
  CATEGORY_WILD_PROPERTY = 2;
  CATEGORY_MONEY = 3;
  CATEGORY_ACTION = 4;
}

enum Color {
  COLOR_UNSPECIFIED = 0;

  COLOR_BROWN = 1;
  COLOR_SKY = 2;
  COLOR_PINK = 3;
  COLOR_ORANGE = 4;
  COLOR_RED = 5;
  COLOR_YELLOW = 6;
  COLOR_GREEN = 7;
  COLOR_BLUE = 8;
  COLOR_UTILITY = 9;
  COLOR_RAILROAD = 10;
}

message Card {
  string card_id = 1;
  AssetKey asset_key = 2;
  Category category = 3;
  Color active_color = 4;
  repeated Color colors = 5;
  int32 value = 6;
}

message Player {
  string player_id = 1;
  string display_name = 2;
  string avatar_url = 3;
  int32 money = 4;
  int32 completed_sets = 5;
  int32 hand_cards = 6;
}

message Hand {
  repeated Card cards = 1;
}

message Money {
  string player_id = 1;
  repeated Card cards = 2;
}

message PropertySet {
  string player_id = 1;
  string property_set_id = 2;
  Color color = 3;
  repeated Card cards = 4;
}

enum DemandKind {
  DEMAND_KIND_UNSPECIFIED = 0;

  DEMAND_KIND_PAYMENT = 1;
  DEMAND_KIND_PROPERTY = 2;
  DEMAND_KIND_PROPERTY_SET = 3;
}

message PaymentDemand {
  int32 amount = 1;
}

message PropertyDemand {
  optional string source_card_id = 1;
  string target_card_id = 2;
}

message PropertySetDemand {
  string property_set_id = 1;
}

enum DemandSource {
  DEMAND_SOURCE_UNSPECIFIED = 0;
  DEMAND_SOURCE_RENT = 1;
  DEMAND_SOURCE_ITS_MY_BIRTHDAY = 2;
  DEMAND_SOURCE_FORCED_DEAL = 3;
  DEMAND_SOURCE_SLY_DEAL = 4;
  DEMAND_SOURCE_DEAL_BREAKER = 5;
  DEMAND_SOURCE_JUST_SAY_NO = 6;
  DEMAND_SOURCE_DEBT_COLLECTOR = 7;
}

message Demand {
  string id = 1;
  string player_id = 2;
  string source_id = 3;
  DemandKind demand_kind = 4;
  oneof demand {
    PaymentDemand payment_demand = 5;
    PropertyDemand property_demand = 6;
    PropertySetDemand property_set_demand = 7;
  }
  bool is_active = 8;
  DemandSource demand_source = 9;
}

message PendingRent {
  string player_id = 1;
  repeated string target_ids = 2;
  int32 base_amount = 3;
  int32 multiplier = 4;
}

message AssetImage {
  AssetKey asset_key = 1;
  string image_url = 2;
}

message Deadline {
  int64 deadline_ms = 1;
  optional string demand_id = 2;
}

message GameState {
  int32 seq_num = 1;
  repeated Player players = 2;
  string current_player_id = 3;
  int32 moves_left = 4;
  Hand your_hand = 5;
  repeated Money money = 6;
  repeated PropertySet properties = 7;
  repeated Demand demands = 8;
  optional PendingRent pending_rent = 9;
  Card last_action = 10;
  repeated AssetImage asset_images = 11;
  int32 max_hand_size = 12;
  repeated Deadline deadlines = 13;
}

enum ActionKind {
  ACTION_KIND_UNSPECIFIED = 0;

  ACTION_KIND_PLAY_MONEY = 1;
  ACTION_KIND_PLAY_PROPERTY = 2;
  ACTION_KIND_PLAY_HOUSE = 3;
  ACTION_KIND_PLAY_HOTEL = 4;
  ACTION_KIND_PLAY_PASS_GO = 5;
  ACTION_KIND_DEMANDS_CREATED = 6;
  ACTION_KIND_PENDING_RENT_CREATED = 7;
  ACTION_KIND_DEMAND_COMPLIED = 8;
  ACTION_KIND_DISCARD_CARDS = 9;
  ACTION_KIND_START_TURN = 10;
  ACTION_KIND_REARRANGE_CARD = 11;
}

message PlayMoney {
  string card_id = 1;
}

message ActionPlayMoney {
  Card card = 1;
}

message PlayProperty {
  string card_id = 1;
  optional string property_set_id = 2;
  optional Color active_color = 3;
}

message ActionPlayProperty {
  PropertySet property_set = 1;
}

message PlayHouse {
  string card_id = 1;
  string property_set_id = 2;
}

message ActionPlayHouse {
  Card card = 1;
  PropertySet property_set = 2;
}

message PlayHotel {
  string card_id = 1;
  string property_set_id = 2;
}

message ActionPlayHotel {
  Card card = 1;
  PropertySet property_set = 2;
}

message PlayPassGo {
  string card_id = 1;
}

message ActionPlayPassGo {
  Card last_played_card = 1;
  repeated Card cards = 2;
}

message MaskedActionPlayPassGo {
  Card last_played_card = 1;
  int32 num_cards = 2;
}

message ActionDemandsCreated {
  optional Card last_played_card = 1;
  optional Demand denied_demand = 2;
  repeated Demand demands = 3;
}

message PlayItsMyBirthday {
  string card_id = 1;
}

message PlayDebtCollector {
  string card_id = 1;
  string target_id = 2;
}

message ActionPendingRentCreated {
  Card last_card_played = 1;
  PendingRent pending_rent = 2;
}

message ResolvePendingRent {

}

message ActionPendingRentResolved {
  repeated Demand demands = 1;
}

message PlayRent {
  string card_id = 1;
}

message PlayWildRent {
  string card_id = 1;
  string target_id = 2;
}

message PlayDoubleTheRent {
  string card_id = 1;
}

message PlaySlyDeal {
  string card_id = 1;
  string target_id = 2;
  string target_card_id = 3;
}

message PlayForcedDeal {
  string card_id = 1;
  string target_id = 2;
  string source_card_id = 3;
  string target_card_id = 4;
}

message PlayDealBreaker {
  string card_id = 1;
  string target_id = 2;
  string property_set_id = 3;
}

message ComplyPaymentDemand {
  string demand_id = 1;
  repeated string card_ids = 2;
}

message ComplyPropertyDemand {
  string demand_id = 1;
  optional string property_set_id = 2;
}

message ComplyPropertySetDemand {
  string demand_id = 1;
}

message TransferCards {
  string source_id = 1;
  string target_id = 2;
  repeated Card cards = 3;
  repeated PropertySet property_sets = 4;
  int32 source_sets = 5;
  int32 source_money = 6;
  int32 target_sets = 7;
  int32 target_money = 8;
}

message TransferProperty {
  string source_id = 1;
  string target_id = 2;
  repeated PropertySet source_property_sets = 3;
  repeated PropertySet target_property_sets = 4;
}

message TransferPropertySet {
  string source_id = 1;
  string target_id = 2;
  PropertySet property_set = 3;
}

message ActionDemandComplied {
  string demand_id = 1;
  oneof transfer {
    TransferCards transfer_cards = 2;
    TransferProperty transfer_property = 3;
    TransferPropertySet transfer_property_set = 4;
  }
}

message DenyDemand {
  string demand_id = 1;
  string card_id = 2;
}

message DiscardCards {
  repeated string card_ids = 1;
}

message ActionDiscardCards {
  repeated Card cards = 1;
}

message MaskedActionDiscardCards {
  int32 num_cards = 1;
}

message CompleteTurn {

}

message ActionStartTurn {
  repeated Card cards = 1;
  int32 moves_left = 2;
}

message MaskedActionStartTurn {
  int32 num_cards = 1;
  int32 moves_left = 2;
}

message RearrangeCard {
  string card_id = 1;
  optional string property_set_id = 2;
  optional Color color = 3;
}

message ActionRearrangeCard {
  optional Card card = 1;
  PropertySet property_set = 2;
  int32 sets = 3;
}

message WonGame {
  string player_id = 1;
  int32 num_completed_sets = 2;
  int32 money = 3;
}

message Action {
  string player_id = 1;
  ActionKind kind = 2;
  int32 seq_num = 3;
  int64 turn_deadline_ms = 4;
  oneof payload {
    ActionPlayMoney action_play_money = 5;
    ActionPlayProperty action_play_property = 6;
    ActionPlayHouse action_play_house = 7;
    ActionPlayHotel action_play_hotel = 8;
    ActionPlayPassGo action_play_pass_go = 9;
    MaskedActionPlayPassGo masked_action_played_pass_go = 10;
    ActionDemandsCreated action_demands_created = 11;
    ActionPendingRentCreated action_pending_rent_created = 12;
    ActionPendingRentResolved action_pending_rent_resolved = 13;
    ActionDemandComplied action_demand_complied = 14;
    ActionDiscardCards action_discard_cards = 15;
    MaskedActionDiscardCards masked_action_discard_cards = 16;
    ActionStartTurn action_start_turn = 17;
    MaskedActionStartTurn masked_action_start_turn = 18;
    ActionRearrangeCard action_rearrange_card = 19;
  }
}

message ActionHistory {
  Action action = 1;
}

message ClientMessage {
  oneof payload {
    Chat chat = 1;
    PlayMoney play_money = 2;
    PlayProperty play_property = 3;
    CompleteTurn complete_turn = 4;
    PlayPassGo play_pass_go = 5;
    PlayItsMyBirthday play_its_my_birthday = 6;
    PlayDebtCollector play_debt_collector = 7;
    PlayRent play_rent = 8;
    PlayWildRent play_wild_rent = 9;
    PlayDoubleTheRent play_double_the_rent = 10;
    ResolvePendingRent resolve_pending_rent = 11;
    RearrangeCard rearrange_card = 12;
    DiscardCards discard_cards = 13;
    DenyDemand deny_demand = 14;
    PlaySlyDeal play_sly_deal = 15;
    ComplyPropertyDemand comply_property_demand = 16;
    PlayForcedDeal play_forced_deal = 17;
    PlayDealBreaker play_deal_breaker = 18;
    ComplyPropertySetDemand comply_property_set_demand = 19;
    ComplyPaymentDemand comply_payment_demand = 20;
    PlayHouse play_house = 21;
    PlayHotel play_hotel = 22;
  }
}

message ServerMessage {
  oneof payload {
    Error error = 1;
    ChatReceived chat_received = 2;
    GameState game_state = 3;
    WonGame won_game = 4;
    Action action = 5;
    ActionHistory action_history = 6;
  }
}
